chore: added indexes for tx_output and transaction tables
HathorNetwork/hathor-wallet-service-old pull request #104
Opened 2021-07-14 20:59 UTC by andreabadesso

2021-07-15 17:18 UTC, luislhl approved these changes

2021-07-15 20:24 UTC, pedroferreira1 requested changes
I like the indexes, I just don't like that the models are not reflecting the same as in the database.

Shouldn't we add in the models as well? Just like here: https://github.com/HathorNetwork/hathor-wallet-service/blob/dev/db/models/transaction.js#L46

2021-07-15 21:13 UTC, andreabadesso commented
@pedroferreira1 You are absolutely correct. Fixed in f79b38a5123393a20876f0bc392e4fe0530d1982

2021-07-16 00:43 UTC, pedroferreira1 approved these changes

2021-07-18 17:53 UTC, merged