feat: wallet tokens api
HathorNetwork/hathor-wallet-service-old pull request #107
Opened 2021-07-19 19:31 UTC by andreabadesso

This was a request from @pedroferreira1 so he can be able to list all tokens a wallet has using the wallet-lib without needing to fetch the full wallet tx history.

2021-07-20 12:20 UTC, pedroferreira1 commented on src/db.ts
> + * Gets a list of tokens that a given walllet has ever interacted with
Triple 'l' in walllet

2021-07-20 12:20 UTC, pedroferreira1 commented on src/types.ts
> +  voided?: boolean | null;
Why this can be null? I always need this info

2021-07-20 21:22 UTC, msbrogli requested changes

2021-07-20 21:22 UTC, msbrogli commented on src/db.ts
> +    `SELECT DISTINCT(token_id)
Is `wallet_id` and `token_id` indexed? Maybe there should be an index `(token_id, wallet_id)` but we need to check whether this query would be able to use it. Otherwise, it might run `O(n)` and get slower and slower over time.

2021-07-20 21:22 UTC, msbrogli commented on src/types.ts
> +  voided?: boolean | null;
From the API, it seems we always load this piece of information. Am I wrong about it?

2021-07-20 21:22 UTC, msbrogli approved these changes

2021-07-22 19:07 UTC, andreabadesso commented on src/db.ts
> +    `SELECT DISTINCT(token_id)
They are not and I don't think DISTINCT(token_id) will use the index

I think I can investigate it further on https://github.com/HathorNetwork/hathor-wallet-service/issues/101

What do you think?

2021-07-22 19:08 UTC, andreabadesso commented on src/types.ts
> +  voided?: boolean | null;
You are both right, fixed in 43e50c044820496089eb809000a4db95ae5f0f97

2021-07-22 19:11 UTC, andreabadesso commented on src/db.ts
> + * Gets a list of tokens that a given walllet has ever interacted with
Fixed in fae4f886e6ada5b59907957a8ee4f04a9735e46f

2021-07-22 19:19 UTC, pedroferreira1 approved these changes

2021-07-27 18:55 UTC, msbrogli commented on src/db.ts
> +    `SELECT DISTINCT(token_id)
It seems good to me. Thanks!

2021-07-27 19:04 UTC, merged