feat: handle failure in wallet load
HathorNetwork/hathor-wallet-service-old pull request #112
Opened 2021-07-30 15:58 UTC by andreabadesso

2021-07-30 18:28 UTC, pedroferreira1 requested changes

2021-07-30 18:28 UTC, pedroferreira1 commented on tests/api.test.ts
> +
I think we should create a test for the retry feature

2021-08-05 16:12 UTC, r4mmer requested changes
Why not use an SQS for real async? Testing would be harder but the actual implementation would make more sense than having 2 lambdas running waiting for the loadAsync to finish

2021-08-05 16:12 UTC, r4mmer commented on jest.config.js
> +      branches: 85,
Why reduce the coverage threshold?

2021-08-05 16:12 UTC, r4mmer commented on src/api/wallet.ts
> +    await updateWalletStatus(mysql, walletId, WalletStatus.ERROR, newRetryCount);
When there is an error loading the wallet we update status to error and return `success=true`?

2021-08-05 16:12 UTC, r4mmer commented on src/api/wallet.ts
> +    console.error('Erroed on loadWalletAsync: ', e);
Is this log message ok? also, should we create an issue to have better loggin, instead of console statements?

2021-08-10 17:10 UTC, pedroferreira1 commented on src/db.ts
> +  const queryParams = [
What's this? Is it missing a rebase?

2021-08-10 17:10 UTC, pedroferreira1 commented on tests/api.test.ts
> +  // retrying should succeed
Maybe add a test that fails the maximum of retries and after that we can't retry anymore?

2021-08-10 17:10 UTC, pedroferreira1 commented on tests/db.test.ts
> +  utxos = await filterUtxos(mysql, { addresses: [addr1, addr2], biggerThan: 0, smallerThan: 3, authority: 1, tokenId, maxUtxos: 1 });
Another PR code?

2021-08-10 19:03 UTC, andreabadesso commented on src/api/wallet.ts
> +    await updateWalletStatus(mysql, walletId, WalletStatus.ERROR, newRetryCount);
I agree this is weird, I refactored it to still return success but with the updated status on the response body on this commit: 841423027fb9e932a5601d31b7d47963cf92f908

The idea here is that the wallet client expects this to be async, the first request is to begin the load wallet mechanism, he will then poll the server until the state changes from `CREATING` to `READY` or `ERROR` 

So the first request worked, but the state changed to `ERROR` instantly

Does it make sense?

2021-08-10 19:04 UTC, andreabadesso commented on src/api/wallet.ts
> +    console.error('Erroed on loadWalletAsync: ', e);
It is logging correctly

I agree to have better logging though, here is the newly created issue: https://github.com/HathorNetwork/hathor-wallet-service/issues/118

2021-08-10 19:22 UTC, andreabadesso commented on tests/db.test.ts
> +  utxos = await filterUtxos(mysql, { addresses: [addr1, addr2], biggerThan: 0, smallerThan: 3, authority: 1, tokenId, maxUtxos: 1 });
You are right, it was missing a rebase.

I fixed it, can you check again?

2021-08-10 19:22 UTC, andreabadesso commented on tests/api.test.ts
> +  // retrying should succeed
I agree, done in 034f34524ddf607e150a18280aeb3c717a423ac6

2021-08-10 19:22 UTC, andreabadesso commented on src/db.ts
> +  const queryParams = [
Yes! It was missing a rebase, can you check again?

2021-08-10 21:24 UTC, andreabadesso commented on jest.config.js
> +      branches: 85,
We shouldn't, I just increased the coverage and set it back to 88

2021-08-10 21:28 UTC, andreabadesso commented
> Why not use an SQS for real async? Testing would be harder but the actual implementation would make more sense than having 2 lambdas running waiting for the loadAsync to finish

The lambda won't wait for the `loadWalletAsync` function to finish, it invokes it using `InvocationType: 'Event'` which invokes it asynchronously (https://docs.aws.amazon.com/pt_br/lambda/latest/dg/API_Invoke.html)

We could refactor it to signal the client that his wallet is ready using WebSockets, but it might finish the load process when the user has his app on background (with the WebSocket conn closed)

2021-08-10 21:36 UTC, r4mmer commented on src/api/wallet.ts
> +    await updateWalletStatus(mysql, walletId, WalletStatus.ERROR, newRetryCount);
Ok, but the status returned is the whole wallet info or just the `wallet.status`?

2021-08-10 21:40 UTC, andreabadesso commented on src/api/wallet.ts
> +    await updateWalletStatus(mysql, walletId, WalletStatus.ERROR, newRetryCount);
The whole wallet information

2021-08-10 22:09 UTC, pedroferreira1 approved these changes

2021-08-10 22:10 UTC, r4mmer approved these changes

2021-08-11 19:01 UTC, merged