feat: void old unconfirmed transactions
HathorNetwork/hathor-wallet-service-old pull request #116
Opened 2021-08-06 16:45 UTC by andreabadesso

2021-08-09 19:28 UTC, luislhl commented on src/mempool.ts
> +  console.log(`Found ${voidedTransactions.length} voided transactions older than 20m`);
Maybe we should use the variable `VOIDED_TX_OFFSET` in this log, instead of always logging `20m`.

2021-08-10 08:05 UTC, msbrogli commented
> If for some reason the daemon misses a `UPDATE_TX` WebSocket message that is voiding a mempool transaction, we need to have a way to void those transactions, otherwise, they would be "stuck" unconfirmed on our database forever, calculating the wrong balance for the involved addresses.

How can it happen? I mean, as long as the messages are arriving from the websocket, I feel the protocol guarantees the proper delivery.

> If the transaction is not voided on the full node and we missed its block confirmation, we should alert and throw an error.

It might happen if the number of transactions is high enough. For example, let's say there are many transactions arriving and we have more than two tips. In this case, the block must choose only two and the remaining will wait for the next block.

2021-08-10 08:11 UTC, msbrogli requested changes

2021-08-10 08:11 UTC, msbrogli commented on src/mempool.ts
> +  console.log(`Found ${voidedTransactions.length} voided transactions older than 20m`);
I feel it is a good message log for now (but it might happen in the future if the number of transactions grow enough). See my comment in the PR for an example.

2021-08-10 08:11 UTC, msbrogli commented on src/mempool.ts
> +      throw new Error(`Transaction ${tx.txId} not voided`);
If we can recover from it, why would we throw an exception? I mean, it should definitely open an issue to be analyzed later, but the service should keep working.

2021-08-10 16:28 UTC, luislhl commented on src/mempool.ts
> +     * TODO: [ALERT] should be replaced with the correct string to get alerted on CloudWatch/Slack
I think this can be removed, we already agreed on the `[ALERT]` string as the correct one.

2021-08-10 16:31 UTC, luislhl commented on serverless.yml
> +      - schedule: rate(20 minutes)
Don't you think we should always use a rate that is lower than the `VOIDED_TX_OFFSET` in the code?

I don't know how precise is this schedule, but if it takes only a few seconds longer to run the next iteration, we could be losing transactions when we query the database, if the rate and the `VOIDED_TX_OFFSET` are exactly the same.

Maybe we can even use the `VOIDED_TX_OFFSET` env var here in this configuration, but subtracted by some number to make sure it's lower.

2021-08-10 18:43 UTC, pedroferreira1 commented on src/db.ts
> +      height: result.height as number,
From the query, height is null, right?

2021-08-10 18:43 UTC, pedroferreira1 commented on tests/db.test.ts
> +  expect(await getMempoolTransactionsBeforeDate(mysql, 11)).toHaveLength(3);
Should we test timestamp as 9? So we will get only the first two and also check that it got the correct txs?

2021-08-10 18:43 UTC, pedroferreira1 commented on src/mempool.ts
> +    const isVoided = await isTxVoided(tx.txId);
Depending on the number of transaction we need to check on the full node this method might take more than 6 seconds, right? I am thinking about the default timeout of the lambda but not sure if it's relevant.

2021-08-10 21:37 UTC, andreabadesso commented on src/mempool.ts
> +  console.log(`Found ${voidedTransactions.length} voided transactions older than 20m`);
I agree, done in 959e44e03f5fbc453bb771f1dd80abf5c40c3bb7

2021-08-10 21:39 UTC, andreabadesso commented on src/mempool.ts
> +     * TODO: [ALERT] should be replaced with the correct string to get alerted on CloudWatch/Slack
Done in 5214328ab16d76347b3727c8237873ea7a67319a

2021-08-10 21:39 UTC, andreabadesso commented on serverless.yml
> +      - schedule: rate(20 minutes)
Done in 959e44e

2021-08-10 21:56 UTC, andreabadesso commented on src/db.ts
> +      height: result.height as number,
Yes it is, do you think we should return a hard-coded `null` there? The type cast will also return null (as it is coming from the database)

2021-08-10 22:00 UTC, andreabadesso commented on tests/db.test.ts
> +  expect(await getMempoolTransactionsBeforeDate(mysql, 11)).toHaveLength(3);
I agree, done in 605dc4c144aefc805d38501c1bf84038cfa9d0a2

2021-08-10 22:01 UTC, andreabadesso commented on src/mempool.ts
> +    const isVoided = await isTxVoided(tx.txId);
I've tested with the testnet synced database and it averaged below 1s, I think we can leave it on the default timeout and observe it before increasing it

2021-08-10 22:11 UTC, andreabadesso commented
> How can it happen? I mean, as long as the messages are arriving from the websocket, I feel the protocol guarantees the proper delivery.

It can (and will) happen when the daemon is restarted because we don't have a voided transaction API on the fullnode, so we can't fetch the list of transactions that were voided recently

I agree that as long as the messages are arriving from the WebSocket the protocol guarantees the proper delivery though

> It might happen if the number of transactions is high enough. For example, let's say there are many transactions arriving and we have more than two tips. In this case, the block must choose only two and the remaining will wait for the next block.

@msbrogli I feel that in this case, it would be better to just increase the env variable (from 20 minutes to something higher that guarantees that the tx should have been confirmed. Maybe in the future this could change from a environmental variable to some value that is generated observing the average transaction confirmation time. What do you think?

2021-08-11 18:21 UTC, andreabadesso commented on src/mempool.ts
> +      throw new Error(`Transaction ${tx.txId} not voided`);
I think I agree, refactored it in d65122eb9a7d6ff184f28e35ae8ed65164949bac to download the `first_block` transaction from the fullnode, get its height and confirm the transaction using it

2021-08-11 20:01 UTC, pedroferreira1 commented on src/db.ts
> +      height: result.height as number,
If the type cast returns null I think it's ok. I was just thinking if it was really needed in the return because it's always null anyway.

2021-08-11 20:02 UTC, pedroferreira1 commented on src/mempool.ts
> +    const isVoided = await isTxVoided(tx.txId);
Yeah, I agree. I think we just need to make sure things will keep consistency if a timeout happens in the middle of the processing. From what I saw, I don't see any problems. What do you think?

2021-08-11 20:03 UTC, pedroferreira1 commented on tests/db.test.ts
> +  expect(await getMempoolTransactionsBeforeDate(mysql, 11)).toHaveLength(3);
Should we check if the txs are the correct one? you are just checking the length, right?

2021-08-11 20:07 UTC, pedroferreira1 commented on src/mempool.ts
> +  console.log(`Found ${voidedTransactions.length} voided transactions older than 20m`);
You changed only the serverless yml in this commit

2021-08-11 20:09 UTC, pedroferreira1 approved these changes

2021-08-12 19:11 UTC, andreabadesso commented on src/mempool.ts
> +  console.log(`Found ${voidedTransactions.length} voided transactions older than 20m`);
@pedroferreira1 you are absolutely correct

Fixed in ce4e42fbbd8627a0464543917d4df3e979411d1c

Also fixed an error on the logic that was not multiplying the env variable setting by 60, calculating it as seconds instead of minutes

2021-08-12 19:18 UTC, andreabadesso commented on tests/db.test.ts
> +  expect(await getMempoolTransactionsBeforeDate(mysql, 11)).toHaveLength(3);
I agree, done in 9f71e85bc7ee5cd58dda88f541001c3536453719

2021-08-12 19:18 UTC, andreabadesso commented on src/mempool.ts
> +    const isVoided = await isTxVoided(tx.txId);
I agree, I don't see any problems since we will try again in the next scheduled run

2021-08-12 20:51 UTC, r4mmer approved these changes

2021-08-13 18:19 UTC, luislhl approved these changes

2021-08-30 20:55 UTC, merged