feat: rollback balance calculation on txProcessor errors
HathorNetwork/hathor-wallet-service-old pull request #117
Opened 2021-08-09 17:48 UTC by andreabadesso

2021-08-10 06:54 UTC, msbrogli requested changes

2021-08-10 06:54 UTC, msbrogli commented on src/txProcessor.ts
> +  try {
I don't feel we should use the transactions with this huge try/catch block. Why don't we create a decorator that does:

```js
function dbTransactionDecorator(wrapped) {
  return async function() {
    try {
      await beginTransaction(mysql);
      const result = wrapped.apply(this, arguments);
      await commitTransaction(mysql);
      return result;
    } catch {
      await rollbackTransaction(mysql);
    }
  }
}
```

2021-08-10 22:25 UTC, pedroferreira1 commented on src/db.ts
> +/**
Should we move this code to another file? This one already has > 2k lines and has the methods to connect lambdas <> db.

I feel those new methods belong to a db utils, or any other name, what do you think?

2021-08-12 17:54 UTC, andreabadesso commented on src/db.ts
> +/**
I agree, done in d3421a66f29f21ca6a0ce695912cc606ede41009

2021-08-12 17:56 UTC, andreabadesso commented on src/txProcessor.ts
> +  try {
I agree that a decorator would be better, I've just committed something like your suggestion in d3421a66f29f21ca6a0ce695912cc606ede41009

The only problem with this approach is that typescript does not support decorators yet, they do have an experimental version of decorators but only for class methods

So to be able to use the decorator pattern, I had to ignore some type errors as the decorator will expect any function as a parameter

What do you think?

2021-08-13 07:06 UTC, msbrogli commented on src/txProcessor.ts
> +  try {
I got it. I saw your solution and I think we shouldn't require the caller to know the decorator is necessary. But I don't think we should move forward with it because of the type errors.

In this case, maybe we should move the code to `_unsafeAddNewTx()` and create a `addNewTx()` that works as the wrapper. For example:

```js
async function addNewTx(...) {
  try {
    await beginTransaction(mysql);
    const result = await _unsafeAddNewTx(...);
    await commitTransaction(mysql);
    return result;
  } catch {
    await rollbackTransaction(mysql);
  }
}
```

What do you think?

2021-08-16 17:04 UTC, andreabadesso commented on src/txProcessor.ts
> +  try {
I think it is better than the huge try/catch block

I agree that it is the best solution until TypeScript supports function decorators

Done in 65b85c1215c96ca94ef5479a4e31c64da6331540

What do you think?

2021-08-17 18:30 UTC, pedroferreira1 approved these changes

2021-08-17 18:59 UTC, msbrogli commented on src/txProcessor.ts
> +  try {
I like it. But it seems we are globally disabling a linter check. Should we do it locally?

2021-08-17 18:59 UTC, msbrogli approved these changes

2021-08-17 19:48 UTC, merged