ci: Create buildspec.yml for CodeBuild deployments
HathorNetwork/hathor-wallet-service-old pull request #137
Opened 2021-08-30 18:12 UTC by luislhl

### Acceptance Criteria
- CodeBuild should be capable of knowing which branch/tag it should deploy
- It should run migrations and deploy the Lambdas to the right environment, according to the branch/tag

2021-08-30 18:58 UTC, andreabadesso requested changes

2021-08-30 18:58 UTC, andreabadesso commented on docs/2021-07-29-infrastructure-design.md
> +4. CodePipeline calls its next step, which is asking for Manual Approval. A message is sent to Slack channel `#deploys`.
That is cool. Will there also be a button for approval on Slack?

If not, where do I approve the deploy?

2021-08-30 18:58 UTC, andreabadesso commented on .codebuild/buildspec.yml
> +  #post_build:
Remove?

2021-08-30 19:19 UTC, luislhl commented on docs/2021-07-29-infrastructure-design.md
> +4. CodePipeline calls its next step, which is asking for Manual Approval. A message is sent to Slack channel `#deploys`.
You click the link on Slack that will lead you to a CodePipeline page with the button.

2021-08-30 21:54 UTC, luislhl commented on .codebuild/buildspec.yml
> +  #post_build:
Done

2021-08-31 02:24 UTC, pedroferreira1 approved these changes

2021-08-31 02:24 UTC, pedroferreira1 commented on README.md
> +## Standard Operating Procedures
Should this be removed? Did you start here and moved to the other file?

2021-08-31 02:24 UTC, pedroferreira1 commented on docs/2021-07-29-infrastructure-design.md
> +2. This project checks the branch and the author of the commit, to decide if it should run the build. If so, it runs some steps that are defined inline in the project, to write to a file which branch
Why do you check the author of the commit? Depending on the author you do different things?

2021-08-31 14:05 UTC, luislhl commented on docs/2021-07-29-infrastructure-design.md
> +2. This project checks the branch and the author of the commit, to decide if it should run the build. If so, it runs some steps that are defined inline in the project, to write to a file which branch
Only specific authors will trigger a deploy. A commit from someone that is not in the list will not trigger a deploy.

This is a built-in feature of CodeBuild and is explained better in the first best practice described in https://docs.aws.amazon.com/codebuild/latest/userguide/webhooks.html?icmpid=docs_acb_console#webhook-best-practices

2021-08-31 14:06 UTC, luislhl commented on README.md
> +## Standard Operating Procedures
There should be a link here to the other file, I'll fix this.

2021-08-31 14:09 UTC, luislhl commented on README.md
> +## Standard Operating Procedures
Done

2021-08-31 14:11 UTC, andreabadesso approved these changes

2021-08-31 16:43 UTC, merged