feat: added total supply api
HathorNetwork/hathor-wallet-service-old pull request #165
Opened 2021-11-08 16:11 UTC by andreabadesso

# Acceptance criteria

- The total supply API must return the sum of all HTR utxos, excluding the burned ones.
- The API must only be called using aws-sdk and should not have a API Gateway API

2021-11-08 19:16 UTC, pedroferreira1 approved these changes

2021-11-08 19:16 UTC, pedroferreira1 commented on tests/db.test.ts
> +test('getTotalSupply', async () => {
Should we add a utxo with burn address in the test?

2021-11-09 18:58 UTC, andreabadesso commented on tests/db.test.ts
> +test('getTotalSupply', async () => {
Done in 9cef83a175806bee4220610bd34f1afcc5ad2388

2021-11-10 17:37 UTC, r4mmer requested changes

2021-11-10 17:37 UTC, r4mmer commented on src/db/index.ts
> +       AND address != 'HDeadDeadDeadDeadDeadDeadDeagTPgmn'`);
Should we add this address as a constant somewhere?

2021-11-10 17:37 UTC, r4mmer commented on src/db/index.ts
> +       AND token_id = '00'
Should we use `token_id` as a parameter? We could get the total supply of any token.

2021-11-11 20:32 UTC, andreabadesso commented on src/db/index.ts
> +       AND address != 'HDeadDeadDeadDeadDeadDeadDeagTPgmn'`);
Added it as a constant on top of the file on commit de275e0beb1077b66e85dc50e42ea42c6e8a7158

The testnet has no burn address and tests run on mainnet so I guess this is fine for now as we don't have a constants file on this project

2021-11-12 19:06 UTC, andreabadesso commented on src/db/index.ts
> +       AND token_id = '00'
That's a great idea, done in fbf73d358495d0c6d109d002ccb7d1599eb6e32f

I'm receiving the token_id on body because this is not a HTTP API exposed by the Api Gateway, it is called using the aws-sdk

2021-11-17 21:59 UTC, r4mmer approved these changes

2021-11-18 18:39 UTC, merged