feat: added methods to unlock old timelocked utxos
HathorNetwork/hathor-wallet-service-old pull request #174
Opened 2021-12-13 20:01 UTC by andreabadesso

### Acceptance Criteria
- Timelocked utxos should be unlocked on the first block after its timelock expiration time
- Balances should be re-calculated considering the unlocked balance from those utxos

### Motivation

The wallet service will currently only evaluate whether an timelocked utxo should be unlocked when a tx that spends this utxo is synced. This worked because transactions were not made using the wallet service, but now that transactions will be made using the `txProposalCreate` mechanism, those utxos will never be returned from the `findUtxos` lambda and so will never be unlocked.

NOTICE: I am running the `unlockTimelockedUtxos` method on every block transaction so the maximum delay between the actual timelock timestamp and the unlock will be the current interval between blocks.

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2021-12-14 16:41 UTC, r4mmer approved these changes

2021-12-14 16:43 UTC, r4mmer reviewed
Maybe we can have a method to update balance from `addressBalanceMap`, the process to update address balance then update all wallets affected is present in more than one place

2021-12-14 19:29 UTC, pedroferreira1 requested changes

2021-12-14 19:29 UTC, pedroferreira1 commented on src/commons.ts
> +  const outputs: TxOutput[] = utxos.map((utxo) => {
This map is exactly the same as in the `unlockUtxos` method, as far as I understood, and if there are differences we can parametrize them. I think would be better to have a method to map utxo -> TxOutput

2021-12-14 19:29 UTC, pedroferreira1 commented on src/commons.ts
> +  if (utxos.length === 0) return;
Actually this whole method seems to be exactly the same as `unlockUtxos`. What's the difference between them?

And looks like you missed one method call `await dbUnlockUtxos(mysql, utxos);`, or you don't need this method here?

Why don't you use the same method?

2021-12-14 19:29 UTC, pedroferreira1 commented on src/commons.ts
> +  if (utxos.length === 0) return;
I think I understand now, the method `dbUnlockTimelockedUtxos` already calls `dbUnlockUtxos`.

Why don't you change a bit and create a `getTimelockedUtxosToUnlock` instead of `dbUnlockTimelockedUtxos`? So you just get the utxos and call `unlockUtxos`, which is pretty much the same as this method here?

2021-12-14 19:29 UTC, pedroferreira1 commented on src/txProcessor.ts
> +    // (that will unlock it).
Maybe make it clear here that we are adding this delay only in the wallet, the protocol will accept any transaction spending a timelocked output as soon as it's expired.

2021-12-15 15:29 UTC, andreabadesso commented on src/commons.ts
> +  if (utxos.length === 0) return;
You are right.

Refactored in 6784c9aec96d79f9941822faf29c8ad2f6a19640

2021-12-15 16:02 UTC, pedroferreira1 requested changes

2021-12-15 16:02 UTC, pedroferreira1 commented on src/db/index.ts
> + * Get timelocked utxos from the database
I don't like the docstring and the method name. You are not getting timelocked utxos, you are actually getting utxos that must be unlocked from timelock.

2021-12-15 20:31 UTC, andreabadesso commented on src/txProcessor.ts
> +    // (that will unlock it).
Done in 530468475a3f40c1d3f00c464f62c31cbe8ec0b0

2021-12-15 20:42 UTC, andreabadesso commented on src/db/index.ts
> + * Get timelocked utxos from the database
Renamed the method (and docstring) on 959e7577e4b95f74582d5e9a904a148a32af8ee6

2021-12-15 21:20 UTC, pedroferreira1 approved these changes

2021-12-16 14:22 UTC, merged