refactor: auth xpubkey
HathorNetwork/hathor-wallet-service-old pull request #178
Opened 2022-02-03 18:18 UTC by andreabadesso

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-02-10 16:51 UTC, r4mmer requested changes

2022-02-10 16:51 UTC, r4mmer commented on src/api/auth.ts
> +import { verifySignature, closeDbConnection, getDbConnection } from '@src/utils';
Maybe remove the `getWalletId` import above since it's not being used

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
```suggestion
```

2022-02-10 16:51 UTC, r4mmer commented on db/models/wallet.js
> +    auth_xpubkey: {
Should `auth_xpubkey` be unique? We don't need this for `xpubkey` because the id is generated from the `xpubkey`.

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  const timestamp = value.timestamp;
I think we should validate that timestamp is not too old.

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  const timestamp = value.timestamp;
Same here

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  if (process.env.CONFIRM_FIRST_ADDRESS === 'true') {
Maybe have logic to test the first address inside a helper since it's used on other handlers.

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  if (!signaturesValid) {
```suggestion
  if (!validateSignatures(walletId, timestamp, xpubkeyStr, xpubkeySignature, authXpubkeyStr, authXpubkeySignature)) {
```

2022-02-10 16:51 UTC, r4mmer commented on src/api/wallet.ts
> +  if (process.env.CONFIRM_FIRST_ADDRESS === 'true') {
I saw that before we didn't check the first address if the wallet already existed, do we need to check it for every request?

2022-02-10 16:51 UTC, r4mmer commented on tests/integration.test.ts
> +block.outputs = [createOutput(0, blockReward, 'HBCQgVR8Xsyv1BLDjf9NJPK1Hwg4rKUh62')];
Why not use `ADDRESSES[0]`? same for other addresses on this file

2022-02-10 16:51 UTC, r4mmer commented on tests/utils.ts
> +export const TEST_SEED = 'neither image nasty party brass oyster treat twelve olive menu invest title fan only rack draw call impact use curtain winner horn juice unlock';
Should we have a test to check that the xpub, auth_xpub and addresses are generated from this seed correctly?

2022-02-11 15:14 UTC, andreabadesso commented on src/api/auth.ts
> +import { verifySignature, closeDbConnection, getDbConnection } from '@src/utils';
Fixed in 7f01b12080229859bc6796c39cc26b6a853864b9, thanks

2022-02-11 15:15 UTC, andreabadesso commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
Why?

2022-02-11 15:18 UTC, andreabadesso commented on db/models/wallet.js
> +    auth_xpubkey: {
Wow, you are right, I hadn't thought about it on the design

I don't like the idea of it being unique, I think that maybe we should require the user to send the `walletId` of his wallet and store it (encrypted with the PIN) on the wallet-lib

What do you think, @r4mmer and @pedroferreira1 ?

2022-02-14 15:04 UTC, pedroferreira1 commented on db/models/wallet.js
> +    auth_xpubkey: {
I don't see any reasons why someone would like to use the same auth xpub for more than one wallet. Why you don't like it being unique? I feel it's natural to be unique.

I was thinking about multisig or any other reasons to reuse the auth xpub but nothing came to my mind. But also if you decide to go with `walletId` stored and sending it in the request it seems ok as well (but I think I prefer setting it as unique).

2022-02-14 15:05 UTC, pedroferreira1 commented on db/models/wallet.js
> +    auth_xpubkey: {
What's the reason to have an API to change the auth xpub? Maybe this is a good reason to allow repeated xpubs here

2022-02-14 15:48 UTC, pedroferreira1 commented on src/db/index.ts
> +export const getWalletFromAuthXpub = async (mysql: ServerlessMysql, authXpub: string): Promise<Wallet> => {
If we have this method here, then I think we must require the `authXpub` to be unique. If we don't do that, we should change this method to get from `walletId` only

2022-02-14 15:48 UTC, pedroferreira1 commented on src/db/index.ts
> +    return {
Should we create a method to get pretty return of wallet data? If we add a new field in the future we must remember to add it in all returns.

2022-02-14 15:48 UTC, pedroferreira1 commented on tests/api.test.ts
> +  const authXpubkeySignature = authMessage.sign(authDerivedPrivKey.privateKey);
Should we have a test with a wrong signature here and the in the other xpubkey? Just so we can confirm that we are only creating the wallet with both signatures valid

2022-02-14 15:53 UTC, r4mmer commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
The `maxGap` was not being used

2022-02-14 16:51 UTC, andreabadesso commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
Oh, this was on the `changeAuthXpub` method, right?

I must have removed it before reading your comment, thanks

2022-02-14 16:54 UTC, andreabadesso commented on src/api/wallet.ts
> +  if (process.env.CONFIRM_FIRST_ADDRESS === 'true') {
Good idea, done in f053b93eaf64af3f61919142148b637efda6cc76

2022-02-14 17:14 UTC, andreabadesso commented on src/api/wallet.ts
> +  if (!signaturesValid) {
Done in 3255889978e41c2b5df0daee084a753e61e90f48

2022-02-14 17:15 UTC, andreabadesso commented on src/api/wallet.ts
> +  if (process.env.CONFIRM_FIRST_ADDRESS === 'true') {
You are right, we don't need to, and those calls are expensive

Fixed in 64f6fe4594d72462ef4885a283a0afec677635e0

2022-02-14 17:39 UTC, andreabadesso commented on tests/integration.test.ts
> +block.outputs = [createOutput(0, blockReward, 'HBCQgVR8Xsyv1BLDjf9NJPK1Hwg4rKUh62')];
Way better, thanks

Done in 7015d74648ab042a6ab1ead0533a2e66316956c1

2022-02-14 17:51 UTC, andreabadesso commented on db/models/wallet.js
> +    auth_xpubkey: {
I don't quite remember why I thought it would be a bad idea to set the `auth_xpubkey` to be unique, I guess I was thinking that since we don't enforce the user to use the different purpose path, he could use anything he wants to and that could lead to two users using the same `auth_xpubkey`, but both would have to prove they own it, so I dont think this is a problem

I have set the column as unique on b0ff81bac9db71f955b9cef41832ceb988d52258

2022-02-14 18:41 UTC, andreabadesso commented on src/api/wallet.ts
> +  const timestamp = value.timestamp;
I agree, done in e16ea1c38e44364cdb87a6fb8d703998f4925634

2022-02-14 18:42 UTC, andreabadesso commented on src/api/wallet.ts
> +  const timestamp = value.timestamp;
I agree, done in e16ea1c38e44364cdb87a6fb8d703998f4925634

2022-02-14 19:07 UTC, andreabadesso commented on src/db/index.ts
> +    return {
We should, done in 35069d8d69b4eb1b04fe4da9d8b1e14848a41cbe

2022-02-14 19:28 UTC, andreabadesso commented on tests/api.test.ts
> +  const authXpubkeySignature = authMessage.sign(authDerivedPrivKey.privateKey);
We should, done in 73488047aac3920280f71eca8bfee84c669919eb

Also fixed a potential problem with invalid user input

2022-02-14 19:55 UTC, andreabadesso commented on tests/utils.ts
> +export const TEST_SEED = 'neither image nasty party brass oyster treat twelve olive menu invest title fan only rack draw call impact use curtain winner horn juice unlock';
That's a great idea, thanks!

Done in 83d8bb74a92033529a6d1b6e94ed55753cc8cb57

2022-02-14 20:06 UTC, r4mmer approved these changes

2022-02-14 23:19 UTC, andreabadesso commented on db/models/wallet.js
> +    auth_xpubkey: {
@r4mmer 

I've refactored the `tokenHandler` to accept the `walletId` as a parameter

This way, we don't have to set the `auth_xpubkey` to unique

The problem with setting `auth_xpubkey` as unique is that someone might want to use multiple wallets from the same seed

This is the refactor commit: 06f4126b4d167231c83fb71369f12bdd7e2b1d1b

2022-02-14 23:48 UTC, andreabadesso commented on src/db/index.ts
> +export const getWalletFromAuthXpub = async (mysql: ServerlessMysql, authXpub: string): Promise<Wallet> => {
This method has been removed as we are not using it anymore since the refactor on 06f4126b4d167231c83fb71369f12bdd7e2b1d1b

2022-02-15 00:46 UTC, pedroferreira1 approved these changes

2022-02-25 14:51 UTC, merged