feat: token info api
HathorNetwork/hathor-wallet-service-old pull request #202
Opened 2022-04-11 16:14 UTC by andreabadesso

## Motivation

Currently, our wallet desktop is querying the fullnode for token details, we need an API to return the information necessary to show token details on the "About" section of our wallet.

### Important

We are currently limiting the max number of authorities returned by this API to `100`. This was done to prevent users that created a large number of authorities (since this is a free operation) to spam this API, causing a lot of bandwidth use

### Acceptance Criteria

- We should have an API to return token details
- The API should require the user to be authenticated
- This API should have the following information:
  - Total supply of the requested token
  - Total number of transactions on the requested token
  - List of unlocked utxos with authorities for the requested token
  - Details (uid, name, symbol) for the requested token

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-04-11 18:17 UTC, andreabadesso commented on tests/utils.ts
> +export const getAuthData = (now: number): any => {
This is just a refactor I did but ended up not using anywhere else than the `loadWallet should update wallet status to ERROR if an error occurs` test

2022-04-13 18:09 UTC, pedroferreira1 requested changes

2022-04-13 18:09 UTC, pedroferreira1 commented on src/db/index.ts
> +   LIMIT 100
I think we shouldn't have this limit here. Why don't you create another method `hasMintAuthority` and `hasMeltAuthority`?

With this method you might be returning the wrong information to the wallet desktop. If you have 100 mint authorities and 1 melt authority, then you might be returning only the mint and will show in the desktop wallet that there are no melt authorities.

I think would be better to create a method that we can trust and fulfills the needs that we have.

2022-04-13 18:09 UTC, pedroferreira1 commented on src/db/index.ts
> +export const getTotalTransactions = async (
When you count the `tx_output` table you might be ignoring some transactions, if I'm not wrong.

One example is a destroy authority transaction, that you have inputs but doesn't have outputs.

Another one is a possible situation where you have a transaction with a single output that is a `DataScript`. Given that you don't store data script outputs in this table, you would also be ignoring this transaction.

Don't you have another table to gather this information? Maybe the tx_history table?

2022-04-13 18:09 UTC, pedroferreira1 commented on src/api/tokens.ts
> +  const tokenInfo: TokenInfo = await getTokenInformation(mysql, tokenId);
If the tokens does not exist in the database what happens? Should we get this info here and return 400? Better than doing all the other queries.

2022-04-13 19:45 UTC, r4mmer commented on src/api/tokens.ts
> +  const availableAuthorities: DbTxOutput[] = await getAvailableAuthorities(mysql, tokenId);
Should we make these queries as a `Promise.all`?

2022-04-14 21:52 UTC, andreabadesso commented on src/db/index.ts
> +export const getTotalTransactions = async (
You are absolutely right, we can use the `address_tx_history` table.

Done in 926a4b8a7c60faec094ecd6bf3ef67666dd9e4e5

I also had to add an index on the `token_id` column to the `address_tx_history` table, this was done in c36a00b541830c54d52b0da82624e83a3d7c8de4

2022-04-14 21:53 UTC, andreabadesso commented on src/api/tokens.ts
> +  const tokenInfo: TokenInfo = await getTokenInformation(mysql, tokenId);
You are right, done in 9ef91e72f5a51ca3fbe5777f14247e18cbe2b1c9

2022-04-14 21:53 UTC, andreabadesso commented on src/api/tokens.ts
> +  const availableAuthorities: DbTxOutput[] = await getAvailableAuthorities(mysql, tokenId);
We absolutely should, thanks!

Done in 2e48bad426314e9f756a48bf210180cf1e8d1943

2022-04-14 21:55 UTC, andreabadesso commented on src/db/index.ts
> +   LIMIT 100
I updated the API to return `true` or `false` on the authorities object, can you please check again? I would link the commit here but it was done on multiple commits as it is a bigger refactor 

I removed the LIMIT from the `getAvailableAuthorities` but didn't remove the method, even though it isn't being used anymore I feel that it might in the future

2022-04-19 01:14 UTC, pedroferreira1 commented on src/db/index.ts
> +): Promise<DbTxOutput> => {
Should this be `Promise<DbTxOutput | null>`? If we have no authorities, we return `null`, right?

2022-04-19 01:21 UTC, pedroferreira1 approved these changes

2022-04-19 01:21 UTC, pedroferreira1 commented on tests/api.test.ts
> +    ['txId', 2, token1.id, ADDRESSES[0], 0, constants.TOKEN_MINT_MASK, null, null, false, null], // melt
The mask is mint but the comment says melt

2022-04-19 19:00 UTC, andreabadesso commented on src/db/index.ts
> +): Promise<DbTxOutput> => {
Fixed in 917c25e0e495b49576e8f7844a7d05970545ff42

2022-04-19 19:00 UTC, andreabadesso commented on tests/api.test.ts
> +    ['txId', 2, token1.id, ADDRESSES[0], 0, constants.TOKEN_MINT_MASK, null, null, false, null], // melt
Fixed in 917c25e0e495b49576e8f7844a7d05970545ff42

2022-04-20 20:09 UTC, r4mmer approved these changes

2022-04-22 15:10 UTC, merged