feat: tx proposal (2)
HathorNetwork/hathor-wallet-service-old pull request #22
Opened 2021-02-25 19:31 UTC by andreabadesso

2021-02-26 07:19 UTC, msbrogli requested changes
I reviewed all files except the tests.

2021-02-26 07:19 UTC, msbrogli commented on .env.production
> +MAX_ADDRESS_GAP=10
Why are you changing it?

2021-02-26 07:19 UTC, msbrogli commented on DATABASE.md
> +CREATE TABLE `version_data` (
Arght! I understand that it will run in a lambda and so we need to store these pieces of information somewhere. Should we add a `last_updated_at` field to force a query to the full node once in a while? Should we `count(*)` and guarantee there's one, and only one, row in this table?

I feel we should add a comment here explaining why it exists and that there must be exactly one row in this table.

2021-02-26 07:19 UTC, msbrogli commented on src/api/errors.ts
> +  INVALID_SELECTION_ALGO = 'invalid-selection-algo',
`INVALID_SELECTION_ALGORITHM`?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +      Joi.array()
1) Shouldn't we validate the content of the array?
2) Isn't it supposed to be an array of objects?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  const eventBody = (function parseBody(body) {
Missing typing?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +      statusCode: 200,
200? Isn't better to use 4xx or 5xx?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    await closeDbConnection(mysql);
Why don't you wrap this method with another method that call `closeDbConnection(mysql)` for you? I feel it is very error prone to do it before each return.

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    await closeDbConnection(mysql);
Same here.

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    if (!body.inputSelectionAlgo) return InputSelectionAlgo.USE_LARGER_UTXOS;
Wrong format.

```
if (...) {
  [code]
}
```

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  // TODO get limit from the full-node (https://github.com/HathorNetwork/hathor-wallet-service/issues/12)
TODO! Or we can have some constants in this project.

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    if (typeof parsed.address !== 'string' || typeof parsed.value !== 'number'
`parsed.value` must also be integer. Maybe use `Number.isInteger(parsed.value)`?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    if (typeof parsed.txId !== 'string' || typeof parsed.index !== 'number') {
`parsed.index` must be an interger. Maybe use `Number.isInteger(parsed.index)`?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +      // TODO not handling authority outputs
TODO

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +        // this treats an unlikely case, where we have more change outputs than addresses. In this case,
That's an interesting design decision. We should create an issue to discuss it further. For now, we can keep the current behavior.

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  const valueUtxos = await getWalletSortedValueUtxos(_mysql, walletId, tokenId);
Do we need to load all of them from database? Some wallets might have hundreds of thousands utxos.

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalSend.ts
> +  const txHex = hathorLib.transaction.getTxHexFromData(txData);
Shouldn't we verify the PoW before moving forward?

2021-02-26 07:19 UTC, msbrogli commented on src/api/txProposalSend.ts
> +    await updateTxProposal(
We need to rollback the transaction here, right?

2021-02-26 07:19 UTC, msbrogli commented on src/utils.ts
> +  && (received < (calculated * ACCEPTABLE_WEIGHT_RANGE))
Why do we have a superior limit? If the nonce matches, I feel we should accept it.

2021-02-26 07:19 UTC, msbrogli commented on src/commons.ts
> +    hathorLib.transaction.updateTransactionWeightConstants(
Shouldn't we do it every call, even when fetching data from the full node?

2021-02-26 07:19 UTC, msbrogli commented on src/api/wallet.ts
> +    // TODO handle
TODO

2021-02-26 07:19 UTC, msbrogli commented on src/db.ts
> +  await mysql.query(
Should we assert there's one and only one record in this table?

2021-02-26 14:18 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `version_data` (
https://github.com/HathorNetwork/hathor-wallet-service/blob/36c82d14b84e4a8b97759fbc7efe280b5ec365a8/src/commons.ts#L221

We are already checking "expiration time" on the method above, that's why we have a `timestamp` field. Currently the expiration time (`VERSION_CHECK_MAX_DIFF`) is set to 1 hour

I agree with the comment explaining why it exists.

I just noticed that Iḿ using `version` as the primary key, this will be an issue when we change the connected fullnode or update the current fullnode to another version as it will add a second row on the database.

I will refactor this to always allow for exactly one row

2021-02-26 14:22 UTC, andreabadesso commented on src/api/errors.ts
> +  INVALID_SELECTION_ALGO = 'invalid-selection-algo',
Done in 3bbcb468296f173bc2f82cf0f5da5e36cdac934f

2021-02-26 14:24 UTC, andreabadesso commented on .env.production
> +MAX_ADDRESS_GAP=10
Can't remember why I changed it.

Changed it back to 20

2021-02-26 14:32 UTC, andreabadesso commented on src/api/txProposalSend.ts
> +    await updateTxProposal(
I agree, but I suggest leaving a comment there for now with a TODO to handle the transaction rollback because we have a task to handle transactions and rollbacks 

What do you think?

2021-02-26 14:40 UTC, andreabadesso commented on src/api/wallet.ts
> +    // TODO handle
I think we can just `console.error` for now to have the error on cloudwatch/serverless dashboard and decide how to handle wallet load failures on another PR as this has nothing to do with `tx_proposal` and was done previously to it, what do you think?

2021-02-26 14:47 UTC, andreabadesso commented on src/commons.ts
> +    hathorLib.transaction.updateTransactionWeightConstants(
`hathorLib.version.checkApiVersion` already updates the weight, calling exactly the methods I'm using on the `else` code block.

We should be safe as long as the api on hathorLib don't change.

@pedroferreira1 I suggest refactoring `checkApiVersion` method on the hathor-lib to make it do _less_, it is currently:

* requesting the fullnode for version data
* updating the lib internally with the version data
* returning it]

What do you think?

2021-02-26 14:56 UTC, pedroferreira1 commented on src/utils.ts
> +  && (received < (calculated * ACCEPTABLE_WEIGHT_RANGE))
I discussed this with @andreabadesso and the idea was to add a protection, in order to prevent a malicious user to send a tx with a higher weight and we would overload the tx-mining-service. Not sure if we could prevent this using  other strategy.

2021-02-26 15:38 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      // TODO not handling authority outputs
I will remove the TODO as this is being done in the `tx_proposal token actions`

2021-02-26 15:43 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      Joi.array()
1. We should.
2. I agree, the API is currently expecting an array of arrays on inputs and outputs. I will refactor it to expect an array of objects and validate it properly

2021-02-26 15:56 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const eventBody = (function parseBody(body) {
I feel that we should leave it without enforcing type on user input before validating it with Joi

2021-02-26 15:56 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      statusCode: 200,
I agree!! Will refactor all status codes for errors

2021-02-26 15:59 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    await closeDbConnection(mysql);
I agree, but I think this refactor can be done when we add an ORM. We already have an task for that on the Epic.

I can create an issue so we won't forget

What do you think?

2021-02-26 16:00 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    if (!body.inputSelectionAlgo) return InputSelectionAlgo.USE_LARGER_UTXOS;
Done

2021-02-26 16:03 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  // TODO get limit from the full-node (https://github.com/HathorNetwork/hathor-wallet-service/issues/12)
Done!

2021-02-26 16:10 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    if (typeof parsed.address !== 'string' || typeof parsed.value !== 'number'
I agree. Done!

2021-02-26 16:14 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    if (typeof parsed.txId !== 'string' || typeof parsed.index !== 'number') {
Done. Also did it for timelock as it should also be an integer

2021-02-26 16:25 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +        // this treats an unlikely case, where we have more change outputs than addresses. In this case,
Done: https://github.com/HathorNetwork/hathor-wallet-service/issues/25

2021-02-26 16:41 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const valueUtxos = await getWalletSortedValueUtxos(_mysql, walletId, tokenId);
I agree that we shouldn't need to load all of them in memory from the database.

We can try to do it on MySQL by refactoring this method to select utxos until their sum is higher than the necessary balance, ordering by value

I would suggest creating an issue for this optimization instead of handling it on tx-proposal. What do you think?

2021-02-26 16:46 UTC, andreabadesso commented on src/api/txProposalSend.ts
> +  const txHex = hathorLib.transaction.getTxHexFromData(txData);
I agree.

I think that this validation should be done on the wallet-lib tho and we don't have a method to do that yet. Created the issue at https://github.com/HathorNetwork/hathor-wallet-lib/issues/152

When its done, we can validate the PoW

Created the issue: https://github.com/HathorNetwork/hathor-wallet-service/issues/26

2021-03-01 15:05 UTC, pedroferreira1 requested changes

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/balances.ts
>      // TODO validate tokenId
What's this validation? Only if it's a valid hex?

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +        .min(4)
I didn't understand this min/max. What's the meaning?

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +      Joi.array()
Important to say in the issue about the content validation of the array also. This was the main problem when I was using `express-validator`, to validate the content of an optional object.

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +    const parameter = firstErrorDetails.path[0];
Why do we return only the first invalid parameter and not all of them?

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +    // check if inputs sent by user are not part of another tx proposal
Is this a `TODO`?

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  // Make sure diff is 0 or lower, which means inputs sum is grater than (or equal to) outputs sum.
Typo: greater

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  const addresses = await getUnusedAddresses(mysql, walletId);
Are we adding the `changeAddress` parameter in this API in another PR?

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  // shuffle array
Maybe we should explain here that we shuffle in order to give some more privacy to the user, given that the last output won't always be the change.

2021-03-01 15:05 UTC, pedroferreira1 commented on src/utils.ts
> +export const getHathorAddresses = (xpubkey: string, startIndex: number, quantity: number): StringMap<number> => {
The wallet lib has a method exactly like this. Check the method `getAddresses` in `src/helpers.js`.

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalDestroy.ts
> + * Send a transaction.
This comment should be another thing, right? Something related to destroy a tx proposal.

2021-03-01 15:05 UTC, pedroferreira1 commented on src/api/txProposalSend.ts
> +  nonce: Joi.number()
Can we specify with `Joi` that we want an integer for `nonce`? In order to throw error if the user sends a float?

2021-03-01 15:05 UTC, pedroferreira1 commented on truncate.sql
> +SELECT Concat('TRUNCATE TABLE ',table_schema,'.',TABLE_NAME, ';') FROM INFORMATION_SCHEMA.TABLES where  table_schema in ('hathor');
I think this file should not be commited.

2021-03-01 15:05 UTC, pedroferreira1 commented on src/db.ts
> +export const getUnusedAddresses = async (mysql: ServerlessMysql, walletId: string): Promise<string[]> => {
This method is being used to create a change output but it might not be the best. The ideal scenario would be to have the change addresses coming from a different path, however this would require a bigger refactor. The problem with this is that we expect the change address to be an address that was never shared with the user but an address with 0 transactions doesn't mean that was never shared with the user.

2021-03-01 17:33 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      statusCode: 200,
Created a new PR for this refactor:

https://github.com/HathorNetwork/hathor-wallet-service/pull/27

2021-03-01 17:34 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    await closeDbConnection(mysql);
@msbrogli 

Refactored this on the status code PR:
https://github.com/HathorNetwork/hathor-wallet-service/pull/27

2021-03-01 17:34 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    await closeDbConnection(mysql);
Refactored this on the status code PR:

https://github.com/HathorNetwork/hathor-wallet-service/pull/27

2021-03-01 17:41 UTC, andreabadesso commented on src/utils.ts
> +export const getHathorAddresses = (xpubkey: string, startIndex: number, quantity: number): StringMap<number> => {
Oops. This is a leftover from the rebase I did with `dev`, this was already refactored to use the wallet-lib's method.

2021-03-01 17:43 UTC, andreabadesso commented on src/api/txProposalDestroy.ts
> + * Send a transaction.
Fixed

2021-03-01 17:46 UTC, andreabadesso commented on src/api/txProposalSend.ts
> +  nonce: Joi.number()
Yes we can, done in 17318c61ed681e27e887e305152770f6daa2a635

2021-03-01 17:47 UTC, andreabadesso commented on truncate.sql
> +SELECT Concat('TRUNCATE TABLE ',table_schema,'.',TABLE_NAME, ';') FROM INFORMATION_SCHEMA.TABLES where  table_schema in ('hathor');
I agree. Done.

2021-03-01 17:48 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  // Make sure diff is 0 or lower, which means inputs sum is grater than (or equal to) outputs sum.
Done

2021-03-01 17:50 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const addresses = await getUnusedAddresses(mysql, walletId);
I suggest doing it in another PR. 

Created the issue here: https://github.com/HathorNetwork/hathor-wallet-service/issues/28

2021-03-01 18:08 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  // shuffle array
I agree. Done

2021-03-01 18:23 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +        .min(4)
We are currently expecting inputs and outputs to be an array instead of an object. This will be refactored, we've got an issue for that: https://github.com/HathorNetwork/hathor-wallet-service/issues/23

2021-03-02 14:35 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    // check if inputs sent by user are not part of another tx proposal
Done in 1d50f33323168003a5bb2d969a7268693a6f8ac4

2021-03-03 14:51 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      Joi.array()
Done in PR https://github.com/HathorNetwork/hathor-wallet-service/pull/29

2021-03-03 14:53 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +        .min(4)
Done in PR https://github.com/HathorNetwork/hathor-wallet-service/pull/29

2021-03-03 14:53 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    const parameter = firstErrorDetails.path[0];
Done in commit 594a2f4d3a1975d1736f40352e355307f9b8ab30

2021-03-03 17:57 UTC, andreabadesso commented on src/api/balances.ts
>      // TODO validate tokenId
Done in PR: https://github.com/HathorNetwork/hathor-wallet-service/pull/30

2021-03-04 16:06 UTC, pedroferreira1 commented on src/db.ts
> +export const getUnusedAddresses = async (mysql: ServerlessMysql, walletId: string): Promise<string[]> => {
An issue was created to handle this later: https://github.com/HathorNetwork/hathor-wallet-service/issues/31

2021-03-04 16:06 UTC, pedroferreira1 approved these changes

2021-03-04 19:06 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `version_data` (
Done in 1fb1fd22fb67107d6dd36bbc6606cc6d6a7a1434

2021-03-04 19:07 UTC, andreabadesso commented on src/db.ts
> +  await mysql.query(
Done in 1fb1fd22fb67107d6dd36bbc6606cc6d6a7a1434

2021-03-04 20:07 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  const eventBody = (function parseBody(body) {
I agree. Thanks!

2021-03-04 20:08 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  const valueUtxos = await getWalletSortedValueUtxos(_mysql, walletId, tokenId);
I agree. Let's do it separately. We can get the db cursor and iterate over it. This way we can control what keeps in memory and what will be collected by the garbage collector.

2021-03-04 20:09 UTC, msbrogli commented on src/api/txProposalSend.ts
> +  const txHex = hathorLib.transaction.getTxHexFromData(txData);
Great! Thanks!

2021-03-04 20:09 UTC, msbrogli commented on src/api/txProposalSend.ts
> +    await updateTxProposal(
I agree. Thanks!

2021-03-04 20:10 UTC, msbrogli commented on src/utils.ts
> +  && (received < (calculated * ACCEPTABLE_WEIGHT_RANGE))
But I feel this protection must be in the tx-mining-service. The wallet is not affected by it at all.

2021-03-04 20:11 UTC, msbrogli commented on src/commons.ts
> +    hathorLib.transaction.updateTransactionWeightConstants(
@andreabadesso Seems like a good suggestion. But, for now, I feel you can leave a note and move forward. And also double check that we have a test that will fail if the hathorLib changes in the future.

2021-03-04 20:12 UTC, msbrogli commented on src/api/wallet.ts
> +    // TODO handle
I agree with your suggestion. But I think we should have an issue to keep track of it.

2021-03-04 20:13 UTC, msbrogli commented on DATABASE.md
> +CREATE TABLE `version_data` (
Great! Thanks!

2021-03-04 20:13 UTC, msbrogli approved these changes

2021-03-04 21:23 UTC, pedroferreira1 approved these changes

2021-03-04 21:42 UTC, merged

2021-03-04 22:34 UTC, andreabadesso commented on src/api/wallet.ts
> +    // TODO handle
Done https://github.com/HathorNetwork/hathor-wallet-service/issues/32

2021-03-04 22:39 UTC, andreabadesso commented on src/utils.ts
> +  && (received < (calculated * ACCEPTABLE_WEIGHT_RANGE))
I created an issue so we can disucss this further: https://github.com/HathorNetwork/hathor-wallet-service/issues/33

2021-03-04 22:53 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const valueUtxos = await getWalletSortedValueUtxos(_mysql, walletId, tokenId);
I agree. Added the issue at https://github.com/HathorNetwork/hathor-wallet-service/issues/34