feat: better monitoring and checking guards
HathorNetwork/hathor-wallet-service-old pull request #220
Opened 2022-05-10 17:22 UTC by andreabadesso

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-05-10 18:54 UTC, andreabadesso commented on serverless.yml
> +  logLevel: ${self:custom.logLevelMap.${opt:stage}, 'debug'}
Any stage other than `mainnet`, `testnet` or `dev` will default to `debug`

2022-05-10 18:54 UTC, andreabadesso commented on serverless.yml
> +    LOG_LEVEL: ${self:custom.logLevel}
We can also change it manually on the serverless AWS page if we want to change it during execution

2022-05-10 19:56 UTC, andreabadesso commented on src/commons.ts
> +  logger.debug(`Setting WalletTxHistory as voided from ${txs.length} transactions.`);
We are already logging transactions on the log above this one

2022-05-11 13:05 UTC, pedroferreira1 reviewed
I just didn't understand why the log parameters were added as a first (or second) parameter in the methods. Why don't we just add as the last parameter in all of them?

2022-05-11 13:05 UTC, pedroferreira1 commented on src/txProcessor.ts
> +
Should we log the full tx data here?

2022-05-11 13:05 UTC, pedroferreira1 commented on src/txProcessor.ts
> +    logger.debug(`Block transaction, unlocking ${utxos.length} locked utxos at height ${tx.height}`);
I'm think about logging all utxos being unlocked here. Not sure if it's worth it

2022-05-11 13:05 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  logger.debug(`Adding ${txId} to database`, tx);
This is the log I requested in the beginning of the method. I know here is just when it's really added but the tx data could be logged in the beginning and here we just log "Adding txID to database" What do you think?

2022-05-11 16:55 UTC, andreabadesso commented on src/txProcessor.ts
> +
On this line we are adding the `txId` to every log message that will be logged next, so we can filter by it

Added a new log to log the full tx on 9e75e9d8951937e8c5344bd7dd40a5d988885035

2022-05-11 16:56 UTC, andreabadesso commented on src/txProcessor.ts
> +    logger.debug(`Block transaction, unlocking ${utxos.length} locked utxos at height ${tx.height}`);
I agree, done in b57b87301e570e3597ddd9ace24b36a97818a26f

2022-05-11 16:57 UTC, andreabadesso commented on src/txProcessor.ts
> +  logger.debug(`Adding ${txId} to database`, tx);
I agree, removed the fulltx log here and added it on top of the txProcessor method in b57b87301e570e3597ddd9ace24b36a97818a26f

2022-05-12 05:09 UTC, msbrogli requested changes

2022-05-12 05:09 UTC, msbrogli commented on src/txProcessor.ts
> +  const logger = createDefaultLogger();
Can't we instantiate `logger` in a separate file and import as a global variable in each file? Here is an example: https://github.com/HathorNetwork/hathor-wallet-headless/blob/master/src/logger.js

I feel it is better than passing it all along method calls.

2022-05-12 05:09 UTC, msbrogli commented on serverless.yml
> +    LOG_LEVEL: ${self:custom.logLevel}
Do we have it explained in the SOP? Do we have to restart the already started lambdas execution environments?

2022-05-12 05:09 UTC, msbrogli commented on tests/integration.test.ts
> +  await addToUtxoTable(mysql, tx2Inputs);
What change affected these tests? I feel you basically improved logging and added some integrity checks. I couldn't find any fix or new feature.

2022-05-12 12:48 UTC, pedroferreira1 approved these changes

2022-05-12 14:36 UTC, andreabadesso commented on src/txProcessor.ts
> +  const logger = createDefaultLogger();
We could, but if we do that, we would either lose the `requestId` (that is added on the handlers) or risk having wrong `requestIds` on the requests (as multiple parallel calls would mutate the global logger object)

That's what I'm doing with this line:

```javascript
  logger.defaultMeta = {
    requestId: context.awsRequestId,
  };
```

2022-05-12 14:41 UTC, andreabadesso commented on tests/integration.test.ts
> +  await addToUtxoTable(mysql, tx2Inputs);
The integrity checks broke those tests because `txEvent2` spends `utxos` that are not on our database, I just added them to the database

2022-05-12 17:15 UTC, andreabadesso commented
> Do we have it explained in the SOP? Do we have to restart the already started lambdas execution environments?

@msbrogli 

Added a SOP line explaining how to change the log level 262ad8f7111b1614476ff63ecee398e679d685ac

2022-05-12 18:02 UTC, msbrogli commented on tests/integration.test.ts
> +  await addToUtxoTable(mysql, tx2Inputs);
Got it. Thanks!

2022-05-12 18:03 UTC, msbrogli commented on serverless.yml
> +    LOG_LEVEL: ${self:custom.logLevel}
I just saw your message saying that you added it to the SOP. Thanks!

2022-05-13 18:39 UTC, msbrogli approved these changes

2022-05-13 18:39 UTC, merged