Add weight to transaction table and update sync algorithm accordingly
HathorNetwork/hathor-wallet-service-old pull request #226
Opened 2022-05-18 15:25 UTC by lucas3003

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-05-19 14:39 UTC, pedroferreira1 requested changes

2022-05-19 14:39 UTC, pedroferreira1 commented on db/models/transaction.js
> +      allowNull: true,
I think we can comment here that we support `null` only for data migration, because the data already there won't have the `weight` and we will need to manually input it there.

It's important to describe this here in case someone wants to do anything with `weight`, it's safe to assume that will be there the value.

2022-05-19 14:39 UTC, pedroferreira1 commented on src/db/index.ts
> +  weight: number,
Missing new parameter in the docstring

2022-05-19 14:39 UTC, pedroferreira1 commented on src/db/index.ts
> +  weight: number,
Missing new parameter in the docstring

2022-05-19 14:39 UTC, pedroferreira1 commented on db/models/transaction.js
> +      type: DataTypes.INTEGER.UNSIGNED,
`weight` is not an integer, it's a float in our full node.

2022-05-19 14:39 UTC, pedroferreira1 commented on src/db/index.ts
> +         ON DUPLICATE KEY UPDATE height = ?, weight = ?`,
Why do we need the `weight` in the `ON DUPLICATE KEY UPDATE`? I thought this was useful only for transactions that could get their height after a block confirmation.

2022-05-19 14:39 UTC, pedroferreira1 commented on src/db/index.ts
> +      weight: result.weight as number,
I feel we could create a method to get `Tx` object from a db result. With that, if we decide to add a new column in this table in the future we won't need to add this new column in all places like you did with `weight`. What do you think?

2022-05-20 01:42 UTC, lucas3003 commented on db/models/transaction.js
> +      allowNull: true,
Done.

2022-05-20 01:42 UTC, lucas3003 commented on src/db/index.ts
> +  weight: number,
Added.

2022-05-20 01:42 UTC, lucas3003 commented on src/db/index.ts
> +  weight: number,
Added

2022-05-20 17:37 UTC, andreabadesso approved these changes

2022-05-23 02:07 UTC, pedroferreira1 approved these changes

2022-05-24 19:35 UTC, merged