Feat/auto review nfts
HathorNetwork/hathor-wallet-service-old pull request #235
Opened 2022-06-18 19:56 UTC by tuliomir

> :construction: PR still in draft

Code is still untested. PR open to ease communication about it.
Pending to know if the Explorer Service will actually have a `[PUT]` route to update token metadata
This code depends on HathorNetwork/hathor-wallet-lib#378

### Acceptance Criteria
- TxProcessor identifies NFT Creation transactions
- TxProcessor updates NFT metadata whenever it identifies a new NFT on the network

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-07-14 14:28 UTC, tuliomir commented on src/txProcessor.ts
> + * @deprecated
This is not related to the scope of this PR, but was relevant to the design process.

2022-07-15 13:59 UTC, andreabadesso commented on events/nftCreationTx.ts
> +const cloneObj = (obj) => JSON.parse(JSON.stringify(obj));
We have lodash on the project, you can use https://lodash.com/docs/#clone

2022-07-15 17:16 UTC, tuliomir commented on events/nftCreationTx.ts
> +const cloneObj = (obj) => JSON.parse(JSON.stringify(obj));
Done on [a47b736](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/a47b736ba32a1183d05ac9ca9c6a3408b69504f3).

2022-07-21 17:00 UTC, tuliomir commented on src/utils.ts
> +import { BinaryToTextEncoding, createHash } from 'crypto';
Related to dependencies update:
`HexBase64Latin1Encoding` was removed on the latest version of `@types/node`.
Changed it to match the current `hash.digest()` contract.

2022-07-27 21:04 UTC, r4mmer requested changes

2022-07-27 21:04 UTC, r4mmer commented on src/txProcessor.ts
> + * @deprecated
But is it still deployed? Or is this lambda removed?

2022-07-27 21:04 UTC, r4mmer commented on src/txProcessor.ts
> +        .catch((err) => logger.error('Errored on nftHandlerLambda invocation', err));
Why not let the outer catch handle this error?

2022-07-27 21:04 UTC, r4mmer commented on src/txProcessor.ts
> +}
These should be on `src/types.ts`.
Also, since this is a very specific handler I think we can make a handler type like in this [example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/handler.d.ts#L12)

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +        : 'https://lambda.eu-central-1.amazonaws.com',
Isn't there a dev stage on aws? Should we use `process.env.ENVIRONMENT` here?

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +      FunctionName: `hathor-explorer-service-${NftUtils.getExplorerServiceStage(process.env.STAGE)}-create_or_update_dag_metadata`,
Instead of this I think we should have the whole function name as a configuration. This would also eliminate the need for a `getExplorerServiceStage` method.

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +      ++retryCount;
We should log each failed attempt, this would make debugging easier if any errors are happening on this invocation.

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +    throw new Error('Metadata update failed.');
Should we log something here to raise an alert?
If we intend to raise an alert from this, we should add more metadata to make the investigation simpler.
I think just the `tx_id` is enough actually.

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +      FunctionName: `${process.env.SERVICE_NAME}-${process.env.STAGE}-onNewNftEvent`,
Same here.

2022-07-27 21:04 UTC, r4mmer commented on src/utils/nft.utils.ts
> +        : `https://lambda.${process.env.AWS_REGION}.amazonaws.com`,
Same here

2022-07-28 11:54 UTC, tuliomir commented on src/txProcessor.ts
> + * @deprecated
This is still deployed, I only added this line to help developers and static code analyzers identify that this should not be used anymore.
The lambda itself will be removed in another PR.

2022-07-28 11:58 UTC, tuliomir commented on src/txProcessor.ts
> +        .catch((err) => logger.error('Errored on nftHandlerLambda invocation', err));
Because we want the `onNewTxRequest` lambda to return with success as soon as possible. Note that `invokeNftHandlerLambda()` returns a function and we are not using `await` to wait for its response here.

If this feels weird, maybe we can take away the whole `try / catch` block and make it inside the `isTransactionNFTCreation()`, so that it's clearer which errors are catched where.

2022-07-28 12:19 UTC, tuliomir commented on src/txProcessor.ts
> +}
Moved these types to inline on [a35b1310](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/a35b13103bfea43d7c41196b358d21e4519f5c8b).

2022-07-28 12:26 UTC, tuliomir commented on src/utils/nft.utils.ts
> +      ++retryCount;
Added the `retryCount` to the logger warning on [a325e540](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/a325e5408d26300c0199082439f11f223083d7ed). Do you think another information would be useful to have here?

2022-07-28 12:51 UTC, tuliomir commented on src/utils/nft.utils.ts
> +    throw new Error('Metadata update failed.');
Good point. I assumed the logs on _retry_ instances would be enough, but it's always good to have this information at hand on every log.
Added the `tx_id` to the error message on [6380e15f](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/6380e15fda86d877153bd92744e97e2872875fff).

2022-07-28 13:26 UTC, andreabadesso requested changes

2022-07-28 13:26 UTC, andreabadesso commented on serverless.yml
> +  serverlessIfElse:
I think you could use [`Fn::Split`](https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html) to avoid adding a new library, I'm not sure about the correct syntax, but my guess is that it would look something like:

```
Fn::Select:
  - 0
  - Fn::Split
    - '-'
    - ${opt:stage, 'dev'}
```

Wouldn't waste too much time on this though, as the library is just a dev dependency

2022-07-28 13:26 UTC, andreabadesso commented on serverless.yml
> +          arn:aws:lambda:eu-central-1:769498303037:function:hathor-wallet-service-${self:custom.stage}-onNewNftEvent
Can't we use something like what was described [here](https://stackoverflow.com/a/61992891)?

2022-07-28 13:26 UTC, andreabadesso commented on serverless.yml
> +    role: arn:aws:iam::769498303037:role/WalletServiceLoadWalletLambda # TODO: Use local iamRoleStatements instead of this rule
TODO

2022-07-28 13:26 UTC, andreabadesso commented on src/utils/nft.utils.ts
> +    if (walletStage === 'dev-testnet') {
Can't we add an environment variable in `serverless.yml`, using `custom.explorerServiceStage` and use it here?

2022-07-28 13:26 UTC, andreabadesso commented on src/utils/nft.utils.ts
> +    const libTx: hathorLib.CreateTokenTransaction = hathorLib.helpersUtils.createTxFromHistoryObject(tx);
Shouldn't we move this inside the try/catch?

2022-07-28 13:26 UTC, andreabadesso commented on src/utils/nft.utils.ts
> +      FunctionName: `hathor-explorer-service-${NftUtils.getExplorerServiceStage(process.env.STAGE)}-create_or_update_dag_metadata`,
Another option would be to set the `explorerServiceStage` as an env variable, using `custom.explorerServiceStage` on `serverless.yml`

2022-07-28 13:26 UTC, andreabadesso commented on src/utils/nft.utils.ts
> +      ++retryCount;
If we want to be notified about this failure, add `[ALERT]` to the log string so alert-manager gets it

2022-07-28 13:26 UTC, andreabadesso commented on src/utils/nft.utils.ts
> +    throw new Error('Metadata update failed.');
@tuliomir Also add `[ALERT]` to the error string, so alert-manager will get it

2022-07-28 13:54 UTC, tuliomir commented on src/utils/nft.utils.ts
> +      FunctionName: `hathor-explorer-service-${NftUtils.getExplorerServiceStage(process.env.STAGE)}-create_or_update_dag_metadata`,
On [56f859db](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/56f859db652843dc2974e61e5f9bfa54b7873a24) I added two new environment variables, one for the `wallet-service` endpoint itself and another for the `explorer-service` endpoint.

The function name itself I kept as a code string, because I think it shouldn't be so easy to change it.
Can you check if this is a valid suggestion?

2022-07-28 14:22 UTC, tuliomir commented on src/utils/nft.utils.ts
> +    const libTx: hathorLib.CreateTokenTransaction = hathorLib.helpersUtils.createTxFromHistoryObject(tx);
I refactored this method on [f88dc663](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/f88dc6630a292a953aaffb5a065c8b65c3becf10) to catch errors on this function, and also to make the `txProcessor` code simpler.

2022-07-28 14:45 UTC, tuliomir commented on serverless.yml
> +    role: arn:aws:iam::769498303037:role/WalletServiceLoadWalletLambda # TODO: Use local iamRoleStatements instead of this rule
Removed the comment and created issue #257 to track this `todo`

2022-07-28 14:46 UTC, tuliomir commented on src/utils/nft.utils.ts
> +    if (walletStage === 'dev-testnet') {
Good idea! Done on [56f859db](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/56f859db652843dc2974e61e5f9bfa54b7873a24).

2022-07-28 15:03 UTC, tuliomir commented on serverless.yml
> +          arn:aws:lambda:eu-central-1:769498303037:function:hathor-wallet-service-${self:custom.stage}-onNewNftEvent
Improved on [aefd31f0](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/aefd31f0d1755845de720487b71d59263b298593).

2022-07-28 15:05 UTC, tuliomir commented on src/utils/nft.utils.ts
> +        : 'https://lambda.eu-central-1.amazonaws.com',
I made some changes on [56f859db](https://github.com/HathorNetwork/hathor-wallet-service/pull/235/commits/56f859db652843dc2974e61e5f9bfa54b7873a24) that involve this code being moved to environment variables.

2022-07-28 17:00 UTC, r4mmer approved these changes

2022-07-28 17:19 UTC, andreabadesso approved these changes

2022-07-28 17:44 UTC, merged

2022-07-28 19:51 UTC, tuliomir commented on serverless.yml
> +  serverlessIfElse:
It is a good idea, but it's not compatible with the structure we've made at the moment: the `explorerServiceStage` that we need to calculate is used on the environment variables and, more importantly, on a text interpolation on `functions.onNewNftEvent.iamRoleStatements.Resource`.

Since the evaluation of the `Fn::Select` and `Fn::Split` only occur at the CloudFormation stage, it seems to not work very well with the `serverless-offline`, nor it passes the validations on `npx serverless print`.

So we may do this on another PR/issue later, but will keep with what's been already tested and worked well so far for this PR.