refactor: storing and using highest address index on the wallet table
HathorNetwork/hathor-wallet-service-old pull request #244
Opened 2022-07-21 01:15 UTC by andreabadesso

### Acceptance Criteria
- We should store the highest used address index on the wallet table every time we generate new addresses
- We should use the highest used address on the `getNewAddresses` query to prevent a query on the big address table

### Security Checklist
- [x] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-07-22 17:30 UTC, luislhl commented on src/db/index.ts
> +        SET \`last_used_address_index\` = ?
The terms `last used` and `highest used` don't necessarily mean the same thing, although in this context they do.

But wouldn't it be better to stick to one of them both in the DB field and in the JS variable?

2022-07-22 17:31 UTC, luislhl approved these changes

2022-07-22 17:37 UTC, tuliomir requested changes
I think just the tests on the new field would be important.

2022-07-22 17:37 UTC, tuliomir commented on src/db/index.ts
> +    highestUsedIndex,
I think it would be good to add an assertion that this new value is being returned with the correct value on each of the calls on the `tests/db.test.ts:130` suite.

2022-07-22 17:37 UTC, tuliomir commented on tests/utils.ts
> +  entries: WalletTableEntry[],
Nice improvement! :+1:

2022-07-25 12:24 UTC, andreabadesso commented on src/db/index.ts
> +    highestUsedIndex,
That's a great idea, done in c981d1fed7515e8eafb3af6333008d8eee1f1085


Thanks

2022-07-25 12:24 UTC, andreabadesso commented on src/db/index.ts
> +        SET \`last_used_address_index\` = ?
I agree, done in 775a69f0c0c858ac4321c79a069e09074ee10f0c

2022-07-25 12:26 UTC, luislhl approved these changes

2022-07-25 12:30 UTC, tuliomir approved these changes

2022-07-25 12:31 UTC, merged