feat: creating fullnode messages integration to wallet service
HathorNetwork/hathor-wallet-service-old pull request #3
Opened 2020-06-30 04:09 UTC by pedroferreira1

2020-06-30 10:57 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +AWS.config.update({ region: 'us-east-1' });
We should get this from config. Also, I don't think the comment applies here. We are actually making calls to AWS.

2020-06-30 10:57 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +  onOpen(): void {
We might want to make this method (and similar ones) private.

2020-06-30 10:57 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +      break;
`break` should be indented?

2020-06-30 10:57 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +class WalletService extends EventEmitter {
Do we need it to emit events? I'm more curious, as I don't think there are no downsides in doing it.

2020-06-30 10:57 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +enum WalletServiceState {
We need to debate this name. I think it's not the wallet service state, but the full node connection state, even though they're related.

2020-07-01 01:59 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +class WalletService extends EventEmitter {
I also don't see any downsides. Currently I am emitting the events every time my state changes, e.g. the full node becomes offline, so the connection will be closed.

It's not 100% clear to me from the design exactly how you are gonna use this service but I guess it's important to listen to those events and know when the data is not being updated in real time.

2020-07-01 02:00 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +enum WalletServiceState {
Yeah, I agree. I used my class name as `WalletService`, that's why I used this name (in that context makes sense). But it's not a good name.

Maybe `WalletServiceMessages` and `WalletServiceMessagesState`?

2020-07-01 02:01 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +      break;
No, I fixed it. Probably was some probably when indenting typescript. Weird that everything was still working fine. Fixed it, thanks

2020-07-01 02:01 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +AWS.config.update({ region: 'us-east-1' });
Yeah, makes sense. Changed it.

2020-07-01 02:10 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +  onOpen(): void {
That's correct, I've set all methods as private, except `start`. Should we also let `sendMessage` public? (I don't think so).

2020-07-01 17:18 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +class WalletService extends EventEmitter {
> It's not 100% clear to me from the design exactly how you are gonna use this service but I guess it's important to listen to those events and know when the data is not being updated in real time.

To be honest, I don't see the wallet-service monitoring this service. I'd guess it's the other way around. When it disconnects, it'll probably have to notify the wallet-service (or only notify when there's a reconnect). There's no way the wallet-service can listen to these emitted events, only the ones put in an SQS queue.

2020-07-01 17:19 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +enum WalletServiceState {
I think this is very specific to the full node connection, so I'd name `FullNodeConnection` or something like that.

2020-07-02 08:00 UTC, msbrogli requested changes

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/README.md
> +- Run `npm start`.
Can't we just compile ts files to js on the `start` command?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/README.md
> +# Run
Is there a dev mode that automatically reloads if the source is changed?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/config.ts.template
> +export const SERVER = '';
Maybe add an example? wss://node1.mainnet.hathor.network/?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +type wsDataType = { [_: string]: any};
Missing a space before `}`?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +enum WalletServiceState {
I agree with @obiyankenobi. Maybe `HathorWebsocketToSQS`?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +  latestPingDate: Date | null = null;
I'd use a bool `waitingPongReply` instead of setting `latestPingDate` as null between pings. What do you think?

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +      if (err) console.log(err, err.stack); // an error occurred
Maybe we should put the data in an internal queue and retry in case of error. If the queue is full, we can raise an unrecoverable error (or start syncing again after the SQS is back).

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +const walletService: WalletService = new WalletService();
I think we should leave just this part in the index.ts and move the class to another file.

2020-07-02 08:00 UTC, msbrogli commented on fullnode-messages/src/index.ts
> +  start(): void {
You haven't included the `stop()` method.

2020-07-02 09:42 UTC, obiyankenobi commented on fullnode-messages/src/index.ts
> +  onOpen(): void {
I agree, `sendMessage` should not be public.

2020-07-02 18:16 UTC, jansegre commented on fullnode-messages/README.md
> +- Run `npm start`.
We can ship the files (on source packaging, docker images, etc) and not have to compile them at all. Which is great because it makes `npm start` not depend on dev dependencies.

Otherwise for development I'd rather use a watch command that auto-recompiles and reloads when needed.

2020-07-02 18:21 UTC, jansegre commented on fullnode-messages/src/config.ts.template
> +export const SERVER = '';
I actually don't really like the `config.ts.template`/`config.js.template` approach. It's certainly useful, but we can't make configurable and functional docker images. For HathorDice I went with a `process.env` only approach (which could definitely be improved, by using a `config` module to organize all available options), but I think it's far easier to auto-build and have deployable and configurable images.

2020-07-03 00:47 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +class WalletService extends EventEmitter {
Yeah, the wallet service probably won't use it.

As we said before, adding those events has no harm for performance or the code, so I will just keep it in case we decide to use later.

2020-07-03 01:07 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +enum WalletServiceState {
I think I will go with `FullNodeConnection`. What do you think @msbrogli? I think `ToSQS` is really specific.

2020-07-03 01:10 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +const walletService: WalletService = new WalletService();
Separated in two different files.

2020-07-03 01:10 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +  start(): void {
Done, can you see if it's good?

2020-07-03 01:29 UTC, pedroferreira1 commented on fullnode-messages/src/index.ts
> +  latestPingDate: Date | null = null;
Yes, it's better I agree. Updated it.

2020-07-03 01:32 UTC, pedroferreira1 commented on fullnode-messages/README.md
> +- Run `npm start`.
Yeah, I agree we shouldn't pack ts files, only js so `npm start` does not depend on dev dependencies. I will add the `watch` command also as @jansegre said in the other comment.

2021-06-01 19:21 UTC, andreabadesso commented
Closing this as this was replaced by the [sync daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/)

2021-06-01 19:21 UTC, andreabadesso commented
Closing this as this was replaced by the [sync daemon](https://github.com/HathorNetwork/hathor-wallet-service-sync_daemon/)

2021-06-01 19:21 UTC, closed without merging