feat: added params validation to missing routes
HathorNetwork/hathor-wallet-service-old pull request #30
Opened 2021-03-03 17:54 UTC by andreabadesso

…h joi

2021-03-03 18:38 UTC, pedroferreira1 requested changes

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/balances.ts
> +    .required()
Why is it required and optional?

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/txhistory.ts
> +    .required()
It shouldn't be required, right?

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/balances.ts
> +    .optional(),
Should we have the default as HTR? Or the API returns all token balances if no token_id is used?

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/txhistory.ts
> +  skip: Joi.number()
Should we add here `min(0)`?

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/txhistory.ts
> +    .optional(),
Maybe add `.positive()` and `max(MAX_COUNT)`

2021-03-03 18:38 UTC, pedroferreira1 commented on src/api/wallet.ts
> +    convert: true, // Skip and count will come as query params as strings
I think this comment is not from here, right?

2021-03-03 18:54 UTC, andreabadesso commented on src/api/balances.ts
> +    .required()
Done

2021-03-03 18:54 UTC, andreabadesso commented on src/api/txhistory.ts
> +    .required()
Typo. Fixed

2021-03-03 18:55 UTC, andreabadesso commented on src/api/txhistory.ts
> +  skip: Joi.number()
I agree. Done

2021-03-03 18:56 UTC, andreabadesso commented on src/api/txhistory.ts
> +    .optional(),
I agree. Done

2021-03-03 18:57 UTC, andreabadesso commented on src/api/wallet.ts
> +    convert: true, // Skip and count will come as query params as strings
Typo. Fixed

2021-03-03 19:12 UTC, msbrogli approved these changes

2021-03-03 19:12 UTC, msbrogli commented on src/api/balances.ts
> +    .optional(),
Maybe we should add a parameter for that (e.g. `all_tokens`).

2021-03-03 19:12 UTC, msbrogli commented on src/api/txhistory.ts
> +  const { value, error } = paramsSchema.validate(params, {
This code repeats itself many times. Should we move the options to a constant?

2021-03-03 20:38 UTC, andreabadesso commented on src/api/balances.ts
> +    .optional(),
By default we return all balances from all tokens if token_id is not passed

I like `token_id` being a filter and suggest keeping all tokens as a default

2021-03-03 20:43 UTC, pedroferreira1 commented on src/api/balances.ts
> +    .optional(),
I agree to keep returning all tokens by default and only filter when `token_uid` is passed.

2021-03-03 20:43 UTC, pedroferreira1 approved these changes

2021-03-03 22:21 UTC, andreabadesso commented on src/api/txhistory.ts
> +  const { value, error } = paramsSchema.validate(params, {
The options are not always the same, I want `convert` to be false when the params are coming from the query string

2021-03-04 16:29 UTC, msbrogli commented on src/api/txhistory.ts
> +  const { value, error } = paramsSchema.validate(params, {
Ok. I haven't noticed that.

2021-03-04 16:30 UTC, msbrogli commented on src/api/balances.ts
> +    .optional(),
Ok. Just add a note that we expect the number of tokens in a wallet to be small.

2021-03-04 16:30 UTC, msbrogli approved these changes

2021-03-04 16:41 UTC, andreabadesso commented on src/api/balances.ts
> +    .optional(),
Done in 9834750f23bf9a75db15d8b0a5d0ab2ce4e6df52

2021-03-04 16:41 UTC, merged