feat: create push/register lambda
HathorNetwork/hathor-wallet-service-old pull request #301
Opened 2022-11-10 02:20 UTC by alexruzenhack

- feat: create PushDevices model and its migration
- refactor: remove default value for push_provider
- chore: remove unused param and fix lint claims
- docs: add push_devices table DDL to DATABASE.md
- docs: remove provider default
- feat: add registerPushDevice persistence
- feat: add register handler for pushRegister function

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-11-14 19:23 UTC, tuliomir requested changes

2022-11-14 19:23 UTC, tuliomir commented on src/api/pushRegister.ts
> +  const body: PushRegister = value;
I wish there was a way to insert this validation within Joi, like a `bodySchema.validate<PushRegister>()`, but I couldn't find a way to do it.

It seems this is actually the best syntax for this case.

2022-11-14 19:23 UTC, tuliomir commented on src/db/index.ts
> +export const removeAllPushDeviceByDeviceId = async (mysql: ServerlessMysql, deviceId: string): Promise<void> => {
I would just suggest having the name in plural, since we will potentially affect multiple rows
```suggestion
export const removeAllPushDevicesByDeviceId = async (mysql: ServerlessMysql, deviceId: string): Promise<void> => {
```

2022-11-14 19:23 UTC, tuliomir commented on src/api/pushRegister.ts
> +import _ from 'lodash';
An unused import "`_`" is being warned by the CI

2022-11-14 19:23 UTC, tuliomir commented on tests/pushRegister.test.ts
> +    expect(returnBody.success).toStrictEqual(false);
I feel we should check the `returnBody` for the error message, to make sure the client is having adequate feedback on the failure.

2022-11-14 19:23 UTC, tuliomir commented on tests/db.test.ts
> +test('registerPushDevice', async () => {
While I like this smoke test here, I feel we should have a more extensive testing suite on the dedicated `pushRegister.test` file.

I can think of some cases would be nice to have:
- check if the values added to the database are correct when
  - there is no row to be deleted
  - there is already a row with the same deviceId and walletId, to ensure the updated values are persisted
- check that the error message of missing foreign key is being treated when trying to register for a wallet-id that is not on the `wallet` table
- ensuring that only the correct rows are affected by a delete command

2022-11-15 19:32 UTC, pedroferreira1 commented on src/types.ts
> +type iOSPushProvider = 'ios';
Maybe an `enum` would fit better here, what do you think? Something similar to

```
export enum TxProposalStatus {
  OPEN = 'open',
  SENT = 'sent',
  SEND_ERROR = 'send_error',
  CANCELLED = 'cancelled',
}
```

2022-11-15 19:32 UTC, pedroferreira1 commented on src/db/index.ts
> +/* eslint-disable camelcase */
Why do you need to add this?

2022-11-15 19:32 UTC, pedroferreira1 commented on src/db/index.ts
> +export const removeAllPushDeviceByDeviceId = async (mysql: ServerlessMysql, deviceId: string): Promise<void> => {
Why? Isn't `device_id` a primary key in the `push_devices` table?

2022-11-15 19:32 UTC, pedroferreira1 commented on src/api/pushRegister.ts
> +  enablePush: Joi.boolean().optional(),
Is the body does not have this parameter, what will we set in the db?

The method `registerPushDevice` expects a boolean here, will it have `undefined`? If yes, maybe we should have here `false` as default.

(the same applies to `enableShowAmounts`)

2022-11-15 19:32 UTC, pedroferreira1 commented on tests/utils.ts
> +  await mysql.query('SET FOREIGN_KEY_CHECKS = 0');
Why did you add this?

2022-11-16 22:48 UTC, alexruzenhack commented on src/api/pushRegister.ts
> +  enablePush: Joi.boolean().optional(),
Ok, agree. I was relying on the database default, which is false, but you are right, better protect the value from the beginning.

2022-11-16 22:48 UTC, alexruzenhack commented on src/db/index.ts
> +export const removeAllPushDeviceByDeviceId = async (mysql: ServerlessMysql, deviceId: string): Promise<void> => {
Yes, it is. I see this removeAll as a double check. In the future, if we want to enable 1:N wallet->device push notification we just remove `device_id` as the primary key.

2022-11-16 22:48 UTC, alexruzenhack commented on src/types.ts
> +type iOSPushProvider = 'ios';
Humm.. sure, it works better.

2022-11-16 22:48 UTC, alexruzenhack commented on tests/utils.ts
> +  await mysql.query('SET FOREIGN_KEY_CHECKS = 0');
Because the table `push_devices` has a relationship with `wallet`, therefore the delete does not work with active constraints, then I need to deactivate it before deleting and reactive it after deleting.

2022-11-16 22:48 UTC, alexruzenhack commented on src/db/index.ts
> +/* eslint-disable camelcase */
Because lint was accusing and error for camelcase rule. But it is not necessary anymore.

2022-11-16 22:48 UTC, alexruzenhack commented on tests/pushRegister.test.ts
> +    expect(returnBody.success).toStrictEqual(false);
I have added error message assert because I think the details of validation should not be asserted to avoid making the tests fragile.

2022-11-16 22:48 UTC, alexruzenhack commented on tests/db.test.ts
> +test('registerPushDevice', async () => {
I believe the update should not be tested because it is a very basic operation in the database realm.

The test to verify the right delete is good.

2022-11-16 22:48 UTC, alexruzenhack commented on tests/db.test.ts
> +test('registerPushDevice', async () => {
I implemented a wallet verification before calling the push device registration. I believe it will be cheaper than handling errors.

2022-11-17 05:02 UTC, pedroferreira1 commented on src/api/pushRegister.ts
> +  enablePush: Joi.boolean().optional(),
I saw how you implemented the default value and it's okay but if there's a way to add this to the `bodySchema` using jest (a default value to each optional parameter), I think would be better.

2022-11-17 05:08 UTC, pedroferreira1 commented on src/db/index.ts
> +  deviceId: string,
Should this be `walletId`? And this db field has index?

2022-11-17 16:46 UTC, alexruzenhack commented on src/db/index.ts
> +  deviceId: string,
It is a primary key, then it is indexed. I will fix the name.

2022-11-17 21:33 UTC, tuliomir commented on tests/pushRegister.test.ts
> +    const result = await register(event, null, null) as APIGatewayProxyResult;
I like this test suite, but could not feel confident that the results on the database are actually what we expect.

From the tests we know that passing a payload without push does not _throw_, but does it add the corrrect value to the table?

I think a simple assert like below could fix this:
```ts
await expect(checkPushDevicesTable(mysql, 1, {
    walletId: 'my-wallet',
    deviceId: 'device1',
    pushProvider: 'android',
    enablePush: false,
    enableShowAmounts: false,
  })).resolves.toBe(true);
```
What do you think about this?

2022-11-22 15:19 UTC, alexruzenhack commented on src/api/pushRegister.ts
> +  enablePush: Joi.boolean().optional(),
Hi, it is already done.

2022-11-22 16:19 UTC, tuliomir approved these changes

2022-11-22 22:33 UTC, pedroferreira1 approved these changes

2022-11-23 04:47 UTC, andreabadesso requested changes

2022-11-23 04:47 UTC, andreabadesso commented on src/db/index.ts
> +    `, [deviceId],
```suggestion
    `
    DELETE
      FROM \`push_devices\`
     WHERE device_id = ?
    `, [deviceId],
```

2022-11-23 04:47 UTC, andreabadesso commented on src/db/index.ts
> +    SELECT COUNT(1) as \`count\` FROM \`wallet\` pd WHERE id= ?`,
```suggestion
    SELECT COUNT(1) as \`count\`
      FROM \`wallet\` pd
     WHERE id= ?`,

```

2022-11-23 04:47 UTC, andreabadesso commented on tests/utils.ts
> +      AND \`enable_show_amounts\` = ?
```suggestion
    SELECT *
      FROM \`push_devices\`
     WHERE \`wallet_id\` = ?
       AND \`device_id\` = ?
       AND \`push_provider\` = ?
       AND \`enable_push\` = ?
       AND \`enable_show_amounts\` = ?
```

2022-11-24 21:45 UTC, andreabadesso commented on src/db/index.ts
> +     WHERE id= ?`,
```suggestion
     WHERE id = ?`,
```

2022-11-25 01:10 UTC, andreabadesso approved these changes

2022-11-25 02:24 UTC, merged