feat: create push/update lambda
HathorNetwork/hathor-wallet-service-old pull request #302
Opened 2022-11-11 01:37 UTC by alexruzenhack

- chore: add existsPushDevice test
- feat: implement existsPushDevice method
- chore: add updatePushDevice test
- feat: implement updatePushDevice method
- chore: add pushUpdate e2e test
- chore: add PushUpdate type
- chore: add DEVICE_NOT_FOUN api error
- feat: improve implementation of pushUdate handler

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-11-15 19:53 UTC, pedroferreira1 commented on src/api/pushUpdate.ts
> +  enablePush: Joi.boolean().optional(),
Same comment about the default value in the previous PR. If we decide to change anything there, then we must change here as well

2022-11-15 19:53 UTC, pedroferreira1 commented on src/db/index.ts
> + * @param input - Input of push device register
We don't have this parameter

2022-11-15 19:53 UTC, pedroferreira1 commented on src/db/index.ts
> + * @param deviceId - The device to verify existence
We don't have this parameter

2022-11-15 19:53 UTC, pedroferreira1 commented on src/db/index.ts
> + * @param walletId - The wallet linked to device
We don't have this parameter

2022-11-16 23:14 UTC, tuliomir requested changes

2022-11-16 23:14 UTC, tuliomir commented on tests/db.test.ts
> +test('updatePushDevice', async () => {
I would also suggest adding tests to failure cases, to improve our code security:
- Missing parameters on the inputs
- Invalid parameters
- Error handling, ensure a developer-friendly error was raised to the controller function

2022-11-16 23:14 UTC, tuliomir commented on tests/pushUpdate.test.ts
> +    expect(returnBody.success).toStrictEqual(false);
We should also assert the error message raised here, to ensure it's helpful to the client.

2022-11-16 23:14 UTC, tuliomir commented on tests/pushUpdate.test.ts
> +    expect(returnBody.success).toStrictEqual(false);
Message should also be asserted here

2022-11-16 23:14 UTC, tuliomir commented on src/api/pushUpdate.ts
> +  .use(warmupMiddleware());
The `serverless.yml` file indicates that this route will not have the `walletWarmer` enabled.
Should we actually use this middleware here?

2022-11-17 05:09 UTC, pedroferreira1 commented on src/db/index.ts
> +    WHERE device_id = ? AND wallet_id = ?`,
Do we have index for `device_id`and `wallet_id`? Should we have it?

2022-11-22 15:21 UTC, alexruzenhack commented on src/db/index.ts
> +    WHERE device_id = ? AND wallet_id = ?`,
No, we don't need a composed index for now, because the cardinality for device_id related to wallet_id is 1. If we change this relation allowing 1 to N then we can rethink a composed index. However, even for a 1-to-N relation, we need to take into consideration the cardinality involved in the average case.

2022-11-22 15:21 UTC, alexruzenhack commented on tests/db.test.ts
> +test('updatePushDevice', async () => {
> Missing parameters on the inputs

We can guarantee that all the parameters will be passed from lambda. As this method is not used in any other place nor intended for it, I believe it would be overkill.

> Invalid parameters

We already validated these parameters in the lambda. I don't see the necessity to validate our own code inputs, because I consider it to be a "safe environment".

> Error handling, ensure a developer-friendly error was raised to the controller function

I don't see an error path for this code. This is a basic database operation. I believe this kind of error should be held by a global error handler. Because there is nothing the controller can do with it.

> When there are multiple devices for the same wallet, if only the correct device is updated

Ok! Got it.

2022-11-22 16:32 UTC, tuliomir approved these changes

2022-11-22 16:32 UTC, tuliomir commented on tests/db.test.ts
> +    })).resolves.toBe(true);
I think it's good to validate also that the `device2` was not updated.

2022-11-23 02:14 UTC, alexruzenhack commented on tests/db.test.ts
> +    })).resolves.toBe(true);
Done!

2022-11-23 02:31 UTC, pedroferreira1 approved these changes

2022-11-23 04:52 UTC, andreabadesso requested changes

2022-11-23 04:52 UTC, andreabadesso commented on src/db/index.ts
> +    SELECT COUNT(1) as \`count\` FROM \`push_devices\` pd WHERE device_id = ? AND wallet_id = ?`,
```suggestion
SELECT COUNT(1) as \`count\`
  FROM \`push_devices\` pd
 WHERE device_id = ?
   AND wallet_id = ?
```

2022-11-23 04:52 UTC, andreabadesso commented on src/db/index.ts
> +    WHERE device_id = ? AND wallet_id = ?`,
```suggestion
UPDATE \`push_devices\`
   SET \`enable_push\` = ?,
       \`enable_show_amounts\` = ?
 WHERE \`device_id\` = ?
   AND \`wallet_id\` = ?
```

2022-11-23 04:52 UTC, andreabadesso commented on tests/pushUpdate.test.ts
> +    expect(returnBody.error).toStrictEqual('invalid-payload');
Import and use `ApiError.INVALID_PAYLOAD`

2022-11-23 04:52 UTC, andreabadesso commented on tests/pushUpdate.test.ts
> +    expect(returnBody.error).toStrictEqual('device-not-found');
Import and use `ApiError.DEVICE_NOT_FOUND`

2022-11-24 21:46 UTC, andreabadesso approved these changes

2022-11-25 02:17 UTC, merged