feat: create push/unregister lambda
HathorNetwork/hathor-wallet-service-old pull request #303
Opened 2022-11-11 02:57 UTC by alexruzenhack

- chore: add unregisterPushDevice db test
- feat: implement unregisterPushDevice
- chore: add pushUnregister e2e test
- feat: implement pushUnregister function
- chore: add pushUnregister as function in serverless

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-11-15 19:58 UTC, pedroferreira1 commented on src/db/index.ts
> + * @param input - Input of push device register
We don't have this parameter

2022-11-15 19:58 UTC, pedroferreira1 commented on tests/db.test.ts
> +  await unregisterPushDevice(mysql, deviceId, walletId);
Maybe add another `checkPushDevicesTable` and expect it to be `false` to validate it has unregistered the device?

2022-11-16 23:29 UTC, tuliomir commented on src/api/pushUnregister.ts
> +  .use(warmupMiddleware());
Same question about the walletWarmer that is defined on the `serverless.yml` as disabled, but added here to the handler.
Should we have this?

2022-11-16 23:29 UTC, tuliomir commented on tests/db.test.ts
> +test('unregisterPushDevice', async () => {
I feel we should also have tests for:
- the behavior when there is no device to unregister
- assert that, when multiple devices are registered for the same wallet, only the correct device is removed

2022-11-16 23:29 UTC, tuliomir commented on tests/pushUnregister.test.ts
> +test('update push device given a wallet', async () => {
```suggestion
test('unregister push device for a given wallet', async () => {
```

2022-11-16 23:29 UTC, tuliomir commented on tests/pushUnregister.test.ts
> +  const result = await unregister(event, null, null) as APIGatewayProxyResult;
While not necessary, I feel we should have a test that tries to delete a device that was never registered, to ensure its result will be a success.

2022-11-22 16:43 UTC, tuliomir approved these changes

2022-11-23 02:33 UTC, pedroferreira1 commented on src/api/pushUnregister.ts
> +    return { value: { enablePush: false, enableShowAmounts: false, ...value }, error };
What are those `enablePush: false, enableShowAmounts: false` values? Do we use them here?

2022-11-23 04:55 UTC, andreabadesso requested changes

2022-11-23 04:55 UTC, andreabadesso commented on src/api/pushUnregister.ts
> +    return { value: { enablePush: false, enableShowAmounts: false, ...value }, error };
Apparently, they are default values

@alexruzenhack You can use `Joi` to set default values, like `.default(true)`

2022-11-23 04:55 UTC, andreabadesso commented on src/db/index.ts
> +    WHERE device_id = ? AND wallet_id = ?`,
```suggestion
    DELETE
      FROM \`push_devices\`
     WHERE \`device_id\` = ?
       AND \`wallet_id\` = ?`,
```

2022-11-23 18:03 UTC, pedroferreira1 approved these changes

2022-11-24 21:46 UTC, andreabadesso approved these changes

2022-11-24 21:47 UTC, andreabadesso approved these changes

2022-11-25 02:06 UTC, merged