feat: create lambda wallet/getTxById
HathorNetwork/hathor-wallet-service-old pull request #309
Opened 2022-11-14 19:16 UTC by alexruzenhack

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-11-17 20:03 UTC, tuliomir requested changes

2022-11-17 20:03 UTC, tuliomir commented on serverless.yml
>      warmup:
Maybe this route could have the warmup active. I think it's worth at least studying the benefits and the costs of it.

2022-11-17 20:03 UTC, tuliomir commented on src/db/index.ts
> +  const result: DbSelectResult = await mysql.query(
The query here must be more complex to be able to retrieve the transaction's balances for the current wallet as well. 

As proposed by the design, it should have a similar interface to the [`getWalletTxHistory` method](https://github.com/HathorNetwork/hathor-wallet-service/blob/master/src/db/index.ts#L1331-L1384), but fetching every relevant token for this specific wallet.

2022-11-17 20:03 UTC, tuliomir commented on tests/txById.test.ts
> +describe('statusCode:404', () => {
I suggest having a `statusCode:500` test as well, mocking the method calls made internally and ensuring a treated response is delivered to the middleware.

2022-11-18 02:59 UTC, pedroferreira1 commented on src/db/index.ts
> +  const result: DbSelectResult = await mysql.query(
We also need the check if this tx belongs to the `walletId` from the request, otherwise it's 404

2022-11-21 01:45 UTC, alexruzenhack commented on tests/txById.test.ts
> +describe('statusCode:404', () => {
Do we have a global error handler? Because beyond this scenario I don't see a way to go wrong, except for connection errors and things like that. Unknown errors should be globally caught imo.

2022-11-21 01:45 UTC, alexruzenhack commented on tests/txById.test.ts
> +describe('statusCode:404', () => {
Also, tests are good, but not too much. I agree with this quote ["Write tests. Not too many. Mostly integration."](https://twitter.com/rauchg/status/807626710350839808?s=20&t=dI2uUted0o5yBWErR9Zbgg)

2022-11-21 01:45 UTC, alexruzenhack commented on serverless.yml
>      warmup:
I believe @andreabadesso can give us a hand about it

2022-11-21 17:00 UTC, andreabadesso commented on serverless.yml
>      warmup:
We are currently only warming up the lambdas called during the wallet load so we don't impact the perceived loading time

I would suggest not warming it up to avoid unnecessary lambda calls (the warmup process is a lambda call every 5 minutes)

2022-11-22 23:35 UTC, tuliomir reviewed
The current state of the PR has more code than what is related to the `getTxById` method.

I think it's a good idea to separate it to isolate the review only on the PR's main subject.

2022-11-22 23:35 UTC, tuliomir commented on src/db/index.ts
> +      wallet_tx_history.wallet_id AS wallet_id
Do we need this column on the results? We have filtered by a single `wallet_id` already.

2022-11-22 23:35 UTC, tuliomir commented on src/db/index.ts
> +    INNER JOIN transaction ON transaction.tx_id = wallet_tx_history.tx_id
Taking a double look at the front-end design and checking this query here it seems the design did not consider the client's need for the tokens' names and symbols on the response.

On the front-end, this will be the desired results:
![Front end exhibition](https://user-images.githubusercontent.com/1299409/199364594-13832f87-20d1-4094-9573-29b0f81393a5.png)

To achieve this, we will need to add two new columns here, otherwise the client application will have nowhere to fetch these data from:
```sql
SELECT
  ...
  token.name AS token_name
  token.symbol AS token_symbol
FROM ...
INNER JOIN token ON wallet_tx_history.token_id = token.id
WHERE ...
```

2022-11-22 23:35 UTC, tuliomir commented on tests/db.test.ts
> +  it('should return null when there is no record', async () => {
it actually returns an empty array, not `null`, right?

2022-11-22 23:35 UTC, tuliomir commented on tests/txById.test.ts
> +  expect(returnBody.tx).toHaveLength(2);
The property `tx` seems to indicate we have two transactions on the response, and could be misleading.

Maybe we could rename it to something that makes it clear that this property is related to a list of token balances? Two possibilities I see are:
- Changing the `tx` property to something like `{ txId: string, tokens: [] }`
- Just changing the `tx` property name to `txTokens`, as received by the db util function

What do you think?

2022-11-23 05:15 UTC, andreabadesso requested changes

2022-11-23 05:15 UTC, andreabadesso commented on src/api/pushUnregister.ts
> +    return { value: { enablePush: false, enableShowAmounts: false, ...value }, error };
Where do `enablePush` and `enableShowAmounts` come from? They are not in the `bodySchema`

Should they be constants? I'm a little confused on what this is doing

2022-11-23 05:15 UTC, andreabadesso commented on src/db/index.ts
> +    INNER JOIN transaction ON transaction.tx_id = wallet_tx_history.tx_id
```suggestion
    SELECT transaction.tx_id AS tx_id,
           transaction.timestamp AS timestamp,
           transaction.version AS version,
           transaction.voided AS voided,
           transaction.height AS height,
           transaction.weight AS weight,
           wallet_tx_history.balance AS balance,
           wallet_tx_history.token_id AS token_id,
           wallet_tx_history.wallet_id AS wallet_id
      FROM wallet_tx_history
INNER JOIN transaction ON transaction.tx_id = wallet_tx_history.tx_id

```

2022-11-23 05:15 UTC, andreabadesso commented on src/db/index.ts
> +    SELECT COUNT(1) as \`count\` FROM \`wallet\` pd WHERE id= ?`,
```suggestion
SELECT COUNT(1) as \`count\`
  FROM \`wallet\` pd
 WHERE id = ?
```

2022-11-23 05:15 UTC, andreabadesso commented on tests/db.test.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention, camelcase
Why don't you just call it `deviceId1` or `deviceIdOne`?

2022-11-23 05:15 UTC, andreabadesso commented on tests/pushRegister.test.ts
> +    expect(returnBody.error).toStrictEqual('invalid-payload');
Import and use `ApiError.INVALID_PAYLOAD`

2022-11-23 05:15 UTC, andreabadesso commented on tests/pushRegister.test.ts
> +    expect(returnBody.error).toStrictEqual('invalid-payload');
Same here

2022-11-23 05:15 UTC, andreabadesso commented on tests/pushRegister.test.ts
> +    expect(returnBody.error).toStrictEqual('wallet-not-found');
Import and use `ApiError.WALLET_NOT_FOUND`

2022-11-23 05:15 UTC, andreabadesso commented on tests/pushUpdate.test.ts
> +    expect(returnBody.error).toStrictEqual('invalid-payload');
Same here

2022-11-23 05:15 UTC, andreabadesso commented on tests/pushUpdate.test.ts
> +    expect(returnBody.error).toStrictEqual('device-not-found');
Same here

2022-11-23 05:15 UTC, andreabadesso commented on src/db/index.ts
> +    INNER JOIN transaction ON transaction.tx_id = wallet_tx_history.tx_id
![Screenshot 2022-11-23 at 02 09 04](https://user-images.githubusercontent.com/3586068/203472812-3218f12b-e45a-40be-ad21-3f714a67eea0.png)

Wow, this is annoying me more than it should, is this happening on the production app?

2022-11-23 05:15 UTC, andreabadesso commented on serverless.yml
> +  getTxById:
We should add the `authorizer` key here to only allow querying if the user is authenticated

2022-11-23 05:15 UTC, andreabadesso commented
Can you link the design on this PR? Took me a while to find it as it is on the internal-issues project:

https://github.com/HathorNetwork/internal-issues/issues/124

2022-11-23 21:10 UTC, alexruzenhack commented on src/db/index.ts
> +      wallet_tx_history.wallet_id AS wallet_id
Well, I have followed the walletTxHistory. But you right.

2022-11-23 21:29 UTC, alexruzenhack commented on tests/txById.test.ts
> +  expect(returnBody.tx).toHaveLength(2);
I chose `txTokens` to represent the list, this is a good name indeed.

2022-11-25 00:04 UTC, alexruzenhack commented on serverless.yml
> +  getTxById:
How do I do it? Can you provide an example?

2022-11-25 00:07 UTC, andreabadesso approved these changes

2022-11-25 12:27 UTC, tuliomir approved these changes

2022-11-25 12:27 UTC, tuliomir commented on src/db/index.ts
> + * @returns A a list of tokens for a transaction if found, return an empty list otherwise
```suggestion
 * @returns A list of tokens for a transaction if found, return an empty list otherwise
```

2022-11-25 12:27 UTC, tuliomir commented on tests/db.test.ts
> +  it('should return null when there is no record', async () => {
Should we change this test's title?

2022-12-01 19:13 UTC, andreabadesso approved these changes

2022-12-01 22:41 UTC, tuliomir approved these changes

2022-12-01 22:41 UTC, tuliomir commented on src/api/pushSendNotificationToDevice.ts
> +import { getPushDevice } from '@src/db';
```suggestion
import { getPushDevice, unregisterPushDevice } from '@src/db';
```

2022-12-02 03:01 UTC, merged