feat: create lambda push/sendNotificationToDevice
HathorNetwork/hathor-wallet-service-old pull request #310
Opened 2022-11-17 00:24 UTC by alexruzenhack

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-11-23 05:22 UTC, andreabadesso requested changes

2022-11-23 05:22 UTC, andreabadesso commented on src/api/pushSendNotificationToDevice.ts
> +    metadata: Joi.object().optional(),
Should we describe better this object? What is expected?

2022-11-23 05:22 UTC, andreabadesso commented on src/db/index.ts
> +      WHERE device_id = ? AND wallet_id = ?`,
```suggestion
      DELETE
        FROM \`push_devices\`
       WHERE \`device_id\` = ?
         AND \`wallet_id\` = ?`,
```

2022-11-23 05:22 UTC, andreabadesso commented on src/db/index.ts
> +    'SELECT * FROM `push_devices` WHERE device_id = ?',
```suggestion
`SELECT *
   FROM \`push_devices\`
  WHERE \`device_id\` = ?`,
```

2022-11-23 05:22 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +const SEND_NOTIFICATION_LAMBDA_ENDPOINT = process.env.SEND_NOTIFICATION_LAMBDA_ENDPOINT;
Maybe we should throw an error here or log with `ALERT` so we get notified that this env is not set

2022-11-23 05:22 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +    return Promise.race([]);
What is this doing?

2022-11-23 05:23 UTC, andreabadesso commented on src/api/pushSendNotificationToDevice.ts
> +    metadata: Joi.object().optional(),
Btw, is this even being used?

2022-11-23 23:00 UTC, alexruzenhack commented on src/api/pushSendNotificationToDevice.ts
> +    metadata: Joi.object().optional(),
@tuliomir Can you clarify for what this `metadata` will be useful?

2022-11-23 23:03 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +    return Promise.race([]);
Oh... this was just a placeholder for the next PR.

2022-11-23 23:05 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +    return Promise.race([]);
You can see the implementation here:
https://github.com/HathorNetwork/hathor-wallet-service/blob/6d0515da45e2ce022de2f066c4cc8d2b43212415/src/utils/pushnotification.utils.ts#L22-L43

2022-11-24 21:53 UTC, andreabadesso approved these changes

2022-11-25 14:57 UTC, tuliomir approved these changes

2022-11-25 14:57 UTC, tuliomir commented on src/api/pushSendNotificationToDevice.ts
> +    metadata: Joi.object().optional(),
We can send JSON metadata with the push. In a previous iteration of the design, there was the possibility of sending an entire transaction here.

Now we only use it for sending the `txId` of the relevant transaction, for example:
```json
"metadata": { 
  "txId": "00e2597222154cf99bfef171e27374e7f35aa7448afae10c15e9f049b95a3e67"
}
```

2022-11-25 14:57 UTC, tuliomir commented on src/utils/pushnotification.utils.ts
> +    return Promise.race([]);
I think this deserves a `TODO` or some other kind of code comment to clarify it's yet to be implemented

2022-11-25 14:57 UTC, tuliomir commented on tests/pushSendNotificationToDevice.test.ts
> +      firstMetadata: 'firstMetadata',
This test could have the sample metadata content expected on the [front-end design](https://github.com/HathorNetwork/internal-issues/issues/132), for example:
```json
"metadata": { 
  "txId": "00e2597222154cf99bfef171e27374e7f35aa7448afae10c15e9f049b95a3e67"
}
```

2022-11-25 14:57 UTC, tuliomir commented on tests/pushSendNotificationToDevice.test.ts
> +const spyOnLoggerError = jest.spyOn(logger, 'error');
Good point! I think we didn't have tests for the logger yet.

2022-11-29 14:52 UTC, merged