feat: implement txPushNotificationRequested lambda
HathorNetwork/hathor-wallet-service-old pull request #315
Opened 2022-11-29 13:35 UTC by alexruzenhack

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-12-06 00:51 UTC, tuliomir commented on src/api/txPushNotificationRequested.ts
> +  deviceSettinsNotFound: 'Failed due to device settings not found.',
```suggestion
  deviceSettingsNotFound: 'Failed due to device settings not found.',
```

2022-12-06 00:51 UTC, tuliomir commented on src/api/txPushNotificationRequested.ts
> +    // TODO: change tokenId to tokenSymbol
When is this refactor expected to happen?

2022-12-06 00:51 UTC, tuliomir commented on tests/txPushNotificationRequested.test.ts
> +    // device with disabled enableShowAmounts, resulting in a generic notification
Actually in _no notification at all_, right?

2022-12-06 00:51 UTC, tuliomir commented on tests/txPushNotificationRequested.test.ts
> +        description: 'You have received 10 token2, 5 token1, and 1 other token on a new transaction.',
Another test with 4 or more tokens to validate the text's plural could be a good idea, since this extra care was taken on the message building method.

2022-12-07 16:23 UTC, andreabadesso requested changes

2022-12-07 16:23 UTC, andreabadesso commented on src/api/txPushNotificationRequested.ts
> +    logger.error('[ALERT] Invalid payload.', { details });
This error message will be presented to the on-call, so we should improve the error message, maybe something like `Invalid payload while handling push notification request`

2022-12-07 16:23 UTC, andreabadesso commented on src/api/txPushNotificationRequested.ts
> +    return { success: false, message: pushNotificationMessage.deviceSettinsNotFound };
```suggestion
    return { success: false, message: pushNotificationMessage.deviceSettingsNotFound };
```

2022-12-07 16:23 UTC, andreabadesso commented on src/api/txPushNotificationRequested.ts
> +    return { success: false, message: pushNotificationMessage.deviceSettinsNotFound };
Maybe grep those spelling mistakes, there were many on all those projects

2022-12-07 16:23 UTC, andreabadesso commented on src/db/utils.ts
> +    } as TokenBalanceValue));
```suggestion
    const balances = entryBalances.map(([tokenId: string, balance: Balance]) => ({
      tokenId: tokenId,
      tokenSymbol: tokenSymbolsMap[tokenId],
      lockedAmount: balance.lockedAmount,
      lockedAuthorities: balance.lockedAuthorities.toJSON(),
      lockExpires: balance.lockExpires,
      unlockedAmount: balance.unlockedAmount,
      unlockedAuthorities: balance.unlockedAuthorities.toJSON(),
      totalAmountSent: balance.totalAmountSent,
      total: balance.total(),
    } as TokenBalanceValue));
```

2022-12-07 16:23 UTC, andreabadesso commented on src/types.ts
> +  body_loc_args: string,
Maybe use `camelCase`

2022-12-07 16:23 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +         * We can change priority to 'hight' to attempt deliver the message as soon as possible,
```suggestion
         * We can change priority to 'high' to attempt deliver the message as soon as possible,
```

2022-12-08 02:48 UTC, alexruzenhack commented on src/api/txPushNotificationRequested.ts
> +    logger.error('[ALERT] Invalid payload.', { details });
I'm adding more context to the log structure, like `module` and `scope`. There are other 3 configurations we can apply to winston in order to have a very good log context.
```
logger.defaultMeta = {
    module: __filename,
    scope: handleRequest.name,
    requestId: context.awsRequestId,
  };
```

2022-12-08 02:59 UTC, alexruzenhack commented on src/api/txPushNotificationRequested.ts
> +    return { success: false, message: pushNotificationMessage.deviceSettinsNotFound };
I adopted this extension now: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-12-08 03:01 UTC, alexruzenhack commented on src/db/utils.ts
> +    } as TokenBalanceValue));
I fixed it in PR 313, I will rebase it.

2022-12-08 03:12 UTC, alexruzenhack commented on src/api/txPushNotificationRequested.ts
> +    // TODO: change tokenId to tokenSymbol
I implemented it in PR 313. I just rebase it. Now, this to-do has gone.

2022-12-08 14:54 UTC, tuliomir approved these changes

2022-12-11 20:12 UTC, andreabadesso approved these changes

2022-12-12 12:11 UTC, merged