feat: implement db.routine to delete stale push devices
HathorNetwork/hathor-wallet-service-old pull request #323
Opened 2022-12-07 05:41 UTC by alexruzenhack

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-12-07 14:02 UTC, tuliomir approved these changes

2022-12-07 14:02 UTC, tuliomir commented on serverless.yml
> +      - schedule: cron(17 3 */15 * * *)
A comment with the interval written here would be helpful too

2022-12-07 14:02 UTC, tuliomir commented on src/db.routines.ts
> +/**
What do you think about moving this file to the `db/` folder?

2022-12-07 14:02 UTC, tuliomir commented on src/db/index.ts
> +     WHERE updated_at > UNIX_TIMESTAMP(date_sub(now(), interval 1 month))`,
Not that it's really necessary, but I think it would be nice to have a constant for all queries that may want to interact with potentially stale devices, should they grow beyond those two.

What do you think of:
```js
const SQL_STALE_DEVICE_TIMESTAMP = 'UNIX_TIMESTAMP(date_sub(now(), interval 1 month))'
```

and then on the queries:
```mysql
SET stale_timestamp = (?)

SELECT
  # ...
  WHERE updated_at > stale_timestamp
```

2022-12-07 16:28 UTC, andreabadesso commented on src/db.routines.ts
> +/**
Or maybe something like `cron/`, `schedules/`

2022-12-07 16:29 UTC, andreabadesso requested changes

2022-12-07 16:29 UTC, andreabadesso commented on src/db/index.ts
> +  );
```suggestion
    DELETE
      FROM \`push_devices\`
     WHERE updated_at > UNIX_TIMESTAMP(date_sub(now(), interval 1 month))`,
```

2022-12-08 01:47 UTC, alexruzenhack commented on src/db/index.ts
> +     WHERE updated_at > UNIX_TIMESTAMP(date_sub(now(), interval 1 month))`,
What is the use case you have in mind?

2022-12-08 01:55 UTC, alexruzenhack commented on src/db.routines.ts
> +/**
Imo the folder `db/` is better to keep consistency, but I add `cron` as a prefix in the file name.

2022-12-08 15:06 UTC, tuliomir commented on src/db/index.ts
> +     WHERE updated_at > UNIX_TIMESTAMP(date_sub(now(), interval 1 month))`,
Nothing specific, just thinking on the DRY principle

2022-12-08 21:22 UTC, alexruzenhack commented on src/db/index.ts
> +     WHERE updated_at > UNIX_TIMESTAMP(date_sub(now(), interval 1 month))`,
I see. Well, let these cases come naturally. We don't know if we will really need it in the future.

2022-12-09 12:40 UTC, andreabadesso approved these changes

2022-12-10 18:29 UTC, merged