feat: refactor txById to receive txId by path param
HathorNetwork/hathor-wallet-service-old pull request #329
Opened 2022-12-11 18:14 UTC by alexruzenhack

### Acceptance Criteria
- pass txId by path param, it will simplify the endpoint usage and comply with HTTP REST spec

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-12-11 20:14 UTC, andreabadesso requested changes

2022-12-11 20:14 UTC, andreabadesso commented on serverless.yml
> +          path: wallet/txById/{txId}
What do you think about refactoring it to be something line:

`wallet/transactions/{txId}`

I think it looks a lot more `restful`

2022-12-12 12:09 UTC, alexruzenhack commented on serverless.yml
> +          path: wallet/txById/{txId}
@andreabadesso, you're right. I didn't use `/transactions` because I was afraid to use it, but it is indeed better.

2022-12-13 16:07 UTC, andreabadesso approved these changes

2022-12-13 16:08 UTC, andreabadesso commented on serverless.yml
> +          path: wallet/txById/{txId}
@alexruzenhack thanks!

Don't forget to update the acceptance criteria

2022-12-13 16:11 UTC, andreabadesso requested changes

2022-12-13 16:11 UTC, andreabadesso commented on src/api/txById.ts
> +    txId: Joi.string().min(1).required(),
I guess we can use `.min(32).max(32)` here since `txId` will always be a `sha256d` hash

2022-12-14 01:35 UTC, alexruzenhack commented on src/api/txById.ts
> +    txId: Joi.string().min(1).required(),
Are you sure it is 32 characters? Doesn't it 64?

2022-12-14 14:55 UTC, andreabadesso commented on src/api/txById.ts
> +    txId: Joi.string().min(1).required(),
Oops, it's in hexadecimal string format, so yes, 64 bytes

Sorry

2022-12-14 20:24 UTC, tuliomir commented on src/api/txById.ts
> +    txId: Joi.string().min(32).max(32).required(),
From previous conversations I see that this should be `min(64).max(64)`

2022-12-14 21:31 UTC, tuliomir approved these changes

2022-12-15 00:26 UTC, andreabadesso approved these changes

2022-12-15 16:15 UTC, merged