feat: refactor firebase environment variables
HathorNetwork/hathor-wallet-service-old pull request #331
Opened 2022-12-16 19:28 UTC by alexruzenhack

### Acceptance Criteria
- refactor the configuration of firebase cloud message to use environment variables

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-12-19 17:38 UTC, andreabadesso requested changes

2022-12-19 17:38 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +  "client_x509_cert_url": FIREBASE_CLIENT_X509_CERT_URL,
Use single quotes

2022-12-19 19:55 UTC, andreabadesso approved these changes

2022-12-20 13:52 UTC, pedroferreira1 approved these changes

2022-12-20 18:50 UTC, merged