feat: returning token list on txProposalCreate
HathorNetwork/hathor-wallet-service-old pull request #36
Opened 2021-03-10 18:31 UTC by andreabadesso

We need to return the tokens array as it's needed to assemble the tx for mining

2021-03-11 19:23 UTC, pedroferreira1 requested changes

2021-03-11 19:23 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  const tokens = Array.from(new Set([...outputsBalance.getTokens(), ...inputsBalance.getTokens()]));
If this is needed only for assembling the tx for mining, we don't need to add the tokens in the inputs. If we have a tx that is a destroy authority tx (which has only one input and no outputs), this tx has an empty tokens array.

2021-03-12 18:47 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const tokens = Array.from(new Set([...outputsBalance.getTokens(), ...inputsBalance.getTokens()]));
Done in 4c65abea9c2b550925ccca4aee49d7aab37e394f

2021-03-12 18:47 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const tokens = Array.from(new Set([...outputsBalance.getTokens(), ...inputsBalance.getTokens()]));
Done in 4c65abea9c2b550925ccca4aee49d7aab37e394f

2021-03-15 17:32 UTC, msbrogli approved these changes

2021-03-15 18:07 UTC, pedroferreira1 approved these changes

2021-03-22 17:01 UTC, merged