chore: add tags on resources
HathorNetwork/hathor-wallet-service-old pull request #363
Opened 2023-01-06 22:22 UTC by luislhl

### Acceptance Criteria
- Include here all things that this PR should solve

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-01-09 13:22 UTC, andreabadesso requested changes

2023-01-09 13:22 UTC, andreabadesso commented on serverless.yml
> +    # role: arn:aws:iam::${self:provider.environment.ACCOUNT_ID}:role/WalletServiceLoadWalletLambda
Should this be commented?

2023-01-09 13:27 UTC, andreabadesso approved these changes

2023-01-09 13:49 UTC, alexruzenhack commented on package-lock.json
> +      "version": "0.0.0",
@luislhl This is strange. I nerve saw a package versioned like this.

2023-01-09 13:52 UTC, alexruzenhack approved these changes
I have only one comment about the package `"user": "0.0.0"`. This is a strange value. Does it worth double check on it?

2023-01-09 15:23 UTC, alexruzenhack commented on package-lock.json
> +      "version": "1.22.3-alpha",
Thank you!

2023-01-09 15:24 UTC, alexruzenhack approved these changes
Nice!

2023-01-09 16:12 UTC, luislhl commented on package-lock.json
> +      "version": "0.0.0",
I've removed this plugin. I was led to believe we needed it by their own page on the serverless site: https://www.serverless.com/plugins/serverless-plugin-resource-tagging

But, after your comment, I decided to make sure and it turns out serverless already has a good built-in support for tagging resources.

2023-01-10 15:46 UTC, andreabadesso approved these changes

2023-01-10 18:05 UTC, merged