fix: push notification
HathorNetwork/hathor-wallet-service-old pull request #372
Opened 2023-01-24 03:39 UTC by alexruzenhack

### Acceptance Criteria
- chore: add permissions to invoke push lambdas
- chore: rename lambda to txPushRequested
- fix: lambda sendNotificationToDevice
- fix: lambda txPushRequested
- feat: improve pushnotification.utils.js
- feat: add push notification feature toggle in the onNewTxRequest lambda

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-01-30 18:19 UTC, andreabadesso requested changes

2023-01-30 18:19 UTC, andreabadesso commented on package.json
> +    "bitcore-lib": "8.25.31"
Why is this listed as a dependency? We only use it on the tests

2023-01-30 18:19 UTC, andreabadesso commented on tsconfig.json
> +    "module": "commonjs",
What is this for?

2023-01-31 12:49 UTC, alexruzenhack commented on tsconfig.json
> +    "module": "commonjs",
This is to enable dynamic imports using the ecma6 import syntax, like this: https://github.com/HathorNetwork/hathor-wallet-service/pull/372/files#diff-d79c36e7f5deb2d97946b3313d23d929ef33fb0790d7fa03602a9e44e3a05b5aR247

2023-01-31 13:04 UTC, alexruzenhack commented on package.json
> +    "bitcore-lib": "8.25.31"
I did it to trying to resolve the bitcore-lib issue. I have restored it to dev dependencies now.

2023-02-01 17:14 UTC, tuliomir commented on tests/pushSendNotificationToDevice.test.ts
> +  process.env = initEnv;
Since each test will overwrite the `process.env` anyway, maybe it would be better to move this environment-reverting code to `afterAll`, wouldn't it?

2023-02-01 17:14 UTC, tuliomir commented on tests/txPushNotificationRequested.test.ts
> +    // device with disabled enableShowAmounts, resulting in a generic notification
This comments leads the reader to think there will be a consequence to the `enableShowAmounts` property here, but the test ignores this and just tests an error handling, right?

If this is correct, maybe just removing this comment would be better for the reader.

2023-02-01 17:14 UTC, tuliomir commented on src/utils/pushnotification.utils.ts
> +const PUSH_ALLOWED_PROVIDERS = (() => {
The format this data is stored caused some weird bits of code on the testing, especially the need to `await import()` in the middle of the code, which for me indicates a testing code smell ( even though it works just fine! ).

I suggest one of two paths here, since this PR is already quite big and the feature has chained ongoing PR's:
- Changing `PUSH_ALLOWED_PROVIDERS` to a function `getPushAllowedProviders()` that fetch the most up-to-date environment variables
- Adding an explanatory JSDocs here to this constant, making it clear that it only stores the environment values once and, should they change on testing, another import is needed to update them ( with a reference to the already existing test code )

If deciding for a code change only later, an issue could be open to keep track of this as well.

2023-02-02 12:39 UTC, alexruzenhack commented on tests/pushSendNotificationToDevice.test.ts
> +  process.env = initEnv;
Hummm... you right!

2023-02-02 13:04 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +const PUSH_ALLOWED_PROVIDERS = (() => {
I did it to avoid calling `process.env` during the lambda's handler processing. Otherwise, this would be another blocking call. Besides that, constants are good to optimize lambda execution, after all the constants are executed in the INIT phase and can be reutilized in warmed instances.

The way to test it is the same for the `env` variables. But sure, I will improve the docstring. However, given it is better to keep it as a constant, should I open an issue?

2023-02-02 13:10 UTC, tuliomir commented on src/utils/pushnotification.utils.ts
> +const PUSH_ALLOWED_PROVIDERS = (() => {
No need for issues, just the helper comments will be fine :+1:

2023-02-02 14:07 UTC, tuliomir approved these changes

2023-02-02 14:07 UTC, tuliomir commented on src/utils/pushnotification.utils.ts
> + * It need to be reloaded after change the underlying environment variable
```suggestion
 * It needs to be reloaded after changing the underlying environment variable
```

2023-02-02 15:45 UTC, andreabadesso approved these changes

2023-02-02 16:32 UTC, merged