refactor: alert using sqs
HathorNetwork/hathor-wallet-service-old pull request #378
Opened 2023-01-30 16:07 UTC by andreabadesso

### Acceptance Criteria
- We should send alerts directly to SQS instead of just logging with an `ALERT` string

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-02-07 15:44 UTC, alexruzenhack requested changes
The is only one required change, but some bikes you may want to address and other thoughts.

2023-02-07 15:44 UTC, alexruzenhack commented on src/api/pushSendNotificationToDevice.ts
> +  if (isPushProviderAllowed(pushDevice.pushProvider)) {
@andreabadesso Here the condition should have a negative `!`. Only log the error if the provider is not allowed.
```javascript
if (!isPushProviderAllowed(pushDevice.pushProvider)) {
```

2023-02-07 15:44 UTC, alexruzenhack commented on src/types.ts
> +export enum Severity {
🚲 I believe it would be nice to have JSDoc here explaining this severity is related to the alert system, because the severity definition for the log may be different.

2023-02-07 15:44 UTC, alexruzenhack commented on src/utils.ts
> +export const validateEnvVariables = (envVariables: string[]): void => {
🚲 A validation function implies a boolean return, which is not the case here. Should the name be changed to convey a better semantic? I suggest `assertEnvVariablesExistence`, but this is a `bike`.

2023-02-07 15:44 UTC, alexruzenhack commented on src/utils/alerting.utils.ts
> +      logger.error(err);
💭 Why use 2 error logs? Why not only 1:
```javascript
logger.error('[ALERT] Erroed while sending message to the alert sqs queue', err);
```

2023-02-07 15:44 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +        `${SEND_NOTIFICATION_FUNCTION_NAME} lambda invoke failed for wallets`,
🚫 Here should be `ON_TX_PUSH_NOTIFICATION_REQUESTED_FUNCTION_NAME` in the place of `SEND_NOTIFICATION_FUNCTION_NAME`

2023-02-07 15:44 UTC, alexruzenhack commented on src/ws/connection.ts
> +    logger.error(e);
💭 Should the error log also have an explanation?
```javascript
logger.error('Captured error on connect websocket lambda', e);
```

2023-02-07 15:44 UTC, alexruzenhack commented on tests/utils/alerting.utils.mock.ts
> +}));
⭐ Nice!

2023-02-07 15:44 UTC, alexruzenhack commented on tests/utils/pushnotification.utils.test.ts
> +      expect(mockedAddAlert).toHaveBeenLastCalledWith(
🚲 It is working, but it would be nice to have the `mockedAddAlert` mock reset `beforeEach`, [like in the line `36`](https://github.com/HathorNetwork/hathor-wallet-service/pull/378/files#diff-da2fa7c63ab1c8c03df04018ca79ce81c497c3c20bf41cea89659689dd2684d7R36).

2023-02-07 15:46 UTC, alexruzenhack commented on src/utils.ts
> +export const validateEnvVariables = (envVariables: string[]): void => {
⭐ But nice function!

2023-02-07 16:13 UTC, andreabadesso commented on src/utils.ts
> +export const validateEnvVariables = (envVariables: string[]): void => {
I agree with the name change, done in fba51be743dd63d6e336f684c081b0649d15985e

2023-02-07 16:14 UTC, andreabadesso commented on src/utils/alerting.utils.ts
> +      logger.error(err);
Not sure, refactored in 0bd59b087878707537898b48d65b8d12db224bf9

2023-02-07 16:17 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +        `${SEND_NOTIFICATION_FUNCTION_NAME} lambda invoke failed for wallets`,
Thanks, done in 230285c7b9395145474a8a9f45942ff64c5dffcb

2023-02-07 16:18 UTC, andreabadesso commented on src/ws/connection.ts
> +    logger.error(e);
Done in 45d242d26ad848c1501fcc565a393d0afee809a2

2023-02-07 16:23 UTC, andreabadesso commented on tests/utils/pushnotification.utils.test.ts
> +      expect(mockedAddAlert).toHaveBeenLastCalledWith(
Done in b5c0046872637f2215e0ef24fbcab0e12cbdae46

2023-02-07 16:24 UTC, andreabadesso commented on src/api/pushSendNotificationToDevice.ts
> +  if (isPushProviderAllowed(pushDevice.pushProvider)) {
Wow, not sure what happened here, fixed in 86821c0a

2023-02-09 16:57 UTC, tuliomir commented on src/commons.ts
> +      Severity.MINOR,
Should we have multiple alerts with different severities for an increasing amount of blocks being _re-org_'d? A reorg of 2 blocks being `minor`, but a reorg of 20 blocks being `major` or something.

The place for this kind of implementation is not in a refactor PR, but I wanted to bring up the subject on the code here.

2023-02-09 16:57 UTC, tuliomir commented on src/types.ts
> +export enum Severity {
Agreed. A link to the document containing the most up-to-date definitions (if available) would be a great addition.

2023-02-09 16:57 UTC, tuliomir commented on src/utils/pushnotification.utils.ts
> +        `${SEND_NOTIFICATION_FUNCTION_NAME} lambda invoke failed for wallets`,
I'm confused: I'm reviewing a version more recent than this `230285c` commit and the value is back to `SEND_NOTIFICATION_FUNCTION_NAME`. No commit seems to have reverted it.

Can you please double check this has the correct value now?

2023-02-09 16:57 UTC, tuliomir commented on src/utils/alerting.utils.ts
> +    application: process.env.APPLICATION_NAME,
I would suggest adding a call to `assertEnvVariablesExistence()` to ensure these variables are present on startup, so that we don't send insufficient data to the alert manager.

2023-02-10 13:51 UTC, alexruzenhack requested changes
Still have a required change to make. These little things to change are the devil.

2023-02-10 13:51 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +        `${ON_TX_PUSH_NOTIFICATION_REQUESTED_FUNCTION_NAME} lambda invoke failed for device: ${notification.deviceId}`,
⛔ Here should be `SEND_NOTIFICATION_FUNCTION_NAME`

2023-02-10 13:51 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +        `${SEND_NOTIFICATION_FUNCTION_NAME} lambda invoke failed for wallets`,
I've realized the problem. The commit above changes the constant in the wrong place 😅, where the commit made the change was correct.

The `invokeSendNotificationHandlerLambda` function must have the following:
- `SEND_NOTIFICATION_FUNCTION_NAME`

The `invokeOnTxPushNotificationRequestedLambda` function must have the following:
- `ON_TX_PUSH_NOTIFICATION_REQUESTED_FUNCTION_NAME`

2023-02-10 13:51 UTC, alexruzenhack commented on src/utils/pushnotification.utils.ts
> +        `${ON_TX_PUSH_NOTIFICATION_REQUESTED_FUNCTION_NAME} lambda invoke failed for device: ${notification.deviceId}`,
See the comment that follows.

2023-02-14 16:05 UTC, andreabadesso commented on src/commons.ts
> +      Severity.MINOR,
I guess we can, I don't remember and couldn't find where we discussed this current setting

I'll create an issue so we track and discuss this

2023-02-14 16:08 UTC, andreabadesso commented on src/types.ts
> +export enum Severity {
I agree, done in 516a2b4dc58ebc3d84de73ec107c2c886c9c6b80

2023-02-14 16:12 UTC, andreabadesso commented on src/utils/pushnotification.utils.ts
> +        `${SEND_NOTIFICATION_FUNCTION_NAME} lambda invoke failed for wallets`,
Oops! Fixed in 071b8d52104138a5defee2a1c17b9157b2b920ac

2023-02-14 16:18 UTC, tuliomir approved these changes

2023-02-14 16:20 UTC, alexruzenhack approved these changes

2023-02-15 17:24 UTC, merged