feat: basic service working
HathorNetwork/hathor-wallet-service-old pull request #4
Opened 2020-07-08 22:59 UTC by obiyankenobi

2020-07-14 09:16 UTC, msbrogli requested changes

2020-07-14 09:16 UTC, msbrogli commented on DATABASE.md
> +# Database
Isn't it better to have a `create_database.sql` file, so we can redirect to mysql client?

2020-07-14 09:16 UTC, msbrogli commented on README.md
> +The hathor-wallet-service is the backend for all official Hathor wallets. It's highly inspired in the [Bitcore Wallet
We've changed so many things that I'm not sure it is highly inspired anymore, hehe. But it is ok to have it here.

2020-07-14 09:16 UTC, msbrogli commented on fullnode-bridge.js
> +/* eslint-disable */
Just drop a comment explaining what it is for and that it is not supposed to be used in production.

2020-07-14 09:16 UTC, msbrogli commented on src/api/addresses.ts
> +const mysql = getDbConnection();
I'm not sure we should get a connection while loading the module.

2020-07-14 09:16 UTC, msbrogli commented on src/api/addresses.ts
> +export const get: APIGatewayProxyHandler = async (event) => {
Does `event` has a type?

2020-07-14 09:16 UTC, msbrogli commented on src/api/addresses.ts
> +    await closeDbConnection(mysql);
We're copying it around. Maybe we should create an error method? Or encapsulate this whole module in a class?

2020-07-14 09:16 UTC, msbrogli commented on src/api/balances.ts
> +const mysql = getDbConnection();
Same comments I did for `src/api/balances.ts`.

2020-07-14 09:16 UTC, msbrogli commented on src/api/txhistory.ts
> +// TODO get from lib
Important TODO.

2020-07-14 09:16 UTC, msbrogli commented on src/api/txhistory.ts
> +  const history = await getWalletTxHistory(mysql, walletId, tokenId, skip, count);
Instead of passing all these parameters over and over, isn't it better to have a class?

2020-07-14 09:16 UTC, msbrogli commented on src/api/wallet.ts
> +  status = await createWallet(mysql, walletId, xpubkey, maxGap);
You are subject to a race condition here. When you check whether a wallet exists, if it doesn't, you should leave a marker saying that it will be created. I think the best way here is to try to insert and handle the error if the key already exists.

2020-07-14 09:16 UTC, msbrogli commented on src/api/wallet.ts
> +    apiVersion: '2015-03-31',
Where does this magic date come from? Maybe we should create an internal method that handles that for us.

2020-07-14 09:16 UTC, msbrogli commented on src/api/wallet.ts
> +    // TODO handle
You should at least log something and return `success: false`.

2020-07-14 09:16 UTC, msbrogli commented on src/api/wallet.ts
> +export const loadWallet: Handler<LoadEvent, LoadResult> = async (event) => {
I think the name is misleading. I think `loadWallet` is used to load something that already exists. Maybe rename it to `createWallet` or `startWallet` or `prepareFreshWallet`. What do you think?

2020-07-14 09:16 UTC, msbrogli commented on src/utils.ts
> +// TODO get from hathor-lib or maybe env?
Why not `hathor-wallet-lib`?

2020-07-14 10:44 UTC, obiyankenobi commented on README.md
> +The hathor-wallet-service is the backend for all official Hathor wallets. It's highly inspired in the [Bitcore Wallet
That's true. I just copied the text from the design, but I'll update this.

2020-07-14 10:47 UTC, obiyankenobi commented on src/api/addresses.ts
> +const mysql = getDbConnection();
This is the correct way to do for lambda handlers. [This example](https://docs.aws.amazon.com/lambda/latest/dg/services-rds-tutorial.html) uses python, but the idea is the same: "Executing pymysql.connect() outside of the handler allows your function to re-use the database connection for better performance."

2020-07-14 10:52 UTC, obiyankenobi commented on src/api/addresses.ts
> +export const get: APIGatewayProxyHandler = async (event) => {
Yes, it's already typed by APIGatewayProxyHandler: `export type APIGatewayProxyHandler = Handler<APIGatewayProxyEvent, APIGatewayProxyResult>;`

It means the parameter is `APIGatewayProxyEvent` and it returns a `APIGatewayProxyResult`.

2020-07-14 10:56 UTC, obiyankenobi commented on src/api/addresses.ts
> +    await closeDbConnection(mysql);
What code do you mean? Just `closeConnection` or the whole process of checking if wallet exists and returning the error?

2020-07-14 10:58 UTC, obiyankenobi commented on src/api/txhistory.ts
> +  const history = await getWalletTxHistory(mysql, walletId, tokenId, skip, count);
I don't see any advantage, at least not at the moment. What other methods would we have in the class? Where else would it be used?

2020-07-14 11:00 UTC, obiyankenobi commented on src/api/wallet.ts
> +  status = await createWallet(mysql, walletId, xpubkey, maxGap);
I agree. But I'm not sure about the marker idea. Shouldn't just handling the error be enough?

2020-07-14 11:01 UTC, obiyankenobi commented on src/api/wallet.ts
> +    apiVersion: '2015-03-31',
It's standard aws lambda invocation. We can have another method, but it'd have exactly the same code.

2020-07-14 11:03 UTC, obiyankenobi commented on src/utils.ts
> +// TODO get from hathor-lib or maybe env?
Yes, I meant `hathor-wallet-lib`.

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/addresses.ts
> +    return {
All files have exactly this return. I think would be good to create a method on utils `return_200` that receives only the object and creates the object with status code and body

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/wallet.ts
> +    if (!body) throw new Error('body is null');
For me this is the same case of a missing or invalid parameter. So it makes no sense to handle it differently, we should return the erro to the user.

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.INVALID_PARAMETER, parameter: 'xpubkey' }),
The invalid parameter here isn't the `body`?

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.MISSING_PARAMETER, parameter: 'xpubkey' }),
I think this return is bad. You've been using this as a missing request parameter but this xpubkey is a missing key inside the body parameter, so this could give a false impression to the user who could just add a `xpubkey` parameter. You could return here 'invalid_parameter' for the body again. (If I understood correctly `body` is the only parameter here

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
I'm thinking if we should allow the user to send a custom `maxGap` in the request. If we don't do that we are saying to all the use cases that need more than 20 addresses on the gap (maybe it's not an expressive quantity) that they need to run their own wallet service to use Hathor for their use cases, which goes totally in the opposite side of what we sell, that is user friendly to create your use case.

However if we allow anything here we let people send a huge number, which could increase the database really fast. So I think we could have the `DEFAULT_ADDRESS_GAP=20` and `MAX_ADDRESS_GAP=100`. Then we just allow uses cases until 100 address gap. I think it's  a small change that does no harm to the code and allow more use cases to use it.

2020-07-14 16:25 UTC, pedroferreira1 commented on src/api/wallet.ts
> +    FunctionName: `${process.env.SERVICE_NAME}-${process.env.STAGE}-loadWalletAsync`,
Why do you need this to be in another lambda?

2020-07-14 16:25 UTC, pedroferreira1 commented on src/db.ts
> +import { strict as assert } from 'assert';
I think this file should be split. We have methods here that deal with different parts of the wallet and it's already 627 lines. If we don't split now it will be more than 1k lines before the first release, which would be bad to maintain

2020-07-14 16:25 UTC, pedroferreira1 commented on src/db.ts
> +      // balance as (tokenBalance < 0 ? 0 : tokenBalance). In case the balance is negative, there
When the balance can be negative?

2020-07-14 16:25 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  if (tx.version === 0 || tx.version === 3) {
This values should be move to a constants file or if we use our lib, we can get it from there

2020-07-15 09:31 UTC, obiyankenobi commented on src/api/wallet.ts
> +    if (!body) throw new Error('body is null');
That's what's being done. The error is thrown and handled in the catch block.

2020-07-15 09:41 UTC, obiyankenobi commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.INVALID_PARAMETER, parameter: 'xpubkey' }),
Not per se. There isn't a `body` parameter. The user should send `{"xpubkey": "myxpub"}`. Instead of `INVALID_PARAMETER`, maybe `INVALID_PAYLOAD`?

2020-07-15 09:43 UTC, obiyankenobi commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.MISSING_PARAMETER, parameter: 'xpubkey' }),
Maybe `INVALID_PAYLOAD` again?

2020-07-15 09:45 UTC, obiyankenobi commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
We have to debate what's our goal. I'd say most use cases are ok with 20 and if they need more, they could run their own service. Or even get in touch with us and we can increase the limit manually.

2020-07-15 09:46 UTC, obiyankenobi commented on src/api/wallet.ts
> +    FunctionName: `${process.env.SERVICE_NAME}-${process.env.STAGE}-loadWalletAsync`,
Because it has to run async. There's no way to send a success message to the user and keep loading the wallet in this same function.

2020-07-15 09:47 UTC, obiyankenobi commented on src/db.ts
> +import { strict as assert } from 'assert';
What's your suggestion for splitting it?

2020-07-15 09:48 UTC, obiyankenobi commented on src/db.ts
> +      // balance as (tokenBalance < 0 ? 0 : tokenBalance). In case the balance is negative, there
When I send tokens to another wallet. My wallet's balance in that tx will be negative.

2020-07-15 09:49 UTC, obiyankenobi commented on src/txProcessor.ts
> +  if (tx.version === 0 || tx.version === 3) {
Ah, I didn't know we had it in the lib. Better to get it from there.

2020-07-15 10:52 UTC, obiyankenobi commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.INVALID_PARAMETER, parameter: 'xpubkey' }),
Just to make it clear, `body` is what the API gateway calls the payload, both for the request and response.

2020-08-03 15:08 UTC, pedroferreira1 commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.INVALID_PARAMETER, parameter: 'xpubkey' }),
Yeah, now I understand what `body` is and I agree `INVALID_PARAMETER` is not really good here. We don't even have a body.

I like `INVALID_PAYLOAD`, as you suggested

2020-08-03 15:08 UTC, pedroferreira1 commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.MISSING_PARAMETER, parameter: 'xpubkey' }),
As in the other comment, now I get what the `body` is. It's ok

2020-08-03 15:12 UTC, pedroferreira1 commented on src/db.ts
> +import { strict as assert } from 'assert';
Address, transaction, token, wallet (core).

2020-08-03 15:15 UTC, pedroferreira1 commented on src/db.ts
> +      // balance as (tokenBalance < 0 ? 0 : tokenBalance). In case the balance is negative, there
Ah okay, you are talking about the tx balance in this line. Just add this in the comment because you start talking about the wallet balance, that can't be negative and that what got me confused.

"on wallet_balance table, balance cannot be negative" and then "In case the balance is negative".

2020-08-03 15:32 UTC, obiyankenobi commented on src/db.ts
> +import { strict as assert } from 'assert';
address and wallet might be useful, are there are some tables for it. But transactions and token might not be useful. Also, there are other functions that don't fall into any of these categories. 

Anyway, I'd prefer to do this refactor in a separate (future) PR:
- there are already 2 other PRs using this as base. If I split this db file, there'll be many conflicts;
- we should investigate using an ORM, as you had suggested. That could also simplify things a lot and make this file much smaller;

2020-08-03 15:33 UTC, obiyankenobi commented on src/db.ts
> +      // balance as (tokenBalance < 0 ? 0 : tokenBalance). In case the balance is negative, there
Ok, I'll improve the comment.

2020-08-04 10:29 UTC, obiyankenobi commented on src/api/wallet.ts
> +export const loadWallet: Handler<LoadEvent, LoadResult> = async (event) => {
I don't like create because it gives me the idea that it's something that will only be done once. As we discussed, in the future, we may remove the wallet from database if it's inactive. And then if it's needed again it'd be "created" a second time. That's why I went with load.

But to be honest, I don't care much about the naming here. We can go with start or create, whatever everyone thinks it's best.

2020-08-04 12:43 UTC, obiyankenobi commented on src/api/addresses.ts
> +  const status = await getWallet(mysql, walletId);
Need to check if status is ready.

2020-08-04 12:44 UTC, obiyankenobi commented on src/api/balances.ts
> +  const status = await getWallet(mysql, walletId);
Need to check if status is ready.

2020-08-04 12:44 UTC, obiyankenobi commented on src/api/txhistory.ts
> +  const status = await getWallet(mysql, walletId);
Need to check if status is ready.

2020-08-04 15:31 UTC, obiyankenobi commented on src/api/txhistory.ts
> +  const history = await getWalletTxHistory(mysql, walletId, tokenId, skip, count);
Actually, do you mean creating a Wallet class so we later can call `wallet.getTxHistory(tokenId, skip, count)`? I'd just be against saving the `mysql` instance in the wallet, so we're basically just repeating `walletId`. But we could do it, so the other APIs would also use it: `wallet.getBalance(mysql, ...)`, `wallet.getAddresses(mysql, ...)`, etc.

2020-08-21 15:01 UTC, jansegre commented on src/api/txhistory.ts
> +// TODO get from lib
Why do we have to get this from the lib? If the value is ever different, it would be a major breaking change, no?

2020-08-21 15:01 UTC, jansegre commented on src/api/txhistory.ts
> +  const history = await getWalletTxHistory(mysql, walletId, tokenId, skip, count);
I'm OK with the code as is. I'm not big fan of trying to abstract too much when a few simple functions are enough.

2020-08-21 15:01 UTC, jansegre commented on DATABASE.md
> +# Database
I second that. I'd prefer an `.sql`, even if only for running locally. And also fixing the database engine to MySQL/MariaDB. Because I don't think we're willing to support an engine that we're not even going to use, and significant differences are bound to come up eventually (for example GitLab dropping support for MySQL).

2020-09-02 14:15 UTC, obiyankenobi commented on src/utils.ts
> +  const xpub = HDPublicKey(xpubkey);
Need to treat bad xpubkeys:
```
Invalid Base58 checksum for xpub6EcBoi2vDFcCW5sPAiQpXDYYtXd1mKhUJD64tUi8CPRG1VQFDkAbL8G5gqTmSZD6oq4Yhr5PZ8pKf3Xmb3W3pGcgqzUdFNaCRKL7TZa3rex
Error: 
    at new NodeError (/Users/yan/dev/hathor/wallet-service/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Function.HDPublicKey.getSerializedError (/Users/yan/dev/hathor/wallet-service/node_modules/bitcore-lib/lib/hdpublickey.js:235:12)
    at new HDPublicKey (/Users/yan/dev/hathor/wallet-service/node_modules/bitcore-lib/lib/hdpublickey.js:42:31)
    at HDPublicKey (/Users/yan/dev/hathor/wallet-service/node_modules/bitcore-lib/lib/hdpublickey.js:38:12)
```

2020-09-02 18:33 UTC, jansegre approved these changes

2020-09-08 20:43 UTC, msbrogli commented on src/api/addresses.ts
> +const mysql = getDbConnection();
Ok. I need to get used to programming lambda handlers. Thanks.

2020-09-08 20:43 UTC, msbrogli commented on src/api/addresses.ts
> +export const get: APIGatewayProxyHandler = async (event) => {
I got it. Thanks!

2020-09-08 20:48 UTC, msbrogli commented on src/api/addresses.ts
> +    await closeDbConnection(mysql);
As far as I understood, we need to always call `closeDbConnection` before this method ends. In this case, shouldn't we use a decorator to do it?

Example:
```js
function closeDbConnectionDecorator(wrapped) {
  return function() {
    try {
        return wrapped.apply(this, arguments);
    } finally {
        closeDbConnection(mysql);
    }
  }
}
```

2020-09-08 20:51 UTC, msbrogli commented on src/api/txhistory.ts
> +  const history = await getWalletTxHistory(mysql, walletId, tokenId, skip, count);
Ok. We can refactor it later if it makes sense.

2020-09-08 20:53 UTC, msbrogli commented on src/api/wallet.ts
> +  status = await createWallet(mysql, walletId, xpubkey, maxGap);
I think so. We can run an insert query and commit. We just need to handle a potential primary key duplication.

2020-09-08 20:54 UTC, msbrogli commented on src/api/wallet.ts
> +    apiVersion: '2015-03-31',
I got it. Maybe move it to a constant?

2020-09-08 20:57 UTC, msbrogli commented on src/api/wallet.ts
> +export const loadWallet: Handler<LoadEvent, LoadResult> = async (event) => {
I feel that "you cannot load something that hasn't been created before". But I understand your points as well. Maybe we should just improve the documentation to explain what you just said.

2020-09-08 21:18 UTC, msbrogli requested changes

2020-09-08 21:18 UTC, msbrogli commented on src/db.ts
> +  for (const [address, index] of Object.entries(addresses)) {
What if only one address has been added? Will we update all other addresses of that wallet?

2020-09-08 21:18 UTC, msbrogli commented on src/db.ts
> +export const initWalletBalance = async (mysql: ServerlessMysql, walletId: string, addresses: string[]): Promise<void> => {
Maybe we should add a lock per `walletId` here to prevent race conditions.

2020-09-08 21:18 UTC, msbrogli commented on src/db.ts
> +export const updateWalletTablesWithTx = async (
Double check if we need to add a lock here.

2020-09-08 21:18 UTC, msbrogli commented on src/db.ts
> +      'SELECT * FROM `utxo` WHERE `heightlock` = ? AND (timelock <= ? OR timelock is NULL)',
Shouldn't it be `heightlock > [height]`?

2020-09-08 21:18 UTC, msbrogli commented on src/txProcessor.ts
> +  // TODO delete message from queue
What does SQS do to prevent sending the same message to two consumers?

2020-09-14 15:55 UTC, obiyankenobi commented on src/db.ts
> +  for (const [address, index] of Object.entries(addresses)) {
I'm not sure I understood your questions.

This function only updates the index and walletId in the address table. There's no logic here, it's up to the calling function to determine which addresses will be updated. This function is called when creating the wallet, so existing addresses get marked as being part of a wallet.

2020-09-15 14:04 UTC, obiyankenobi commented on src/db.ts
> +export const initWalletBalance = async (mysql: ServerlessMysql, walletId: string, addresses: string[]): Promise<void> => {
Adding locks on lambda functions is not easy to do. Anyway, this function will try to do an insert on `wallet_balance`. If it's been already added, it will fail on a repeated primary key. So treating the database error should handle the problem.

2020-09-15 15:07 UTC, obiyankenobi commented on src/db.ts
> +      'SELECT * FROM `utxo` WHERE `heightlock` = ? AND (timelock <= ? OR timelock is NULL)',
I can review the logic behind it, but the docstring clearly states it only gets the blocks locked at the specific height.

2020-09-15 15:09 UTC, obiyankenobi commented on src/txProcessor.ts
> +  // TODO delete message from queue
https://aws.amazon.com/sqs/features/#Queue_types

We should us FIFO queues.

2020-09-16 18:02 UTC, obiyankenobi commented on DATABASE.md
> +# Database
Included `db.sql`.

2020-09-16 18:02 UTC, obiyankenobi commented on README.md
> +The hathor-wallet-service is the backend for all official Hathor wallets. It's highly inspired in the [Bitcore Wallet
Done

2020-09-16 18:02 UTC, obiyankenobi commented on fullnode-bridge.js
> +/* eslint-disable */
Done

2020-09-16 18:02 UTC, obiyankenobi commented on src/api/txhistory.ts
> +// TODO get from lib
Getting it from the lib anyway, since it's easy.

2020-09-16 18:09 UTC, obiyankenobi commented on src/api/wallet.ts
> +    apiVersion: '2015-03-31',
Added as a constant on this same file, as it's only used here. If we later use in other places, we can move to a constants file.

2020-09-16 18:09 UTC, obiyankenobi commented on src/api/wallet.ts
> +export const loadWallet: Handler<LoadEvent, LoadResult> = async (event) => {
Renamed to `createWallet`.

2020-09-16 18:11 UTC, obiyankenobi commented on src/api/addresses.ts
> +    return {
I created a helper method `closeDbAndGetError`, so now it's easier. But that only sends errors. For success responses, since it's only done once in each API, I kept the more verbose code. This way, the helper function can be specific to errors.

2020-09-16 18:11 UTC, obiyankenobi commented on src/api/wallet.ts
> +      body: JSON.stringify({ success: false, error: ApiError.INVALID_PARAMETER, parameter: 'xpubkey' }),
Done

2020-09-16 18:11 UTC, obiyankenobi commented on src/db.ts
> +      // balance as (tokenBalance < 0 ? 0 : tokenBalance). In case the balance is negative, there
Done

2020-09-16 18:13 UTC, obiyankenobi commented on src/txProcessor.ts
> +  if (tx.version === 0 || tx.version === 3) {
Done

2020-09-16 18:13 UTC, obiyankenobi commented on src/api/addresses.ts
> +  const status = await getWallet(mysql, walletId);
Done

2020-09-16 18:14 UTC, obiyankenobi commented on src/api/balances.ts
> +  const status = await getWallet(mysql, walletId);
Done

2020-09-16 18:14 UTC, obiyankenobi commented on src/api/txhistory.ts
> +  const status = await getWallet(mysql, walletId);
Done

2020-09-16 18:14 UTC, obiyankenobi commented on src/utils.ts
> +  const xpub = HDPublicKey(xpubkey);
This code was moved to the lib and already handles this.

2020-09-16 18:16 UTC, obiyankenobi commented on src/api/addresses.ts
> +    await closeDbConnection(mysql);
I created a helper method to close the connection and get the error reply (`closeDbAndGetError`), so the code is cleaner now. What do you think?

2020-09-17 10:46 UTC, obiyankenobi commented on src/db.ts
> +export const updateWalletTablesWithTx = async (
No need to do it, as long as tx is processed once.

2020-09-17 11:05 UTC, obiyankenobi commented on src/api/wallet.ts
> +    // TODO handle
Now I also update the status of the wallet on db to `error` and also return `success: false`. Regarding logging, I'm not sure where it would end up when using lambdas. I need to look into this when testing on the real environment.

2020-09-17 11:08 UTC, obiyankenobi commented on src/api/wallet.ts
> +  status = await createWallet(mysql, walletId, xpubkey, maxGap);
Yeah, handling the db error should be fine.

2020-09-28 22:14 UTC, pedroferreira1 commented on src/db.ts
> +import { strict as assert } from 'assert';
About token and transaction not being useful I agree with this code, however with future implementations of the next features maybe it will (at least transaction). But I agree with you that could be done in a different PR, just create this issue to separate this file because it's already confusing with the current code and might become worse with to next changes.

2020-09-28 22:15 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  const maxGap = parseInt(process.env.MAX_ADDRESS_GAP, 10);
Yeah, we can discuss the specific cases when they come to us in the future, it's ok for now.

2020-09-28 22:18 UTC, pedroferreira1 commented on package.json
> +  "license": "MIT",
I think we should create the LICENSE file also, right? And also add the header in all code files. Just to follow what we've been using in all other repositories.

2020-09-28 22:18 UTC, pedroferreira1 approved these changes

2020-10-01 08:20 UTC, msbrogli commented on src/api/wallet.ts
> +    // TODO handle
That's something really important to check, and also how to monitor this service.

2020-10-01 08:22 UTC, msbrogli commented on src/txProcessor.ts
> +  // TODO delete message from queue
Thanks!

2020-10-01 08:22 UTC, msbrogli commented on src/db.ts
> +export const initWalletBalance = async (mysql: ServerlessMysql, walletId: string, addresses: string[]): Promise<void> => {
Ok. Thanks!

2020-10-01 08:23 UTC, msbrogli commented on src/db.ts
> +      'SELECT * FROM `utxo` WHERE `heightlock` = ? AND (timelock <= ? OR timelock is NULL)',
Ok! Thanks.

2020-10-01 08:24 UTC, msbrogli commented on src/api/addresses.ts
> +    await closeDbConnection(mysql);
It is good. Thanks!

2020-10-01 08:25 UTC, msbrogli commented on src/db.ts
> +  for (const [address, index] of Object.entries(addresses)) {
I'm trying to figure out if it will loop over all addresses of the wallet or not.

2020-10-01 08:25 UTC, msbrogli approved these changes

2020-10-01 15:05 UTC, obiyankenobi commented on src/db.ts
> +  for (const [address, index] of Object.entries(addresses)) {
It will loop over the addresses passed on the `addresses` parameter. That, in turn, is calculated on:
`const { addresses, existingAddresses, newAddresses } = await generateAddresses(mysql, xpubkey, maxGap);`

2020-10-01 15:05 UTC, obiyankenobi commented on package.json
> +  "license": "MIT",
That's true, forgot about it.

2020-10-01 15:07 UTC, obiyankenobi commented on src/db.ts
> +import { strict as assert } from 'assert';
There's already a task in the Epic to revisit the db code and support transactions/commits. I think that'll be the best PR to do it.

2020-10-05 10:32 UTC, obiyankenobi commented on package.json
> +  "license": "MIT",
Done

2020-10-06 09:25 UTC, merged