chore: missing env variables
HathorNetwork/hathor-wallet-service-old pull request #402
Opened 2023-02-28 15:50 UTC by andreabadesso

### Acceptance Criteria
- Added the `LOG_LEVEL` and `ALERT_QUEUE_URL` variables on deploy

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-03-01 14:07 UTC, andreabadesso commented on src/utils/alerting.utils.ts
> +  await new Promise<void>((resolve) => {
During tests I noticed that sometimes the lambda would end causing the alert to never be sent

2023-03-01 14:54 UTC, tuliomir approved these changes

2023-03-01 14:54 UTC, tuliomir commented on src/utils/alerting.utils.ts
> +  await new Promise<void>((resolve) => {
I suggest adding a comment to explain this promise on the code, just like you did here on the PR.

That way, future developers will understand why not to simplify the code by removing the seemingly unnecessary promise.

2023-03-01 21:44 UTC, alexruzenhack commented on .github/workflows/pr-validation.yml
> +          ACCOUNT_ID: 1
I couldn't find the `ACCOUNT_ID` reference on `.codebuild/buildspec.yml`, or on `serverless.yml`.

2023-03-01 21:55 UTC, alexruzenhack requested changes
Laking `ACCOUNT_ID` declaration on `buildspec.yml` and `serverless.yml`

2023-03-01 21:55 UTC, alexruzenhack commented on .github/workflows/pr-validation.yml
> +          ACCOUNT_ID: 1
I couldn't find the `ACCOUNT_ID` reference on `.codebuild/buildspec.yml`, or on `serverless.yml`.

2023-03-01 21:55 UTC, alexruzenhack commented on .github/workflows/pr-validation.yml
> +          ALERT_MANAGER_TOPIC: alert-manager-void
Can we add this to `.env.example`?

2023-03-01 22:02 UTC, alexruzenhack approved these changes

2023-03-01 22:03 UTC, alexruzenhack commented on .github/workflows/pr-validation.yml
> +          ACCOUNT_ID: 1
It is already declared.

2023-03-03 14:52 UTC, andreabadesso commented on src/utils/alerting.utils.ts
> +  await new Promise<void>((resolve) => {
I think this is kind of implicit, it was an error before for the `addAlert` to be async but leak this callback after it resolves, right?

Adding a comment there would be like:

"This async method is really async because we are returning a promise"

2023-03-03 14:56 UTC, andreabadesso commented on .github/workflows/pr-validation.yml
> +          ALERT_MANAGER_TOPIC: alert-manager-void
We didn't have one, but added in 3828dff6340d798119364aae45c970cffff6b9ed

2023-03-03 16:49 UTC, merged