feat: return address path in tx proposal create
HathorNetwork/hathor-wallet-service-old pull request #44
Opened 2021-03-15 18:53 UTC by pedroferreira1

2021-03-15 19:09 UTC, msbrogli requested changes

2021-03-15 19:09 UTC, msbrogli commented on tests/integration.test.ts
> +}, 60000);
Why did you increase the timeout?

2021-03-15 19:09 UTC, msbrogli commented on src/db.ts
> + * @returns The details of the address {address, index, transactions}
`... or null if not found`.

2021-03-15 19:09 UTC, msbrogli commented on DATABASE.md
> -CREATE TABLE `token` (
Why did you delete it?

2021-03-15 19:21 UTC, pedroferreira1 commented on tests/integration.test.ts
> +}, 60000);
I increased just to pass the tests. Before the changes this test was almost getting timeout in my machine. With the changes, I believe because of the db access, it was getting timeout eventually. We already have an issue to add indexes in the db and understand why it's a bit slow to execute queries.

2021-03-15 19:22 UTC, pedroferreira1 commented on DATABASE.md
> -CREATE TABLE `token` (
It was duplicated in this file.

2021-03-16 18:07 UTC, andreabadesso approved these changes

2021-03-16 21:02 UTC, msbrogli commented on tests/integration.test.ts
> +}, 60000);
Is it close to timeout with 30 seconds?

2021-03-16 21:03 UTC, msbrogli commented on DATABASE.md
> -CREATE TABLE `token` (
Ok. Thanks!

2021-03-16 21:17 UTC, pedroferreira1 commented on tests/integration.test.ts
> +}, 60000);
Yes, I agree. That's why we have an issue to understand some queries slowness. @andreabadesso already said that sharing the mysql connection might be a problem but still need to investigate.

2021-03-17 00:22 UTC, msbrogli commented on tests/integration.test.ts
> +}, 60000);
Ok. We can do it now but I think we should open an issue to reduce these timeouts to just a few seconds (or even less).

2021-03-17 00:22 UTC, msbrogli approved these changes

2021-03-17 17:15 UTC, merged