feat: add validation for wallet start to check first wallet address
HathorNetwork/hathor-wallet-service-old pull request #49
Opened 2021-03-24 22:58 UTC by pedroferreira1

2021-03-25 08:11 UTC, msbrogli requested changes

2021-03-25 08:11 UTC, msbrogli commented on src/api/wallet.ts
> +  address0: Joi.string()
I called it `firstAddress` in hathor-wallet-headless. Should we use the same name here?

2021-03-25 08:11 UTC, msbrogli commented on src/api/wallet.ts
> +  const address0 = hathorLib.walletUtils.getAddressAtIndex(xpubkey, 0, 0, 'mainnet');
We should get the network from config, right?

2021-03-25 08:11 UTC, msbrogli commented on src/api/wallet.ts
> +  const address0 = hathorLib.walletUtils.getAddressAtIndex(xpubkey, 0, 0, 'mainnet');
Maybe we should make it optional in the config file. What do you think?

2021-03-25 14:26 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  const address0 = hathorLib.walletUtils.getAddressAtIndex(xpubkey, 0, 0, 'mainnet');
Yes, done

2021-03-25 15:44 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  address0: Joi.string()
Makes sense, changed.

2021-03-25 16:38 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  const address0 = hathorLib.walletUtils.getAddressAtIndex(xpubkey, 0, 0, 'mainnet');
Makes sense, done

2021-03-25 17:37 UTC, msbrogli approved these changes

2021-03-30 02:48 UTC, msbrogli approved these changes

2021-03-30 16:32 UTC, andreabadesso requested changes

2021-03-30 16:32 UTC, andreabadesso commented on src/api/wallet.ts
> +  firstAddress: Joi.string(),
When `process.env.CONFIRM_FIRST_ADDRESS` is `'true'`, shouldn't `firstAddress` be required?

2021-04-06 14:45 UTC, pedroferreira1 commented on src/api/wallet.ts
> +  firstAddress: Joi.string(),
Done. Can you see if it's good?

2021-04-06 15:09 UTC, andreabadesso commented on src/api/wallet.ts
> +  firstAddress: Joi.string(),
LGTM

![](https://media3.giphy.com/media/KWRjfFe4x7nwyh9GlX/giphy.gif)

2021-04-06 15:10 UTC, andreabadesso approved these changes

2021-04-06 15:11 UTC, merged