feat: handle timelock
HathorNetwork/hathor-wallet-service-old pull request #6
Opened 2020-07-20 14:40 UTC by obiyankenobi

2020-10-07 16:31 UTC, pedroferreira1 requested changes

2020-10-07 16:31 UTC, pedroferreira1 commented on DATABASE.md
> +CREATE TABLE `info` (
What's this table used for?

2020-10-07 16:31 UTC, pedroferreira1 commented on tests/utils.ts
> +export const createInput = (value: number, address: string, txId: string, index: number, token = '00', timelock = null, locked = false, tokenData = 0): TxInput => (
Why do we have a `locked` field on the input?

2020-10-07 16:31 UTC, pedroferreira1 commented on tests/utils.ts
> +    `${baseQuery} AND timelock_expires ${lockExpires === null ? 'IS' : '='} ?`,
All other queries the parameters are between ``, shouldn't timelock_expires also be between ``?

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +        [entry, tokenBalance.unlocked, tokenBalance.locked, walletId, token],
In this query I see only 3 '?', which I believe are the markers for escaping vars. Why do we have 5 elements on the array?

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +  const entries = inputs.map((input) => [input.tx_id, input.index]);
I think we should try to be consistent with the names. Here we have `input.tx_id` and right above we have `utxo.txId`

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +export const getTxLockedInputs = async (mysql: ServerlessMysql, inputs: TxInput[]): Promise<Utxo[]> => {
This method returns the locked utxos not the locked inputs. I think this name is misleading maybe it could be `getLockedUtxoFromInputs` don't know if it's good but I think is better.

Even the first line of the comment is saying "Get tx inputs that are still marked as locked."

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +        [entry, tokenBalance.unlocked, tokenBalance.locked, address, token],
Again the same comment about the  5 parameters with 3 '?'. Only to mark if there is a problem in the other, this should be changed also.

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +          'UPDATE `address_balance` SET `timelock_expires` = (SELECT MIN(`timelock`) FROM `utxo` WHERE `address` = ? AND `token_id` = ? AND `locked` = TRUE)',
When the utxo is locked because of a heightlock and not a timelock, we shouldn't consider it on the SELECT, right? 

Besides that, if we have no more locked utxos should we also update the `timelock_expires` to `null`?

2020-10-07 16:31 UTC, pedroferreira1 commented on src/db.ts
> +          'UPDATE `wallet_balance` SET `timelock_expires` = (SELECT MIN(`timelock_expires`) FROM `address_balance` WHERE `address` IN (SELECT `address` from `address` WHERE `wallet_id` = ?) AND `toke
What happens with the `MIN` operator with `null` values and integer values?

2020-10-07 16:31 UTC, pedroferreira1 commented on DATABASE.md
> +CREATE TABLE `info` (
For what I've seen is used to save the current height, right? Or something else also?
Maybe we should update the Design to add it, I tried to find there and that's why I added this first comment.

2020-10-14 19:30 UTC, jansegre approved these changes

2020-10-14 19:30 UTC, jansegre commented on DATABASE.md
> +CREATE TABLE `info` (
Yeah, I also think the name is too generic. Would `lock_info` or `metadata` describe it better? I'm not really sure what it's used for.

2020-10-14 19:30 UTC, jansegre commented on src/db.ts
> +  const entries = inputs.map((input) => [input.tx_id, input.index]);
I agree with consistency. But I get that these differences may come from exposing (or consuming) an API that uses a different naming pattern.

2020-11-27 20:30 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `info` (
I believe the idea is to have a generic key-value store in the database to persist data

For now the only info stored is the current height

I agree that `metadata` would describe it better though

2020-11-27 20:30 UTC, andreabadesso commented on src/db.ts
> +        [entry, tokenBalance.unlocked, tokenBalance.locked, walletId, token],
This was probably left there after the query was refactored

Removed it.

2020-11-27 20:30 UTC, andreabadesso commented on src/db.ts
> +export const getTxLockedInputs = async (mysql: ServerlessMysql, inputs: TxInput[]): Promise<Utxo[]> => {
Agreed, replaced `getTxLockedInputs` with `getLockedUtxoFromInputs`

2020-11-27 20:30 UTC, andreabadesso commented on src/db.ts
> +  const entries = inputs.map((input) => [input.tx_id, input.index]);
I also agree with the consistency but as there are several places mixing camelCase and snake_case, I suggest creating new issue to deal with this normalization and convert everything to camelCase as that is the usual casing for javascript

2020-11-27 20:30 UTC, andreabadesso commented on src/db.ts
> +        [entry, tokenBalance.unlocked, tokenBalance.locked, address, token],
Fixed

2020-11-27 20:30 UTC, andreabadesso commented on src/db.ts
> +          'UPDATE `wallet_balance` SET `timelock_expires` = (SELECT MIN(`timelock_expires`) FROM `address_balance` WHERE `address` IN (SELECT `address` from `address` WHERE `wallet_id` = ?) AND `toke
It will return the MIN integer value if there is at least one non-null value and NULL otherwise

2020-11-27 20:30 UTC, andreabadesso commented on tests/utils.ts
> +export const createInput = (value: number, address: string, txId: string, index: number, token = '00', timelock = null, locked = false, tokenData = 0): TxInput => (
Maybe the idea was to have locked here to test the condition we have on the `getLockedUtxoFromInputs` method (```We have a "lazy" unlock policy so we might receive a transaction with a UTXO that is still marked as locked in our database```)

But since it is not being used anywhere on the tests, I removed it.

2020-11-27 20:30 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `info` (
Updated on ec887d6c606aeadb3e03b90ed86288dcb89e5745

2020-11-27 20:30 UTC, andreabadesso commented on tests/utils.ts
> +    `${baseQuery} AND timelock_expires ${lockExpires === null ? 'IS' : '='} ?`,
The `value` of `timelock_expires` is using `?`, only the operation is using js template strings, so we can use `IS NULL` instead of `= NULL`

This will be refactored when we add an ORM or a QueryBuilder, I suggest not changing it on this PR

2020-11-27 20:39 UTC, obiyankenobi commented on src/db.ts
> +  const entries = inputs.map((input) => [input.tx_id, input.index]);
I used camelCase for this code, but the tx object we get from the fullnode uses snake_case.

2020-11-27 22:05 UTC, andreabadesso commented on src/db.ts
> +          'UPDATE `address_balance` SET `timelock_expires` = (SELECT MIN(`timelock`) FROM `utxo` WHERE `address` = ? AND `token_id` = ? AND `locked` = TRUE)',
> When the utxo is locked because of a heightlock and not a timelock, we shouldn't consider it on the SELECT, right?

This function (`updateAddressLockedBalance`) is called on two situations:
1) When a new block arrives, so it will unlock UTXOs from height-locked blocks. In this case, `updateTimeLocks` will be set to false
2) When there are locked inputs (queried from `getLockedUtxoFromInputs`)

Both calls are made from [`addNewTx`](https://github.com/HathorNetwork/hathor-wallet-service/blob/ec887d6c606aeadb3e03b90ed86288dcb89e5745/src/txProcessor.ts#L83)

On case (1), we would also get height-locked inputs because we use the same `locked` column for locked inputs (wether they are locked because of time, height or being used in a tx-proposal). But that shouldn't matter because the query is only updating `address_balance`, so height-blocked inputs with no timelock would receive `NULL`.

That's the query returning the closest timelock expire:

`SELECT MIN(timelock) FROM utxo WHERE address = ? AND token_id = ? AND locked = TRUE`

There are two possible outcomes of that:

1) There is at least one "valid" timelock in any of the UTXOs, so it will return the closest.
2) There are no more valid timelocks, so it will return `NULL`

> Besides that, if we have no more locked utxos should we also update the timelock_expires to null?

That's exactly what the outcome (2) is doing.

2020-12-07 12:00 UTC, obiyankenobi reviewed
Looks good to me.

2020-12-07 15:13 UTC, pedroferreira1 approved these changes

2020-12-09 17:44 UTC, jansegre approved these changes

2021-01-27 09:25 UTC, msbrogli requested changes

2021-01-27 09:25 UTC, msbrogli commented on src/api/balances.ts
> +    await updateBalances(mysql, walletId, now);
Can't we just update the balance of the `tb`s which lock has expired (instead of updating the whole wallet balance)?

2021-01-27 09:25 UTC, msbrogli commented on src/api/balances.ts
> +const updateBalances = async (_mysql: ServerlessMysql, walletId: string, now: number) => {
Missing docstring.

2021-01-27 09:25 UTC, msbrogli commented on src/db.ts
> +          AND \`locked\` = TRUE`,
I know mysql accepts `TRUE` and `FALSE` but isn't it better to use `1` here? I'd say it will clearly show that `locked` is a numeric field and justify the `result.locked > 0` below.

2021-01-27 09:25 UTC, msbrogli commented on src/db.ts
> +        AND \`locked\` = TRUE
Same here. Replace `TRUE` by `1`.

2021-01-27 09:25 UTC, msbrogli commented on src/types.ts
> +    if (b1.lockExpires === null) {
Isn't it easier to use `0` or `-1` instead of `null`? I feel it would prevent a lot of verifications.

2021-01-27 09:25 UTC, msbrogli commented on tests/api.test.ts
> +  await addToWalletBalanceTable(mysql, [['my-wallet', 'token1', 10, 0, null, 3]]);
I feel the method should receive an object and internally map it to an array. The way it is seems very error prone. What do you think?

2021-01-27 09:25 UTC, msbrogli commented on tests/db.test.ts
> +    ['addr1', 0, walletId, 1],
Don't you think this is hard to read (and too error prone when one is using it)?

2021-02-03 17:41 UTC, andreabadesso commented on src/types.ts
> +    if (b1.lockExpires === null) {
It would indeed prevent some verifications but I would argue that using null is more "semantically correct", meaning that it does not have an expiration time as oposed to "it does have an expiration time but it already elapsed". What do you think?

2021-02-03 17:46 UTC, andreabadesso commented on src/api/balances.ts
> +    await updateBalances(mysql, walletId, now);
I don't know if I understood your question correctly

`updateBalances` only updates the UTXOs that are currently locked and should be unlocked on the current height

2021-02-03 19:57 UTC, andreabadesso commented on tests/api.test.ts
> +  await addToWalletBalanceTable(mysql, [['my-wallet', 'token1', 10, 0, null, 3]]);
I agree. Refactored it

2021-02-03 19:57 UTC, andreabadesso commented on tests/db.test.ts
> +    ['addr1', 0, walletId, 1],
I agree. Refactored it

2021-02-05 00:22 UTC, msbrogli commented on src/types.ts
> +    if (b1.lockExpires === null) {
Makes sense. I agree. Thanks!

2021-02-05 00:26 UTC, msbrogli approved these changes

2021-02-05 00:26 UTC, msbrogli commented on src/api/balances.ts
> +    await updateBalances(mysql, walletId, now);
Ok. I got it.  But why are we verifying above whether there's any `tb` to be refreshed or not? Isn't it as simple as calling `updateBalances()`? Or add an option so the `getWalletBalances` also refresh locks?

2021-02-05 00:31 UTC, msbrogli approved these changes

2021-02-05 00:31 UTC, msbrogli commented on tests/api.test.ts
> +  await addToWalletBalanceTable(mysql, [{
![image](https://user-images.githubusercontent.com/449119/106972784-6bbdd600-6706-11eb-817c-d70526205106.png)

2021-02-08 20:41 UTC, merged