feat: token actions implementation
HathorNetwork/hathor-wallet-service-old pull request #61
Opened 2021-04-20 15:17 UTC by andreabadesso

2021-05-11 16:02 UTC, pedroferreira1 requested changes

2021-05-11 16:02 UTC, pedroferreira1 commented on DATABASE.md
> +  `token_id` varchar(64) DEFAULT NULL,
Why this is default null now? We always have a `token_id`, right? Or the token creation outputs you are not setting the token id?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +}).unknown(true);
What's this unknown?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +export const createTxSchema = Joi.object({
We should have `changeAddress` here as well, right?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +          .alphanum(),
The default is optional or required?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +  amount: Joi.number().required(),
Add `.posivite()` and `.integer()`?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +  amount: Joi.number().required().min(1),
Maybe we should have all amount fields with the same definition. I feel it's better to have as you defined the first output amount (`.integer().positive()`). What do you think?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/schemas.ts
> +  amount: Joi.number().required().min(1),
Same comment about amount.

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalSend.ts
> +  if (txProposal.type === TokenActionType.CREATE_TOKEN) {
Maybe add a comment here explaining that a create token transaction does not have the tokens array and has a specific version and name/symbol as custom fields.

2021-05-11 16:02 UTC, pedroferreira1 commented on src/db.ts
> +  quantity = 1,
Missing `:number` or typescript infers from the default value?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/types.ts
> +export interface CreateTxBody extends BaseTxBody {
Should we add `changeAddress`?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  }());
Shouldn't we add below here this validation?

```
  if (!inputSelectionAlgo) {
    return closeDbAndGetError(mysql, ApiError.INVALID_SELECTION_ALGORITHM);
  }
```

I think at least all validations could be refactored in a single place.

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  // Create the deposit change without creating an deposit output
a* deposit

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  const inputPromises = inputUtxos.map(async (utxo) => {
This also could be a separate method.

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  if ((htrInputBalance.unlockedAmount * -1) < necessaryDepositAmount) {
Why do you need to do it? `unlockedAmount` is negative?

Isn't it enough just `if necessaryDepositAmount  > htrInputBalance.unlockedAmount`?

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  if ((tokenInputBalance.unlockedAmount * -1) < body.amount) {
Same question as in the mint.

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  for (let i = 0; i < body.amount; i++) {
I think I've missed this `amount` parameter in delegate authorities in the design. I am not sure we should have it, I believe should always be 1. Maybe we could have the parameter but as optional and the default could be 1

2021-05-11 16:02 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +  if (authorities.length > 1) {
The destroy we have the quantity, then it's possible to destroy more than one in a request, doesn't it?

2021-05-11 19:09 UTC, andreabadesso commented on DATABASE.md
> +  `token_id` varchar(64) DEFAULT NULL,
Exactly. Token create actions will not have the token id yet

2021-05-11 19:11 UTC, andreabadesso commented on src/api/schemas.ts
> +}).unknown(true);
`unknown` will allow for more attributes other than the ones defined in the schema without failing

2021-05-11 19:11 UTC, andreabadesso commented on src/api/schemas.ts
> +          .alphanum(),
Default is optional

2021-05-11 19:12 UTC, andreabadesso commented on src/db.ts
> +  quantity = 1,
Typescript infers from the default value and will not allow me to set `:number` if I'm providing a default value

2021-05-14 06:53 UTC, msbrogli requested changes

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +}).unknown(true);
Why would we accept an unknown type?

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +      Joi.object({
Should we support non-standard scripts? Maybe in a future release?

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +  version: Joi.number()
Why would we allow user to change the version?

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +  amount: Joi.number().required().min(1),
Can't we create a `const JoiTxInputAmount = Joi.number().required().integer().min(1)`?

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +export const createTokenSchema = Joi.object({
Brainstorm: Isn't it better to receive a serialized transaction and just sign the known inputs? I feel it would simplify the whole API and be much more flexible. We can create validation rules after parsing the serialized tx if we need to.

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +  version: Joi.number()
Why would we allow user to change the version?

2021-05-14 06:53 UTC, msbrogli commented on src/api/schemas.ts
> +  version: Joi.number()
Why would we allow user to change the version?

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +      return closeDbAndGetError(mysql, ApiError.INPUTS_ALREADY_USED);
Maybe `INPUTS_ALREADY_PROVISIONED`? The word used gives the feeling that it has already been spent so it would be a double spending.

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    for (const [tokenId, tokenBalance] of outputsBalance.iterator()) {
What if the inputs sent by the user are not enough? Should we generate an error or complete with more inputs?

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +      const destinationAddresses = await getUnusedAddresses(mysql, walletId);
Maybe create a `getChangeAddress()`? In the initial implementation, it can be a direct call to `getUnusedAddresses()` just like here.

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +    const addressPath = `m/44'/${hathorLib.constants.HATHOR_BIP44_CODE}'/0'/0/${addressDetail.index}`;
I agree it should be in the address table. For now, we should at least move to a separate method (e.g. `generateAddressPath()`).

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  }());
I agree with the refactor. It seems this piece of code has been duplicated several times.

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +  // If inputs were sent, we must validate if they are enough for the amount of tokens we want to create.
This code seems equal to the code above. Maybe we should find a better way. What about a `fillTxInputs()` or `verifyManualInputs()` method?

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +        // TODO: Make sure we are not already using this address on change outputs
Pending TODO item.

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +        // TODO: Make sure we are not already using this address on change outputs
Pending TODO item.

2021-05-14 06:53 UTC, msbrogli commented on src/api/txProposalCreate.ts
> +enum InputSelectionAlgo {
**This comment is not related to the place I put it.**

Shouldn't we simplify and receive a serialized transaction with some instructions such as "fill inputs"? I feel the code is too complicated because there are too many possible cases. @andreabadesso @pedroferreira1

2021-05-14 14:17 UTC, pedroferreira1 commented on src/api/txProposalCreate.ts
> +enum InputSelectionAlgo {
I am thinking about how this would make the code simpler. We would still need to have the code to select the inputs, change output and tx validation, which are the main reasons for code complexity, isn't it?

2021-08-17 18:50 UTC, closed without merging