fix: added a 'ignore list' of transactions including the genesis txs
HathorNetwork/hathor-wallet-service-old pull request #62
Opened 2021-04-27 17:45 UTC by andreabadesso

We could extend this to ignore other transactions, maybe have a list of transactions to ignore on an env variable but I think that this should be enough for the transactions on the `testnet` and `mainnet` as they won't ever change

2021-04-27 18:15 UTC, pedroferreira1 approved these changes

2021-04-27 18:15 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  // we should ignore genesis transactions as they have no parents, inputs and outputs
The genesis blocks have the premine outputs. If you are adding this output in the database in another way we should at least make it clear here.

2021-04-27 18:31 UTC, andreabadesso commented on src/txProcessor.ts
> +  // we should ignore genesis transactions as they have no parents, inputs and outputs
Improved the commend to explain that genesis txs and pre-mined outputs should be already in the database when the service starts.

2021-04-30 20:55 UTC, msbrogli requested changes

2021-04-30 20:55 UTC, msbrogli commented on src/txProcessor.ts
> +export const IGNORE_TXS = {
I think we should use this PR to update the README with the explanation about the genesis and also add the scripts to add the genesis transactions to the database.

2021-05-04 15:45 UTC, andreabadesso commented on src/txProcessor.ts
> +export const IGNORE_TXS = {
Done in 5a06691b84ba7e99aeccce7f39e1d6f08da9a342

I added the inserts to add the genesis block to the database and the UTXO with the pre-mined tokens

2021-05-04 18:29 UTC, msbrogli commented on src/txProcessor.ts
> +export const IGNORE_TXS = {
Ok. Thanks!

2021-05-04 18:29 UTC, msbrogli approved these changes

2021-05-04 19:58 UTC, merged