feature: authorization
HathorNetwork/hathor-wallet-service-old pull request #69
Opened 2021-05-12 19:33 UTC by r4mmer

2021-05-26 17:47 UTC, andreabadesso requested changes

2021-05-26 17:47 UTC, andreabadesso commented on AUTHENTICATION.md
> +// TODO: list all protected views
TODO

2021-05-26 17:47 UTC, andreabadesso commented on src/api/auth.ts
> +  ts: Joi.number().required(),
Maybe use https://joi.dev/api/?v=17.4.0#datetimestamptype

2021-05-26 17:47 UTC, andreabadesso commented on src/api/auth.ts
> +    const details = {
Maybe use:

```
const details = [{
    message: `...`
}]
```

To be consistent with the txProposalCreate API that returns a list of details on error

2021-05-26 17:47 UTC, andreabadesso commented on src/api/auth.ts
> +type Dictionary<T> = { [s: string]: T };
Move this to the `types.ts` file?

2021-05-26 17:47 UTC, andreabadesso commented on src/api/errors.ts
> +  INVALID_SIGNATURE = 'invalid-signature',
Maybe use `AUTH_INVALID_SIGNATURE = 'invalid-auth-signature'` to distinguish it from a invalid input signature on `txProposalSend`

2021-05-26 17:47 UTC, andreabadesso commented on src/api/auth.ts
> +      // jwtId: // generate or accept?
I think this is necessary to be able to blacklist JWT tokens in the future and I think we should generate it

Maybe for now, just generate a random UUID

I don't think we have an use for the other options yet

2021-05-28 13:21 UTC, r4mmer commented on src/api/auth.ts
> +  ts: Joi.number().required(),
This converts the timestamp value to a `Date`, here we are looking for the actual number value for the message.

2021-05-28 13:22 UTC, r4mmer commented on src/api/auth.ts
> +    const details = {
Done.

2021-05-28 13:40 UTC, r4mmer commented on src/api/auth.ts
> +type Dictionary<T> = { [s: string]: T };
This was to prevent a bug on serverless offline (if the context wasn't typed str to str dict it wasn't passed to the function), but i double checked and it was fixed, so i'm removing this.

2021-05-28 13:43 UTC, r4mmer commented on src/api/errors.ts
> +  INVALID_SIGNATURE = 'invalid-signature',
Done.

2021-05-28 13:47 UTC, r4mmer commented on src/api/auth.ts
> +      // jwtId: // generate or accept?
Ok

2021-05-28 15:13 UTC, andreabadesso approved these changes

2021-05-31 16:17 UTC, pedroferreira1 requested changes

2021-05-31 16:17 UTC, pedroferreira1 commented on package.json
> +    "@hathor/wallet-lib": "^0.19.0",
You will need the next version, right? The one with the open lib PR.

2021-05-31 16:17 UTC, pedroferreira1 commented on src/api/auth.ts
> +  ts: Joi.number().required(),
Maybe a bit too much but we can add `.number().positive().required()`

2021-05-31 16:17 UTC, pedroferreira1 commented on src/api/auth.ts
> +// import { closeDbAndGetError } from '@src/api/utils';
Remove?

2021-05-31 16:17 UTC, pedroferreira1 commented on src/api/auth.ts
> +  // getDbConnection,
Remove?

2021-05-31 16:17 UTC, pedroferreira1 commented on src/api/addresses.ts
> -const paramsSchema = Joi.object({
With this authorization change we are not sending the walletId as query parameters anymore, right? We are getting the id from the auth header?

2021-05-31 16:17 UTC, pedroferreira1 commented on src/api/auth.ts
> +    throw new Error('Unauthorized'); // returns a 401
Where do you handle this exception to return 401? Or is it automatically?

2021-05-31 18:40 UTC, r4mmer commented on package.json
> +    "@hathor/wallet-lib": "^0.19.0",
Yes, this update was made by a tool i was testing to check for updates in dependencies, so i ended up updating this, but the authentication will need the version with the bitcore-lib updated to 8.25.10

2021-05-31 18:46 UTC, r4mmer commented on src/api/addresses.ts
> -const paramsSchema = Joi.object({
Yes, the token has the walletId and the authorizer extracts and embeds it in the `event.requestContext.authorizer`. This way the function already has access to the walletId the user owns (and is viewing right now). The walletId only is necessary if the api allows users to request info of other wallets.

2021-05-31 18:53 UTC, r4mmer commented on src/api/auth.ts
> +    throw new Error('Unauthorized'); // returns a 401
According to aws documentation if you return the string `"Unauthorized"` or throw an error containing this string, it will return a 401 default response. (Also, the validation is case-sensitive).

2021-05-31 18:55 UTC, r4mmer commented on src/api/auth.ts
> +// import { closeDbAndGetError } from '@src/api/utils';
Done.

2021-05-31 18:55 UTC, r4mmer commented on src/api/auth.ts
> +  // getDbConnection,
Done.

2021-05-31 19:00 UTC, r4mmer commented on src/api/auth.ts
> +  ts: Joi.number().required(),
Done.

2021-06-30 17:33 UTC, luislhl commented on src/api/auth.ts
> + * @returns true if the timestamp, the xpubkey and signature matches
I think there is a mismatch between this docs and the params in the function

2021-06-30 17:42 UTC, r4mmer commented on src/api/auth.ts
> + * @returns true if the timestamp, the xpubkey and signature matches
You're right, adding the new parameters now

2021-06-30 17:53 UTC, andreabadesso approved these changes

2021-07-01 00:22 UTC, merged