feat: handle authorities
HathorNetwork/hathor-wallet-service-old pull request #7
Opened 2020-08-03 10:44 UTC by obiyankenobi

2020-12-14 13:32 UTC, obiyankenobi commented on src/txProcessor.ts
> +    // TODO get version from lib constants
You can complete the TODO now, as on the other `if`.

2020-12-14 13:32 UTC, obiyankenobi commented on src/txProcessor.ts
> +      token_data: utxo.authorities > 0 ? 0b10000000 : 0,
Get from lib: `hathorLib.constants.TOKEN_AUTHORITY_MASK`

2020-12-14 13:32 UTC, obiyankenobi commented on src/types.ts
> +    if (this.id === '00') {
TODO

2020-12-14 13:32 UTC, obiyankenobi commented on src/types.ts
> +    const isAuthority = (output.token_data & 0b10000000) > 0;   // eslint-disable-line no-bitwise
Get `0b10000000` from lib.

2020-12-14 13:32 UTC, obiyankenobi commented on src/types.ts
> +    if ((input.token_data & 0b10000000) > 0) {    // eslint-disable-line no-bitwise
Get `0b10000000` from lib.

2020-12-14 13:32 UTC, obiyankenobi commented on src/utils.ts
> +  (tokenData & 0b10000000) > 0    // eslint-disable-line no-bitwise
Get `0b10000000` from lib.

2020-12-14 13:32 UTC, obiyankenobi commented on src/types.ts
> +      melt: (authorities & 0b00000010) > 0,   // eslint-disable-line no-bitwise
Get constants from lib.

2020-12-14 16:59 UTC, pedroferreira1 approved these changes

2020-12-14 16:59 UTC, pedroferreira1 commented on DATABASE.md
> +// TODO name and symbol lengths are not limited on the blockchain, might be 255
Actually we do limit both on the protocol level. Name is at most 30 chars and symbol 5 chars.

2020-12-14 16:59 UTC, pedroferreira1 commented on src/types.ts
> +    const isAuthority = (output.token_data & 0b10000000) > 0;   // eslint-disable-line no-bitwise
We have this comparison 4 times in the code, maybe we should create a method for that, e.g. `isTokenDataAuthority`

2020-12-14 16:59 UTC, pedroferreira1 commented on tests/txProcessor.test.ts
> +    if ((output.token_data & 0b10000000) > 0) {     // eslint-disable-line no-bitwise
Get 0b10000000 from lib.

2020-12-14 16:59 UTC, pedroferreira1 commented on src/types.ts
> +    const isAuthority = (output.token_data & 0b10000000) > 0;   // eslint-disable-line no-bitwise
I just saw the method in `src/utils`, can you use it here and in the other places?

2020-12-14 16:59 UTC, pedroferreira1 commented on src/db.ts
> +  // outputs might be empty if we're destroying authorities or melting tokens
If you are melting tokens you still have the HTR deposit back as an output, right?

2020-12-14 19:25 UTC, andreabadesso commented on src/types.ts
> +    if (this.id === '00') {
Changed it to get hathor data from the lib, also changed the next lines to use it:

```
    const hathorConfig = hathorLib.constants.HATHOR_TOKEN_CONFIG;

    if (this.id === hathorConfig.uid) {
      this.name = hathorConfig.name;
      this.symbol = hathorConfig.symbol;
    }
```

2020-12-14 19:59 UTC, andreabadesso commented on src/types.ts
> +    const isAuthority = (output.token_data & 0b10000000) > 0;   // eslint-disable-line no-bitwise
Done

2020-12-14 20:03 UTC, andreabadesso commented on DATABASE.md
> +// TODO name and symbol lengths are not limited on the blockchain, might be 255
Updates docs to consider 30 chars for the name and 5 chars for the symbol

2020-12-14 21:13 UTC, andreabadesso commented on src/db.ts
> +  // outputs might be empty if we're destroying authorities or melting tokens
Right, but might be empty if we're destroying authorities. Removed the last part of the comment

2020-12-16 11:46 UTC, obiyankenobi commented on .env
> +DB_PASS=hathor
Not sure if you should commit this file.

2020-12-16 11:46 UTC, obiyankenobi commented on src/types.ts
> +    if (isAuthority(input.token_data)) {    // eslint-disable-line no-bitwise
`// eslint-disable-line no-bitwise` left

2020-12-16 11:46 UTC, obiyankenobi commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
I'm trying to remember why `Math.abs` is needed here, as `toInteger` should always return a positive number. Did you try removing it? We should investigate and leave a comment so we don't have this question in the furute.

2020-12-16 11:46 UTC, obiyankenobi commented on src/db.ts
> +  // outputs might be empty if we're destroying authorities or melting tokens
Comment still has `or melting tokens`.

2021-01-27 09:44 UTC, msbrogli requested changes

2021-01-27 09:44 UTC, msbrogli commented on DATABASE.md
> +  `unlocked_authorities` tinyint unsigned NOT NULL DEFAULT '0',
Why don't we treat authorities like any other utxo? We can add some flags to make it easy to filter them.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
I agree. It feels weird to have `Math.abs()` here. We could even assert that these values are `>= 0`.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +        // if it's < 0, there must be an entry already, so it will execute "ON DUPLICATE KEY UPDATE" instead of setting it to 0
In which cases it can become negative? I feel that it should never happen.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +        unlocked_authorities: Math.abs(tokenBalance.unlockedAuthorities.toInteger()),
Why do we need the `Math.abs()` here? It also feels weird to call the `.toInteger()` method.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
Same here.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +      return [
I'm always concerned about arrays. I feel they should always be objects. It also make it impossible to the linter to find typing errors/warnings.

2021-01-27 09:44 UTC, msbrogli commented on src/db.ts
> +      if (tokenBalance.unlockedAuthorities.hasNegativeValue()) {
When is it expected to be negative?

2021-01-27 09:44 UTC, msbrogli commented on src/types.ts
> +   * Supporting up to 8 authorities (but we only have mint and melt at the moment)
I don't get. Is it supposed to handle 8 types of authority but implements only 2? Shouldn't we raise an exception in the constructor if we get a not implemented type?

2021-01-27 09:44 UTC, msbrogli commented on src/types.ts
> +      n += this.array[i] * (2 ** (this.array.length - i - 1));
It's nit-picky but we can shift bits to prevent calculating `2**x` multiple times. We can also prevent the multiplication using an `if` block.

2021-01-27 09:44 UTC, msbrogli commented on src/types.ts
> +      if (value === 0) return 0;
Why do we need the `if`?

2021-01-27 09:44 UTC, msbrogli commented on tests/api.test.ts
> +    [token1.id, token1.name, token1.symbol],
Same feelings about using an array instead of an object.

2021-01-27 09:44 UTC, msbrogli commented on tests/api.test.ts
> +    tokenAuthorities: { unlocked: { mint: false, melt: false }, locked: { mint: false, melt: false } },
That's great and easy to read. Cheers to objects! \o/

2021-01-27 09:44 UTC, msbrogli commented on tests/utils.ts
> +  entries: unknown[][],
I know it is an utility function for the tests but I think we should receive a list of objects and map internally to an array.

2021-01-27 12:59 UTC, andreabadesso commented on src/db.ts
> +      return [
I agree. I will refactor this

2021-01-29 14:09 UTC, andreabadesso commented on src/types.ts
> +   * Supporting up to 8 authorities (but we only have mint and melt at the moment)
I agree, I'll add the exception

2021-01-29 14:20 UTC, andreabadesso commented on src/types.ts
> +      if (value === 0) return 0;
Because javascript uses the [IEEE_754](https://en.wikipedia.org/wiki/IEEE_754) standard and has negative and positive zeros, so `(-1) * 0` would return -0.

Apparently `-0 === 0` is `true` on most cases, so there wouldn't be a problem, but I would argue that the if is needed to be safe

2021-02-03 20:02 UTC, andreabadesso commented on tests/api.test.ts
> +    [token1.id, token1.name, token1.symbol],
This was refactored on 0ff2f1bf5d74b28143db2eb6c3fa14516cd88cc1 from `feat/timelock` branch. Will come when we rebase

2021-02-04 19:29 UTC, andreabadesso commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
`toInteger` will return negative values if we are spending an authority on the tx, the way the service is designed, we are setting the authority bits to `-1` when dealing with balances of a transaction.

In this case, toInteger will return a negative value, e.g: new `Authorities([-1, -1])` will return -3.

This is expected behaviour with the current design (using "negative bits" to represent spent authority in a tx) so the `Math.abs` is required

What I suggest is creating a `toUnsignedInteger` method that will only return positive values by using Math.abs before returning. What do you think, @obiyankenobi @msbrogli ?

I got a little confused when trying to understand what was going on on this method so I added a comment on 2675404e53233fdc07589652cd3222c432b20f0e to try to explain better what is doing.

2021-02-05 01:11 UTC, msbrogli commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
I agree with the `toUnsignedInteger()` method. Anyway, I still don't understand why we have negative values (and why we have decided to use negative values to represent a specific situation).

2021-02-05 01:13 UTC, msbrogli requested changes

2021-02-05 01:13 UTC, msbrogli commented on src/types.ts
> +      if (value === 0) return 0;
WTF! Really?! Ok. I feel we should add a comment explaining why this code is here (and mentioning the IEEE 754 for float numbers). Thanks!

2021-02-05 18:09 UTC, andreabadesso commented on DATABASE.md
> +  `unlocked_authorities` tinyint unsigned NOT NULL DEFAULT '0',
We could and probably should because of Pay-to-ScriptHash (P2SH) transactions.

If the Authority UTXO is inside a P2SH transaction, we won't be able to know if it is "unlocked" until we verify its script, making this cache invalid.

I would suggest to open a new issue to refactor the way we store and cache authorities instead of doing in this PR tho, what do you think?

2021-02-05 18:09 UTC, andreabadesso commented on src/db.ts
> +        unlocked_authorities: Math.abs(tokenBalance.unlockedAuthorities.toInteger()),
Will use the new `.toUnsignedInteger()`

2021-02-05 18:09 UTC, andreabadesso commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
Will use the new `.toUnsignedInteger()`

2021-02-05 18:15 UTC, msbrogli commented on DATABASE.md
> +  `unlocked_authorities` tinyint unsigned NOT NULL DEFAULT '0',
I agree. Let's do it in the future. Would you please add another issue about it to add it to our backlog?

2021-02-05 18:24 UTC, andreabadesso commented on src/types.ts
> +      if (value === 0) return 0;
Done bbec6f667ed38c3213912ae7e204964e49570d47

2021-02-05 18:51 UTC, andreabadesso commented on tests/utils.ts
> +  entries: unknown[][],
Done in 98315b43356214ddce32c1c4367099e7eff98cf9

2021-02-09 18:30 UTC, andreabadesso commented on DATABASE.md
> +  `unlocked_authorities` tinyint unsigned NOT NULL DEFAULT '0',
Done.

https://github.com/HathorNetwork/hathor-wallet-service/issues/15

2021-02-10 16:26 UTC, andreabadesso commented on src/types.ts
> +      n += this.array[i] * (2 ** (this.array.length - i - 1));
I don't think we can because we could have negative values in the array (representing an authority being spent on a TX)

2021-02-10 17:13 UTC, andreabadesso commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
We can have negative values for an Authority when calculating balances of a transaction.

When calculating the tokenBalanceMap from the Inputs, we set the authorities to negative when they are being spent on the inputs as you can see on 

https://github.com/HathorNetwork/hathor-wallet-service/blob/a42578f9458a2bb51c6b73caac125412a7bbbddc/src/types.ts#L435

So when the balances for an address are **merged**, we get the correct authorities value:

https://github.com/HathorNetwork/hathor-wallet-service/blob/a42578f9458a2bb51c6b73caac125412a7bbbddc/src/txProcessor.ts#L187

This is done by using [Math.sign](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math/sign) on the merge function:

https://github.com/HathorNetwork/hathor-wallet-service/blob/a42578f9458a2bb51c6b73caac125412a7bbbddc/src/types.ts#L196

2021-02-10 17:15 UTC, andreabadesso commented on src/db.ts
> +        locked_authorities: Math.abs(tokenBalance.lockedAuthorities.toInteger()),
Added the `toUnsignedInteger` method

2021-02-11 15:40 UTC, andreabadesso commented on src/db.ts
> +        // if it's < 0, there must be an entry already, so it will execute "ON DUPLICATE KEY UPDATE" instead of setting it to 0
This is dealing with balances of a transaction, so `tokenBalance.unlocked` can be negative when we are spending inputs

To make it clearer (it gets kind of hard to understand because we are using `ON DUPLICATE`), the object `entry` will only be inserted if there are not already an address_balance row for this (address, token_id)

This will be clearer when we refactor with the ORM

2021-02-11 16:44 UTC, msbrogli commented on src/types.ts
> +      n += this.array[i] * (2 ** (this.array.length - i - 1));
Following the docstring, I understood that the arrays must have only zeros and ones. What other values are allowed? I mean, the algorithm to convert to integer might be wrong for other values.

2021-02-11 16:50 UTC, msbrogli reviewed
Just replied some comments. It seems there are some things yet to finish.

2021-02-19 18:15 UTC, andreabadesso commented on src/db.ts
> +      return [
@msbrogli 

This is the expected syntax for bulk inserts on the ServerlessMysql lib we are using, this will be refactored and clearer when we add the ORM

2021-02-21 21:15 UTC, andreabadesso commented on src/types.ts
> +      n += this.array[i] * (2 ** (this.array.length - i - 1));
@msbrogli this will be removed or refactored when we close https://github.com/HathorNetwork/hathor-wallet-service/issues/15

2021-02-21 21:18 UTC, andreabadesso commented on src/db.ts
> +      if (tokenBalance.unlockedAuthorities.hasNegativeValue()) {
@msbrogli this will be removed or refactored when we close https://github.com/HathorNetwork/hathor-wallet-service/issues/15

2021-02-23 15:41 UTC, pedroferreira1 commented on DATABASE.md
> +// TODO name and symbol lengths are not limited on the blockchain, might be 255
You need to remove this TODO, right?

2021-02-23 15:42 UTC, pedroferreira1 approved these changes

2021-02-23 16:35 UTC, msbrogli approved these changes

2021-02-23 16:46 UTC, andreabadesso commented on DATABASE.md
> +// TODO name and symbol lengths are not limited on the blockchain, might be 255
Done

2021-02-23 16:54 UTC, merged