feat: create new API to return addresses to use of a wallet
HathorNetwork/hathor-wallet-service-old pull request #70
Opened 2021-05-13 01:03 UTC by pedroferreira1

2021-05-13 14:57 UTC, andreabadesso approved these changes

2021-05-14 06:27 UTC, msbrogli requested changes

2021-05-14 06:27 UTC, msbrogli commented on src/types.ts
> +  index: number;
Should we add the derivation path?

2021-05-14 06:27 UTC, msbrogli commented on src/db.ts
> +       ASC`, [walletId, walletId]);
Should we limit the max number of results? I understand the gap limit should automatically do it but it would prevent problems from eventual bugs or later changes in the way addresses are handled.

2021-05-14 06:27 UTC, msbrogli commented on serverless.yml
> +  getAddressesToUseApi:
Maybe add a description of what this API does? I'm not sure where to add it but I feel we should have it. In the OpenAPI description file seems a good place if there is one.

2021-05-19 20:36 UTC, jansegre reviewed
Looks OK. I only think that "addresses to use" is an awkward expression. I don't immediately understand what is it supposed to mean, is it supposed to be "new addresses + potentially already used addresses". Either way, here are some alternatives (which IMO are better but I'm obviously biased here):

- new addresses
- next addresses
- available addresses

2021-07-15 18:15 UTC, pedroferreira1 commented on src/types.ts
> +  index: number;
Done

2021-07-15 18:15 UTC, pedroferreira1 commented
> Looks OK. I only think that "addresses to use" is an awkward expression. I don't immediately understand what is it supposed to mean, is it supposed to be "new addresses + potentially already used addresses". Either way, here are some alternatives (which IMO are better but I'm obviously biased here):
> 
> * new addresses
> * next addresses
> * available addresses

Changed the name to newAddresses and the API name to /addresses/new

2021-07-15 18:20 UTC, pedroferreira1 commented on src/db.ts
> +       ASC`, [walletId, walletId]);
I agree it's important. Is it good enough to add a LIMIT as the gap limit of the wallet?

This raised another concern for me that we are not limiting the gap limit the wallets are requesting to use. We must limit them at what? 100? I know some use cases use much more than that but not sure we should allow use cases to use our public wallet service.

2021-07-15 18:31 UTC, pedroferreira1 commented on serverless.yml
> +  getAddressesToUseApi:
Done.

2021-07-15 19:55 UTC, andreabadesso requested changes

2021-07-15 19:55 UTC, andreabadesso commented on tests/api.test.ts
> +  await _testInvalidPayload(newAddressesGet, ['"id" is required']);
This will never be reached, id is not a parameter anymore, it comes from the authentication, right?

2021-07-15 19:55 UTC, andreabadesso commented on tests/api.test.ts
> +  const event = makeGatewayEvent({ id: 'my-wallet' });
You should use `makeGatewayEventWithAuthorizer`

2021-07-15 20:01 UTC, pedroferreira1 commented on tests/api.test.ts
> +  await _testInvalidPayload(newAddressesGet, ['"id" is required']);
Fixed

2021-07-15 20:01 UTC, pedroferreira1 commented on tests/api.test.ts
> +  const event = makeGatewayEvent({ id: 'my-wallet' });
Fixed, thanks

2021-07-15 22:16 UTC, msbrogli commented on src/db.ts
> +       ASC`, [walletId, walletId]);
I feel our public wallet service should allow at most 40 as GAP Limit.

2021-07-15 22:17 UTC, msbrogli approved these changes

2021-07-15 22:27 UTC, andreabadesso approved these changes

2021-07-16 00:30 UTC, merged