Feat/handle reorg
HathorNetwork/hathor-wallet-service-old pull request #71
Opened 2021-05-13 16:32 UTC by andreabadesso

2021-06-02 06:10 UTC, msbrogli approved these changes

2021-06-02 06:10 UTC, msbrogli commented on src/commons.ts
> +export const handleReorg = async (mysql: ServerlessMysql): Promise<void> => {
Missing docstring.

2021-06-02 06:10 UTC, msbrogli commented on src/commons.ts
> +    await removeTxs(mysql, txs);
Why would we remove the transactions? If they have not been voided, they will still be valid but without any confirmation.

2021-06-02 06:10 UTC, msbrogli commented on src/commons.ts
> +    await removeTxs(mysql, txs);
Oh! I just noticed that these are blocks. Maybe rename the variable to `blocks`? Or `blocksAfterHeight`?

2021-06-02 06:10 UTC, msbrogli commented on src/commons.ts
> +export const handleReorg = async (mysql: ServerlessMysql): Promise<void> => {
Should we log each step of the reorg? I feel it might be slow to run and logging each step might help debugging.

2021-06-02 06:10 UTC, msbrogli commented on src/fullnode.ts
> +export const create = (baseURL = BASE_URL): any => {
Missing docstring.

2021-06-02 06:10 UTC, msbrogli commented on src/txProcessor.ts
> +    await addTx(mysql, txId, tx.height, tx.timestamp, tx.version);
Maybe rename to `updateTx(...)`? It might be a direct call to `addTx(...)` in the current implementation. I just feel they might differ in the future, and it is more intuitive to call updateTx instead of addTx here.

2021-06-02 06:10 UTC, msbrogli commented on src/txProcessor.ts
> +export const onSearchForLatestValidBlockRequest: APIGatewayProxyHandler = async () => {
Missing docstring.

2021-06-02 06:10 UTC, msbrogli commented on src/txProcessor.ts
> +export const onHandleReorgRequest: APIGatewayProxyHandler = async () => {
Missing docstring.

2021-06-02 06:10 UTC, msbrogli commented on src/txProcessor.ts
> +export const onNewTxRequest: APIGatewayProxyHandler = async (event) => {
Missing docstring.

2021-06-02 06:10 UTC, msbrogli commented on src/db.ts
> +export const addTx = async (
Maybe rename to `addOrUpdateTx()`?

2021-06-02 06:10 UTC, msbrogli commented on DATABASE.md
>    `tx_id` varchar(64) NOT NULL,
`tx_id` might point to a block, right? If yes, I think we should add a comment here to clarify this point.

2021-06-03 18:09 UTC, andreabadesso commented on src/commons.ts
> +export const handleReorg = async (mysql: ServerlessMysql): Promise<void> => {
Done in 4226ced035e28859eae4ad9c33ec9a9b8d688707

2021-06-03 18:11 UTC, andreabadesso commented on src/commons.ts
> +    await removeTxs(mysql, txs);
This variable is used to remove transactions as well, on the loop

Maybe I could rename it to `hashes`, what do you think?

2021-06-03 18:30 UTC, andreabadesso commented on src/commons.ts
> +export const handleReorg = async (mysql: ServerlessMysql): Promise<void> => {
Done in 6a0a50d0b627ef911ad6f997eac756acc7d94c0b

2021-06-03 18:33 UTC, andreabadesso commented on src/fullnode.ts
> +export const create = (baseURL = BASE_URL): any => {
Done in b1bceda1f66a75436b92370c0a3273d1d523bcd5

2021-06-03 19:05 UTC, andreabadesso commented on src/txProcessor.ts
> +    await addTx(mysql, txId, tx.height, tx.timestamp, tx.version);
I agree.

Done in cafcd5697f43008ac3e63d88583993b03f4f3c20

2021-06-03 19:08 UTC, andreabadesso commented on src/db.ts
> +export const addTx = async (
Done in cafcd5697f43008ac3e63d88583993b03f4f3c20

2021-06-03 19:08 UTC, andreabadesso commented on src/txProcessor.ts
> +export const onSearchForLatestValidBlockRequest: APIGatewayProxyHandler = async () => {
Done in bee212d80ccf8578feab5935f1e8983def225b16

2021-06-03 19:08 UTC, andreabadesso commented on src/txProcessor.ts
> +export const onHandleReorgRequest: APIGatewayProxyHandler = async () => {
Done in bee212d80ccf8578feab5935f1e8983def225b16

2021-06-03 19:08 UTC, andreabadesso commented on src/txProcessor.ts
> +export const onNewTxRequest: APIGatewayProxyHandler = async (event) => {
Done in bee212d80ccf8578feab5935f1e8983def225b16

2021-06-03 19:09 UTC, andreabadesso commented on DATABASE.md
>    `tx_id` varchar(64) NOT NULL,
I agree

Done in 122f158abf756125aab83845a62fcf0aa338a3fb

2021-06-04 03:18 UTC, pedroferreira1 approved these changes

2021-06-04 03:18 UTC, pedroferreira1 commented on DATABASE.md
> +  `height` int unsigned DEFAULT NULL,
Are we going to store all blocks duplicated in `blocks` and `transaction` tables?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/utils.ts
> +export const checkBlockForVoided = async (txId: string): Promise<boolean> => {
I prefer `isBlockVoided` but I am ok with it. Or `isTxVoided` because we are not checking if it's a block, so it's a more generic method.

2021-06-04 03:18 UTC, pedroferreira1 commented on src/fullnode.ts
> + * Creates an handler for requesting data from the fullnode
Typo: a handler

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +  let end = bestBlock.height; // 63
What's 63? (on the line below as well)

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +  while (start <= end) {
I was thinking about this algorithm here and maybe I am exaggerating in the optmization but I think we've noticed that reorgs of size 1 happen regularly in our network, so every time this reorg happens we will need to do this binary search in all blocks of the network, right now this would be ~20 iterations, what's is not too much but if 99% of our reorgs are of size < 2, what do you think about getting the latest 3 blocks of the network to see if any of them are valid before starting the binary search? Then, if the assumption of 99% of reorgs are small is correct, we will prevent this longer binary search 99% of the time.

@msbrogli @andreabadesso

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +export const removeUtxos = async (mysql: ServerlessMysql, inputs: TxInput[], txId: string): Promise<void> => {
Should we update this method name? It should be called `updateOutputSpentBy` imo, what do you think?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  await removeUtxos(mysql, tx.inputs, txId);
Are we still removing the utxos?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  await removeUtxos(mysql, tx.inputs, txId);
Nevermind, I just noticed that the method name is still `removeUtxos` but we are only updating the rows right now. We should rename it (I've added the comment there).

2021-06-04 03:18 UTC, pedroferreira1 commented on DATABASE.md
> +  `height` int unsigned DEFAULT NULL,
Maybe we are saving only blocks in `blocks` table and only transactions in `transaction`? Is that right?

If that's the case, don't we need the timestamp of blocks? And maybe add a comment that the height of this table is the tx `first_block`, I thought it was to store the blocks height.

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +export const getBlockByHeight = async (mysql: ServerlessMysql, height: number): Promise<Block> => {
This return type `Promise<Block>` includes returning `null` in the case we call this method with a height we don't have in the db?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +    const utxo: DbTxOutput = {
We do this map at least two times, should we create a method for that in order to make it easier for future changes?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +  const txIds = txOutputs.map((txOutput) => txOutput.txId);
I am not sure this is right, this method is used here: https://github.com/HathorNetwork/hathor-wallet-service/pull/71/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts#diff-f2a2f842c9891cbd8bd1777480db992084e7be4cd6abbc0f58d0f156bc6c0968R375

The `txOutputs` in the parameter are the ones that were spent but should not be spent anymore, right? Then we must search here by `tx_id` and `index` because we could have an output that must be unspend and another output that is still correct and both are from the same transaction, right?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +            SUM(\`value\`), -- unlocked_balance
For an authority output the value is always 0?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/db.ts
> +  const results: DbSelectResult = await mysql.query(
Why don't you get this info from `address_balance` table?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +  while (start <= end) {
I am thinking again about this and, each reorg call should be every ~30s if we are unlucky and this full binary search should be really fast even without optmization, not sure if it's valid.

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +  let txs: Tx[] = allTxsAfterHeight.filter((tx) => [
With this filter I notice that the `transaction` table also has all the blocks, just like the `blocks` table. Is it necessary?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +    await removeTxs(mysql, txs);
@msbrogli they can be transactions if the transactions are spending outputs that were from reorged blocks, then they become voided as well.

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +      acc.add(utxo.spentBy);
Should we add only if `utxo.spentBy !== null`? Or is it safe to do like this?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +    const spentOutputs: DbTxOutput[] = await getTxOutputsBySpent(mysql, [...txIds]);
Maybe I am misunderstanding this part but you are getting these outputs to mark them as `spent_by = null`, right? Right now you are getting the outputs from `txIds`, which are the ids of the transactions that are spending the removed outputs, i.e. you are getting the outputs that will be removed in the next iteration.

I think you should be getting the outputs that are being spent by txs:

```
const txsBeingDeletedIds = txs.map((tx) => tx.tx_id);
const spentOutputs: DbTxOutput[] = await getTxOutputsBySpent(mysql, [...txsBeingDeletedIds]);   // Now you are using outputs that might be deleted, are being spent by a tx that will be deleted, then should be marked as not used

... 

// And the unspendUtxos method has a relevant comment as well imo
```

Is that right?

2021-06-04 03:18 UTC, pedroferreira1 commented on src/commons.ts
> +  const affectedAddresses = removedUtxoList.reduce((acc: Set<string>, utxo: DbTxOutput) => acc.add(utxo.address), new Set<string>());
I think we should add the utxos that were marked as `spent_by = null` in the `removedUtxoList` array as well, right? Maybe rename to `affectedUtxoList`. Because those utxos were not removed but they were spent but are not anymore, then the address balance changes also.

2021-06-04 03:19 UTC, pedroferreira1 requested changes
I miss clicked in "Approve" last time, just fixing this

2021-06-07 15:55 UTC, andreabadesso commented on src/db.ts
> +  const txIds = txOutputs.map((txOutput) => txOutput.txId);
I agree.

Done in 5d52f0d7f2e1c9caf915606954ce6e032a04c326

2021-06-07 15:56 UTC, andreabadesso commented on src/commons.ts
> +  const affectedAddresses = removedUtxoList.reduce((acc: Set<string>, utxo: DbTxOutput) => acc.add(utxo.address), new Set<string>());
I agree.

Done in f4dfc72e1b7a093a9b396f34060163227cd95f0f

2021-06-07 15:56 UTC, andreabadesso commented on src/commons.ts
> +    const spentOutputs: DbTxOutput[] = await getTxOutputsBySpent(mysql, [...txIds]);
Yes, you are right

Fixed in f4dfc72e1b7a093a9b396f34060163227cd95f0f

2021-06-07 15:56 UTC, andreabadesso commented on src/commons.ts
> +      acc.add(utxo.spentBy);
You are right.

Fixed in f4dfc72e1b7a093a9b396f34060163227cd95f0f

2021-06-07 17:39 UTC, andreabadesso commented on src/commons.ts
> +  let end = bestBlock.height; // 63
Oops

Done in 7a81e7348869a003e6554578d02c8b7ef30d4843

2021-06-07 17:43 UTC, andreabadesso commented on src/commons.ts
> +  let txs: Tx[] = allTxsAfterHeight.filter((tx) => [
Done in another PR:
https://github.com/HathorNetwork/hathor-wallet-service/pull/76

2021-06-07 17:49 UTC, andreabadesso commented on src/db.ts
> +export const removeUtxos = async (mysql: ServerlessMysql, inputs: TxInput[], txId: string): Promise<void> => {
Yes we should

Done in e411037c4ef31f42e6b4e57086c0250df2032001

2021-06-07 17:56 UTC, andreabadesso commented on src/db.ts
> +export const getBlockByHeight = async (mysql: ServerlessMysql, height: number): Promise<Block> => {
Done in bd56d1f5c0b448167e7c8928135ef6454c9f157c

2021-06-07 18:46 UTC, andreabadesso commented on src/db.ts
> +  const results: DbSelectResult = await mysql.query(
This is used to assert if the sum of `address_tx_history` is exactly equal the balance on the `address_balance` table

2021-06-07 18:47 UTC, andreabadesso commented on src/fullnode.ts
> + * Creates an handler for requesting data from the fullnode
Done in 76d3d66a2ccda0031e3c82182626d37e035ba990

2021-06-07 18:52 UTC, andreabadesso commented on src/utils.ts
> +export const checkBlockForVoided = async (txId: string): Promise<boolean> => {
I agree, done in 0e3a602f3b2635343558948edac5578834634fe0

2021-06-07 19:17 UTC, andreabadesso commented on src/db.ts
> +            SUM(\`value\`), -- unlocked_balance
Yes

2021-06-08 13:51 UTC, pedroferreira1 commented on DATABASE.md
> +  `height` int unsigned DEFAULT NULL,
This was done in another PR

2021-06-10 14:06 UTC, pedroferreira1 approved these changes

2021-06-10 14:06 UTC, pedroferreira1 commented on src/txProcessor.ts
>    // remove inputs from utxo table
Update comment after method rename?

2021-06-10 18:46 UTC, andreabadesso commented on src/txProcessor.ts
>    // remove inputs from utxo table
Done in 73af9092af09e3a966ba715d19d7765d11850854

2021-06-10 18:54 UTC, pedroferreira1 commented on src/txProcessor.ts
>    // remove inputs from utxo table
Still makes no sense to me the comment. 

`// remove inputs from tx_outputs table` should be `// mark tx_outputs used in the new tx as spent by`. What do you think?

2021-06-10 19:02 UTC, andreabadesso commented on src/txProcessor.ts
>    // remove inputs from utxo table
I agree with you, done in 7eb739884c9463e86771395c5bd217680b01d2e7

2021-06-15 19:46 UTC, msbrogli approved these changes

2021-06-15 19:46 UTC, msbrogli commented on src/commons.ts
> +  while (start <= end) {
Another approach is to run an exponential search before running the binary search. Sync-v1 does exactly this for the reasons already pointed out by @pedroferreira1. I feel we can open an issue to do it in the future. What do you think?

2021-06-15 22:30 UTC, merged