feature: update real time
HathorNetwork/hathor-wallet-service-old pull request #72
Opened 2021-05-17 19:48 UTC by r4mmer

2021-05-21 14:49 UTC, giovanecosta commented on src/ws/admin.ts
> +    console.log(event); // eslint-disable-line no-console
Is this for serverless running offline? If so, what do you think of using some High-Order function for ApiGateway handlers? (I'm using annotations in python).

So you can have something like:
```javascript
const ApiGatewayHandler = (handler) => {
  return (event, context) => {
    if (process.env.IS_OFFLINE) { console.log(event); }
    // ...
    // You can even parse headers and params here. it's extreme useful when we need some special header 
    //   or we want to normalize query strings and body params
    // ...
    return handler(event, context);
  }
}
```

And export you function like that:
`export const broadcast = ApiGatewayHandler(realBroadcastFunction);`

2021-05-21 15:12 UTC, giovanecosta commented on src/ws/admin.ts
> +  if (!(authHeader && validateAdminToken(authHeader))) {
this kind of validation can be easily done in the example i gave in the previous comment.

2021-05-21 15:12 UTC, giovanecosta commented on src/ws/admin.ts
> +  if (!payload) {
And this validation as well.

2021-05-21 15:14 UTC, giovanecosta commented on src/ws/admin.ts
> +  if (!(authHeader && validateAdminToken(authHeader))) {
i saw a lot of code like this here. Just reinforcing the first comment about High-Order Functions

2021-05-21 16:32 UTC, giovanecosta commented on src/ws/txNotify.ts
> +      return {
This lambda will consume SQS, right? So what will happen when `400` is returned? Make sense have a dead letter queue to reprocess? Or maybe a log for us to know that something is going wrong?

2021-05-21 19:39 UTC, r4mmer commented
### Open discussions
- wallets: should we have a `joinWallet` action or send the `walletId` on the connection call?
    - the `joinWallet` lets unvalidated clients connect to the API GW.
    - `joinWallet` lets the client use a single connection to listen to multiple wallet events
    - Implementing auth will not be a problem on either one.
- wallets: should we validate the walletId? Look in the wallets table to check if exists?
- txNotify: The trigger should be from SQS or lambda invoke?
    - the caller would be a lambda for `onNewTxEvent` that is called by an invoke, so if the caller invokes as well the execution time of `onNewTx` would be doubled (as 2 lambdas are running at the same time until completion)
    - SQS lets the lambda be called asynchronously but introduces another resource, and who would provision the SQS? (The SQS arn must be on the serverless.yml, so it must exist before lambda deployment).
- channels: should we let the `join channel` action enter the PR? There is no application for it now, but it opens up for future applications.
- ws admin: should it be a http trigger, or no trigger and we invoke from the cli or sdk if needed
- ws admin: should we make multicast by address or tx_id? (currently only walletId is supported)
- ws admin: should we have a disconnect by `connectionId` or only by `walletId` (by walletId disconnects all connections of that wallet)

2021-05-24 17:48 UTC, pedroferreira1 requested changes

2021-05-24 17:48 UTC, pedroferreira1 commented on README.md
> +#### WebSocker Action: New TX
Typo: Websocke**t**

2021-05-24 17:48 UTC, pedroferreira1 commented on README.md
> +#### WebSocker Action: New TX
Typo: Websocke**t**

Typo: **Update TX**

2021-05-24 17:48 UTC, pedroferreira1 commented on src/api/errors.ts
> +  FORBIDDEN = 'forbidden',
Is this related to the admin token in the env file, right? Why do we have this? Shouldn't we integrate the wallet authorization here after is finished for the APIs?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  // TODO send new_tx (ws)event for all walletIds on addressWalletMap
This is the event to be sent to SQS? I think this is one of the most important parts of the PR, right?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/redis.ts
> +export default redis;
Why do you export what you are importing?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/redis.ts
> +// export const client = redis.createClient(redisConfig);
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/redis.ts
> +  return setAsync(`walletsvc:conn:${connInfo.id}`, connInfo.url);
Maybe we should have a var with the prefix `walletsvc`

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/admin.ts
> +// import AWS from 'aws-sdk';
Remove import?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/admin.ts
> +  // addresses: Joi.array()
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/admin.ts
> +  // addresses: Joi.array()
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/admin.ts
> +  // maybe Promise.all().then(() => return)?
I prefer async/await syntax

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/utils.ts
> +  // return util.format(util.format('https://%s/%s', domain, stage));
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on tests/utils.ts
> +  // client.keys('*', (err, keys) => {
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/txNotify.ts
> +// const parseBody = (body: string) => {
Remove

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/txNotify.ts
> +      return {
For what I understood this 400 error will be returned when a message with wrong body schema is received. In this case I believe we should discard those messages (we can log but not reprocess).

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/txNotify.ts
> +    await Promise.all(wallets.map((wallet) => notifyWallet(redisClient, wallet, updateBody)));
Should we have a `type` key in the notify body message? For what I am seeing we are just sending the data in the ws message, right?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/joinChannel.ts
> +// import { APIGatewayProxyHandler } from 'aws-lambda';
Remove?

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/connection.ts
> +// import AWS from 'aws-sdk';
Remove? and the one below

2021-05-24 17:48 UTC, pedroferreira1 commented on src/ws/connection.ts
> +  // if (routeKey === '$default') {
We should remove all these commented codes

2021-05-24 17:56 UTC, pedroferreira1 commented
> wallets: should we have a joinWallet action or send the walletId on the connection call?

I prefer starting with the walletId on the connection call, even though it prevents out connection from listening to multiple wallets (we don't have it for now)

> wallets: should we validate the walletId? Look in the wallets table to check if exists?

Yes, I think so.

> txNotify: The trigger should be from SQS or lambda invoke?

I think using the SQS would be the best approach. The only downside is to have a new resource? If yes, I would go with that.

> channels: should we let the join channel action enter the PR? There is no application for it now, but it opens up for future applications.

I like it but I am afraid someone might explore this flooding our redis with fake connections. At least for the wallets we can validate if the wallet id exists.

> ws admin: should it be a http trigger, or no trigger and we invoke from the cli or sdk if needed

I am ok with triggering it with the cli for now. We don't have a regular use for that, I just think this should be clearly documented somewhere.

> ws admin: should we make multicast by address or tx_id? (currently only walletId is supported)

I think walletId is enough for now.

> ws admin: should we have a disconnect by connectionId or only by walletId (by walletId disconnects all connections of that wallet)

I think we should disconnect only by connectionId by default. Disconnect by walletId would disconnect all devices at the same time (mobile, desktop, headless, ...). We could support this but the default must be to disconnect by connectionId.

2021-05-24 18:57 UTC, andreabadesso requested changes

2021-05-24 18:57 UTC, andreabadesso commented on src/ws/admin.ts
> +  const proms = [];
Suggestion:

Refactor to something like (untested):

```
const proms = wallets.reduce(async (acc, walletId) => {
    const connections = await wsGetWalletConnections(redisClient, walletId);
    const disconnectPromises = connections.map((connection) => disconnectClient(connection, redisClient));

    return [...acc, ...disconnectPromises];
}, []);
```

2021-05-24 18:57 UTC, andreabadesso commented on src/ws/utils.ts
> +  connInfo: WsConnectionInfo,
Maybe change the parameters order to have the `RedisClient` as the first argument to be consistent with `@src/redis` method signatures

2021-05-24 18:57 UTC, andreabadesso commented on src/ws/utils.ts
> +  const apigatewaymanagementapi = new AWS.ApiGatewayManagementApi({
camelCase?

2021-05-24 18:57 UTC, andreabadesso commented on src/types.ts
> +
I think we should create a `types` directory and separate types into different files, those types here should be in `types/redis.ts`

What do you think?

2021-05-24 18:57 UTC, andreabadesso commented on src/ws/admin.ts
> +    const details = error.details.map((err) => ({
I know you are just being consistent with the other APIs that are doing this map to get the error details but I think it would be optimal to have a `getErrorDetails` method on utils and use it everywhere

Maybe create an issue to refactor this?

2021-05-24 18:57 UTC, andreabadesso commented on src/ws/joinChannel.ts
> +  _mysql: ServerlessMysql,
Why the underscore on `mysql` and `client`?

2021-05-24 20:12 UTC, r4mmer commented on src/ws/txNotify.ts
> +      return {
You're right, just checked the type for SQSHandler, the return type is void, so no return message is needed.

2021-05-24 20:14 UTC, r4mmer commented on src/ws/admin.ts
> +  if (!(authHeader && validateAdminToken(authHeader))) {
For this one i think it's not needed, i prefer not having an http trigger and make the admin calls only by invoke (sdk, cli or aws console). So i'm cleaning this validation out of the handler.

2021-05-24 20:26 UTC, r4mmer commented on src/api/errors.ts
> +  FORBIDDEN = 'forbidden',
You're right, i guess i didn't see this change when changing branches. I'm cleaning this out.

2021-05-24 20:27 UTC, r4mmer commented on src/redis.ts
> +export default redis;
You're right, i'm cleaning this out.

2021-05-25 18:22 UTC, r4mmer commented on src/ws/admin.ts
> +    console.log(event); // eslint-disable-line no-console
I think it's a good use for some validations, but we should see if we want to have this offline log first.

2021-05-25 18:28 UTC, r4mmer commented on src/types.ts
> +
I guess, but is there any other need for this, or redis is just a special case? if redis is a special case, i could put these types on `src/redis.ts` instead.

2021-05-25 18:28 UTC, r4mmer commented on src/ws/joinChannel.ts
> +  _mysql: ServerlessMysql,
To not have conflicts with global mysql (and in the first version i had a global client as well)

2021-05-27 14:21 UTC, pedroferreira1 requested changes

2021-05-27 14:21 UTC, pedroferreira1 commented on src/txProcessor.ts
> +  if (!queueUrl) {
Shouldn't this be `if (queueUrl)`?

2021-05-28 13:01 UTC, r4mmer commented on src/txProcessor.ts
> +  // TODO send new_tx (ws)event for all walletIds on addressWalletMap
Done

2021-05-28 13:03 UTC, r4mmer commented on src/ws/admin.ts
> +  const proms = [];
Changed to something along those lines, but there were a few modifications since the arrow function cannot be async (we cannot 'await' inside the arrow, but we can return promises).

2021-05-28 13:03 UTC, r4mmer commented on src/ws/utils.ts
> +  connInfo: WsConnectionInfo,
Done.

2021-05-28 13:04 UTC, r4mmer commented on src/ws/utils.ts
> +  const apigatewaymanagementapi = new AWS.ApiGatewayManagementApi({
Done.

2021-05-28 13:07 UTC, r4mmer commented on src/ws/admin.ts
> +    const details = error.details.map((err) => ({
Since this call is not called from ApiGateway it doesn't need to respond with details of the error, so i removed this part, but maybe we should refactor this on another issue.

2021-05-28 13:10 UTC, r4mmer commented on src/txProcessor.ts
> +  if (!queueUrl) {
Yes, i was thinking of `if (!queueUrl) return;" but ended up wrapping the sqs call on the it.

2021-06-01 13:15 UTC, pedroferreira1 commented on src/redis.ts
> +  // walletID: string,
Remove?

2021-06-01 13:15 UTC, pedroferreira1 commented on src/redis.ts
> +// XXX: AsyncGenerator implementations of scanAll, maybe use these?
Remove?

2021-06-01 13:15 UTC, pedroferreira1 commented on src/ws/admin.ts
> +export const broadcast: Handler = async (event) => {
I don't think broadcast and multicast should be open APIs. We could have basic auth or just something to protect from a bad usage.

2021-06-01 13:15 UTC, pedroferreira1 commented on src/ws/join.ts
> +  if (routeKey === 'join') {
Is there any other possible `routeKey`? Should we return any error if it's different than join?

2021-06-01 13:15 UTC, pedroferreira1 commented on src/ws/join.ts
> +  // verify ownership of wallet
This is a TODO, right? We are verifying if the wallet exists, now we must verify if your are the wallet owner after integrating with auth, right?

2021-06-01 19:01 UTC, r4mmer commented on src/ws/admin.ts
> +export const broadcast: Handler = async (event) => {
I just saw that i didn't remove the triggers from serverless, it should not have any triggers, so it would be invoke only, a caller must have an invoke permission (like `src.txProcessor.addNewTx` that is called by the daemon).

2021-06-01 19:03 UTC, r4mmer commented on src/ws/join.ts
> +  if (routeKey === 'join') {
The API Gateway takes care of routing actions to their lambdas, this would be good if we had more `routeKey`'s pointing to this lambda, but we just have the "join".

2021-06-01 19:04 UTC, r4mmer commented on src/ws/join.ts
> +  // verify ownership of wallet
Yes, for now we just verify that the wallet exists on the database.

2021-06-01 19:12 UTC, r4mmer commented on src/redis.ts
> +// XXX: AsyncGenerator implementations of scanAll, maybe use these?
Done

2021-06-01 19:13 UTC, r4mmer commented on src/redis.ts
> +  // walletID: string,
Done

2021-06-02 18:36 UTC, pedroferreira1 commented on src/ws/utils.ts
> +  // AWS.Request.promise() will make the request and return a thenable with the response
Didn't understand this "AWS.Request.promise() will make the request and return a thenable with the response". Is 'thenable' a typo?

2021-06-02 18:36 UTC, pedroferreira1 commented on src/ws/join.ts
> +  // verify ownership of wallet
You've removed both comments. I think you can keep the comment that we validate that the wallet exists on the db and another comment with TODO to verify ownership

2021-06-02 18:37 UTC, pedroferreira1 approved these changes

2021-06-02 19:13 UTC, r4mmer commented on src/ws/utils.ts
> +  // AWS.Request.promise() will make the request and return a thenable with the response
'thenable' is a way to refer to `Promise` or other objects that have the `.then()` function. A way to see this is that all promises are thenables but not all thenables are promises. I use this nomenclature because it's what the [aws-sdk docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#promise-property) use.

2021-06-02 19:25 UTC, r4mmer commented on src/ws/join.ts
> +  // verify ownership of wallet
Done.

2021-06-03 19:18 UTC, andreabadesso approved these changes

2021-06-04 21:27 UTC, merged