feat: handle voided transactions
HathorNetwork/hathor-wallet-service-old pull request #74
Opened 2021-06-01 19:42 UTC by andreabadesso

2021-06-28 19:27 UTC, pedroferreira1 requested changes

2021-06-28 19:27 UTC, pedroferreira1 commented on src/commons.ts
> + * Handles a reorg by finding the last valid block on the service's database and
The docstring (including parameters and return) is wrong

2021-06-28 19:27 UTC, pedroferreira1 commented on src/commons.ts
> +    const addresses = [...affectedAddresses];
Why do you recreate the list again here?

2021-06-28 19:27 UTC, pedroferreira1 commented on tests/txProcessor.test.ts
> +  await expect(checkAddressBalanceTable(mysql, 1, addr, token, 2500, 0, 0, 1)).resolves.toBe(true);
Maybe we should add a tx3 in this test that spends tx2. With tx2 as voided, tx3 should become voided as well and tx1 unspent. What do you think?

2021-06-28 19:54 UTC, andreabadesso commented on src/commons.ts
> +    const addresses = [...affectedAddresses];
`affectedAddresses` is a `Set`, I need to convert it to an `array`

2021-07-02 05:03 UTC, msbrogli approved these changes

2021-07-02 05:03 UTC, msbrogli commented on src/commons.ts
> +    const addresses = [...affectedAddresses];
Maybe log which address is being recalculated?

2021-07-02 18:31 UTC, andreabadesso commented on src/commons.ts
> +    const addresses = [...affectedAddresses];
I agree, the list probably won't be large so we can safely log

Done in d38c66bf0d8304c4d694e4bf499c4b17300dc994

2021-07-02 18:35 UTC, andreabadesso commented on src/commons.ts
> + * Handles a reorg by finding the last valid block on the service's database and
Done in c6fa85e97944dde34ef931a0d8d50cb516b825df

2021-07-05 18:23 UTC, andreabadesso commented on tests/txProcessor.test.ts
> +  await expect(checkAddressBalanceTable(mysql, 1, addr, token, 2500, 0, 0, 1)).resolves.toBe(true);
I agree!

Done in 849a8d74ba8865ed7b1103e6ef9c70292f6ecbe2

2021-07-05 18:48 UTC, pedroferreira1 approved these changes

2021-07-05 18:48 UTC, merged