refactor: using the transactions table to handle blocks
HathorNetwork/hathor-wallet-service-old pull request #76
Opened 2021-06-07 17:36 UTC by andreabadesso

2021-06-08 17:37 UTC, msbrogli approved these changes
I've been wondering whether we should store blocks in a separate table or not for a while. It seems you reached the conclusion that a single table is easier to maintain, right? You should've suffered from handling two tables and decided to move to a single table approach. What pain made you decide to change?

2021-06-08 17:37 UTC, msbrogli commented on src/db.ts
> +         IN (?)`, [blockVersion],
Double check that there is a hash index for the `version` field.

2021-06-08 17:55 UTC, pedroferreira1 commented
> I've been wondering whether we should store blocks in a separate table or not for a while. It seems you reached the conclusion that a single table is easier to maintain, right? You should've suffered from handling two tables and decided to move to a single table approach. What pain made you decide to change?

Before this refactor we were storing the blocks duplicated, in the blocks and transactions table. I suggested saving only once because it was not useful having the same information twice. We discussed about the queries in the future if we end up having many tps in the network but I still believe it won't be bad for us.

2021-06-09 17:40 UTC, andreabadesso commented on src/db.ts
> +         IN (?)`, [blockVersion],
Added the index on `DATABASE.md` on commit 68ca86212fdc0ec35f71656b77bd678ba3ae69d0

2021-06-09 17:43 UTC, andreabadesso commented on src/db.ts
> +         IN (?)`, [blockVersion],
What made me decide to remove the `blocks` database was the fact that we already have this information on the `transactions` table, so we would be storing the same information twice.

With a properly indexed table, I see no reason to separate it on another table for now

2021-06-10 02:08 UTC, pedroferreira1 requested changes

2021-06-10 02:08 UTC, pedroferreira1 commented on DATABASE.md
>    `height` int unsigned DEFAULT NULL,
Can we add a comment in this column to say that if it's a block, it's the height of the block and if it's a transaction, it's the height of the first_block?

2021-06-10 02:08 UTC, pedroferreira1 commented on src/db.ts
> +  const blockVersion = [
We have this array three times in this same file, can we create a single variable that is used in the three methods?

2021-06-10 16:20 UTC, andreabadesso commented on src/db.ts
> +  const blockVersion = [
Done in 54b7fd7d6ddb50e47b013c2da2ae242658304d1e

2021-06-10 16:20 UTC, andreabadesso commented on DATABASE.md
>    `height` int unsigned DEFAULT NULL,
Done in 7a4388591656421b396b5c710fc89d27efe1bae3

2021-06-10 16:23 UTC, pedroferreira1 approved these changes

2021-06-10 16:33 UTC, merged