chore: devops - Rate Limit, Alerts, Monitoring, QA, Deployment Steps
HathorNetwork/hathor-wallet-service-old pull request #78
Opened 2021-06-17 01:12 UTC by andreabadesso

2021-06-17 18:18 UTC, luislhl approved these changes

2021-06-18 01:19 UTC, pedroferreira1 approved these changes

2021-06-18 01:19 UTC, pedroferreira1 commented on serverless.yml
> +    # AWS_REGION: ${self:provider.region}
Why comment this? If it's not needed we could remove it.

2021-06-18 07:38 UTC, msbrogli approved these changes

2021-06-21 17:30 UTC, andreabadesso commented on serverless.yml
> +    # AWS_REGION: ${self:provider.region}
I agree, done in bd85c1378230e4ee41ebba7862802ca53256c2ef

2021-06-21 17:40 UTC, luislhl commented on serverless.yml
> +              - WalletServiceNewTxQueue
I think we should be adding the stage suffix here too

2021-06-21 17:41 UTC, luislhl commented on serverless.yml
> +        Fn::GetAtt: [ WalletServiceNewTxQueue, Arn ]
I think we should be adding the stage suffix here too

2021-06-21 17:41 UTC, luislhl requested changes
See previous comments

2021-06-21 17:54 UTC, andreabadesso commented on serverless.yml
> +              - WalletServiceNewTxQueue
I tested it, this is the resource name and not the queue name, so it will get the queue name (with the stage) from the resource

2021-06-21 17:54 UTC, andreabadesso commented on serverless.yml
> +        Fn::GetAtt: [ WalletServiceNewTxQueue, Arn ]
Same as above

2021-06-22 19:20 UTC, msbrogli approved these changes

2021-06-22 19:20 UTC, luislhl approved these changes

2021-06-22 20:25 UTC, merged