feat: filter utxo api and db method
HathorNetwork/hathor-wallet-service-old pull request #82
Opened 2021-06-21 17:07 UTC by andreabadesso

2021-07-07 17:18 UTC, r4mmer requested changes

2021-07-07 17:18 UTC, r4mmer commented on src/db.ts
> +        ${finalFilters.authority === 0 ? 'AND value > ?' : ''}
`finalFilters.authority` twice. I think it should be `smallerThan` and `biggerThan`, right?

2021-07-07 17:18 UTC, r4mmer commented on src/db.ts
> +        ${finalFilters.maxUtxos ? 'LIMIT ?' : ''}
Won't this throw an error? if `maxUtxos` exist and its not "falsy" it will be ok, but if not, there will be 5 `?` and 6 parameters.

2021-07-07 17:18 UTC, r4mmer commented on src/db.ts
> +    'INSERT INTO `tx_proposal_token_info` VALUES ?',
I think that if entry is a list of values the columns should be specified on the query, so we should either add the columns to the query or use a list of objects.

2021-07-07 17:18 UTC, r4mmer commented on src/db.ts
> +  const entry = [
The query below uses `[ entry ]`, so this shouldn't be a list of entries, right?

2021-07-07 17:18 UTC, r4mmer commented on src/db.ts
> +    [txProposalId],
For a single parameter we don't need the list.

from https://github.com/mysqljs/mysql#performing-queries 

> If the query only has a single replacement character (?), and the value is not null, undefined, or an array, it can be passed directly as the second argument to .query

2021-07-07 18:55 UTC, andreabadesso commented on src/db.ts
> +        ${finalFilters.authority === 0 ? 'AND value > ?' : ''}
No, that is correct, we are only checking value if we are not filtering for authority utxos as authority utxos will always have value = 0

2021-07-07 18:55 UTC, andreabadesso commented on src/db.ts
> +        ${finalFilters.maxUtxos ? 'LIMIT ?' : ''}
No, it will just ignore the 6th parameter, I think it is safe to do that

2021-07-18 18:01 UTC, andreabadesso commented on src/db.ts
> +    'INSERT INTO `tx_proposal_token_info` VALUES ?',
This query was removed entirely in the latest refactor

2021-07-18 18:01 UTC, andreabadesso commented on src/db.ts
> +    [txProposalId],
This query was removed entirely in the latest refactor

2021-07-18 18:01 UTC, andreabadesso commented on src/db.ts
> +  const entry = [
This query was entirely removed in the latest refactor

2021-07-22 22:22 UTC, pedroferreira1 requested changes

2021-07-22 22:22 UTC, pedroferreira1 commented on DATABASE.md
> +  `version` int unsigned NOT NULL DEFAULT 1,
Do we still need this field?

2021-07-22 22:22 UTC, pedroferreira1 commented on DATABASE.md
> +CREATE INDEX tx_output_heightlock_idx USING HASH ON `tx_output`(`heightlock`);
We've already created those indexes in dev, or not?

2021-07-22 22:22 UTC, pedroferreira1 commented on DATABASE.md
> +  `token_id` varchar(64), -- Can be null because it might be a token creation action
The first file is a migration that deletes this table. Why are we adding those fields here?

2021-07-22 22:22 UTC, pedroferreira1 commented on db/migrations/20210718180539-add_tx_proposal_version.js
> +    await queryInterface.addColumn('tx_proposal', 'version', {
Why do we need it?

2021-07-22 22:22 UTC, pedroferreira1 commented on serverless.yml
> +                maxUtxos: true
We also have txId and index as optional parameters, right? How is it working if they are not here? Why do we need this configuration?

2021-07-22 22:22 UTC, pedroferreira1 commented on DATABASE.md
> +CREATE TABLE `tx_proposal_token_info` (
Why do we need this table?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/types.ts
> +export interface TxProposalTokenInfo {
I haven't seen this being used.

2021-07-22 22:22 UTC, pedroferreira1 commented on src/types.ts
> +export interface IWalletInsufficientFunds {
Where's it being used?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/types.ts
> +export enum InputSelectionAlgo {
Where's it being used?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/types.ts
> +export interface IFilterUtxo {
We also have `txId` and `index` as optional parameters here, right?

2021-07-22 22:22 UTC, pedroferreira1 commented on tests/db.test.ts
> +test('updateTx should add height to a tx', async () => {
I didn't understand this test. Where are we checking the height?

2021-07-22 22:22 UTC, pedroferreira1 commented on tests/db.test.ts
> +});
Should we add a test for `filterUtxos` that filters by `txId` and `index`?

2021-07-22 22:22 UTC, pedroferreira1 commented on tests/db.test.ts
> +});
Nevermind. It's already being tested in the other test file

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> +  index: Joi.number().optional(),
Add `min(0)`?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> + * This lambda is called by API Gateway on POST /filter_utxos
It's a GET /wallet/utxos

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> +    // check if the utxo is a member of the user's wallet
This comment should be above, right? Here you map each utxo to add the address path to it.

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> +export const mapUtxosWithPath = (walletAddresses: AddressInfo[], utxos: DbTxOutput[]) => utxos.map((utxo) => {
Missing return type

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> +  const flatAddresses = walletAddresses.map((walletAddress) => walletAddress.address);
I am thinking if it's worth it to have another type `AddressString` (or something like that), which is only the address. Everywhere you are using this `walletAddresses` you need to map them to the `.address`.

2021-07-22 22:22 UTC, pedroferreira1 commented on src/api/utxos.ts
> + * @param walletId - The user wallet id
This is wrong docstring, right?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/db.ts
> +  if (results.length > 0 && results[0].value !== null) {
Why did you add this? What's this `value` in transaction table?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/db.ts
> +  version: number,
Do we still need this?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/db.ts
> +      finalFilters.smallerThan,
If `authority` is !== 0 and `maxUtxos` need to be filtered, this query will still work? I think the array of values should change dynamically for it to work, or am I missing something?

2021-07-22 22:22 UTC, pedroferreira1 commented on src/db.ts
> +  const utxos: DbTxOutput[] = results.map((utxo) => ({
I think you are missing 2 fields here, comparing to the `getUtxo` method:

```
    txProposalId: result.tx_proposal as string,
    txProposalIndex: result.tx_proposal_index as number,
```

Because it's a big mapping and it's used more than once, maybe it's worth it creating a method for that.

2021-07-26 15:27 UTC, andreabadesso commented on DATABASE.md
> +  `version` int unsigned NOT NULL DEFAULT 1,
We don't. This is a leftover from the old `txProposalCreate` API. Fixed in 5b56c84f9f110340d8e32c0179c0f594c6b84632

2021-07-26 15:33 UTC, andreabadesso commented on DATABASE.md
> +  `token_id` varchar(64), -- Can be null because it might be a token creation action
We shouldn't. Fixed in aaedf7762e104ed406a6c19f9121ead67d178b79

2021-07-26 15:34 UTC, andreabadesso commented on serverless.yml
> +                maxUtxos: true
We don't need it. I was testing those parameters and forgot to remove it

Fixed in 7164730cdf738ec4fd951e6db3c2c8abf33e766d

2021-07-26 15:36 UTC, andreabadesso commented on src/api/utxos.ts
> +  index: Joi.number().optional(),
Done in f6dc6531545249cde00b9fb746917a072eb6b7b5

2021-07-26 15:37 UTC, andreabadesso commented on DATABASE.md
> +CREATE INDEX tx_output_heightlock_idx USING HASH ON `tx_output`(`heightlock`);
We did, but didn't add to `DATABASE.md`

2021-07-26 15:38 UTC, andreabadesso commented on src/api/utxos.ts
> + * This lambda is called by API Gateway on POST /filter_utxos
Fixed in 174b95b34d9ac4141247f57db4188bdb8a18debf

2021-07-26 15:38 UTC, andreabadesso commented on src/api/utxos.ts
> +  index: Joi.number().optional(),
Done in f6dc6531545249cde00b9fb746917a072eb6b7b5

2021-07-26 15:39 UTC, andreabadesso commented on src/api/utxos.ts
> +    // check if the utxo is a member of the user's wallet
You are right. Fixed in e3d59edd89cda5c3d0baa87f5b8bbfe017ac33ff

2021-07-26 15:51 UTC, andreabadesso commented on src/api/utxos.ts
> +export const mapUtxosWithPath = (walletAddresses: AddressInfo[], utxos: DbTxOutput[]) => utxos.map((utxo) => {
Done in cfef8693f1deccc0e88d40d9eb05ec4ce31d935b

2021-07-26 15:52 UTC, andreabadesso commented on src/api/utxos.ts
> + * @param walletId - The user wallet id
Indeed.

Fixed in c67a656f49fda331dc39af7e88c12243586426e7

2021-07-26 15:54 UTC, andreabadesso commented on src/db.ts
> +  if (results.length > 0 && results[0].value !== null) {
Because `MAX(height)` will always return a row in the query, but with NULL if nothing is found.

`value` is the result of `MAX(height)`:

`SELECT MAX(height) AS` **value**

2021-07-26 15:55 UTC, andreabadesso commented on src/db.ts
> +      finalFilters.smallerThan,
It will still work, it will just ignore the extra parameters in the array

2021-07-26 16:28 UTC, andreabadesso commented on src/db.ts
> +  const utxos: DbTxOutput[] = results.map((utxo) => ({
I agree!

Done in 8eaca4920335c4670e02c388667711626e1147f6

2021-07-26 16:29 UTC, andreabadesso commented on src/types.ts
> +export interface IFilterUtxo {
Yes!

Fixed in 7c1d205b458357fcab3d65280840f99a42fc7850

2021-07-26 16:30 UTC, andreabadesso commented on src/types.ts
> +export enum InputSelectionAlgo {
It is not anymore, removed it in 7c1d205b458357fcab3d65280840f99a42fc7850

2021-07-26 16:30 UTC, andreabadesso commented on src/types.ts
> +export interface IWalletInsufficientFunds {
It is not.

Fixed in e23e65aa3a26fbfb4f44f4a1cbce4ed252101d8a

2021-07-26 16:31 UTC, andreabadesso commented on src/types.ts
> +export interface TxProposalTokenInfo {
It is not. 

Fixed in 5a2a383af42aa1bc8c959fcad1988309269be022

2021-07-26 16:32 UTC, andreabadesso commented on tests/db.test.ts
> +test('updateTx should add height to a tx', async () => {
Wow, you are right. The test was pointless

Fixed in c9d41298ee3c48040b853f3ca81889bca2235de3

2021-07-28 01:32 UTC, pedroferreira1 commented on src/db.ts
> +      finalFilters.smallerThan,
As we talked today, this needs a fix and a test that fails in this case.

2021-07-29 17:33 UTC, andreabadesso commented on src/db.ts
> +      finalFilters.smallerThan,
Fixed in 142c9d39a6be1ee5c9c0db26665b6b3d9f40cb53

2021-07-29 17:34 UTC, andreabadesso commented on src/db.ts
> +  version: number,
We don't, I removed it, can you check again?

2021-07-29 17:34 UTC, andreabadesso commented on db/migrations/20210718180539-add_tx_proposal_version.js
> +    await queryInterface.addColumn('tx_proposal', 'version', {
We don't, I deleted the migration as it was not yet deployed

2021-07-29 17:35 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `tx_proposal_token_info` (
We don't. 

I removed it in 5a2a383af42aa1bc8c959fcad1988309269be022

2021-07-29 17:48 UTC, andreabadesso commented on src/api/utxos.ts
> +  const flatAddresses = walletAddresses.map((walletAddress) => walletAddress.address);
As we discussed on slack, I don't think there would be a huge performance gain from having a separate method that will have a different query (returning the address list as strings) as opposed to mapping the query result for the addresses

But I can open an issue to refactor this later, what do you think?

2021-07-30 18:12 UTC, pedroferreira1 commented on src/api/utxos.ts
> +  const flatAddresses = walletAddresses.map((walletAddress) => walletAddress.address);
I don't think there is need for an issue. I think the code is ok as it is right now.

2021-07-30 18:18 UTC, pedroferreira1 approved these changes

2021-08-13 20:54 UTC, luislhl commented on DATABASE.md
> +CREATE INDEX transaction_height_idx USING HASH ON `transaction`(`height`);
Do we have sequelize migrations for those indexes?

2021-08-13 20:58 UTC, luislhl commented on db/migrations/20210718180425-remove_tx_proposal_outputs.js
> +    await queryInterface.dropTable('tx_proposal_outputs');
We will have to be careful with this kind of change when the service is in production, to not break compatibility with the previous version of the application in the meantime between running the migrations and deploying the app.

But for now I think it's ok

2021-08-13 21:39 UTC, luislhl commented on src/api/utxos.ts
> +    if (!Number.isInteger(value.index)) {
I think you could also declare this requirement in the Joi schema: https://github.com/sideway/joi/blob/master/API.md#objectandpeers-options

Unless you think it's better to have it here as an if.

2021-08-13 21:48 UTC, luislhl commented on src/api/utxos.ts
> +export const validateAddresses = async (walletAddresses: AddressInfo[], addresses: string[]): Promise<string[]> => {
Why is this function async?

2021-08-13 21:50 UTC, luislhl commented on src/api/utxos.ts
> +      return closeDbAndGetError(mysql, ApiError.FORBIDDEN);
Shouldn't we have a more descriptive error here like the other ones?

2021-08-13 21:53 UTC, luislhl commented on src/api/utxos.ts
> +  if (value.txId !== undefined) {
Maybe a comment here explaining in which case the `txId` exists would improve readability. I had to go to the design to check the explanation there.

2021-08-13 21:55 UTC, luislhl commented on src/api/utxos.ts
> +  if (value.txId !== undefined) {
I mean, the confusion is not about when it exists, it's obvious that it exists when it's in the query. The comment would be to explain in which case someone sends it in the query.

2021-08-16 14:48 UTC, andreabadesso commented on DATABASE.md
> +CREATE INDEX transaction_height_idx USING HASH ON `transaction`(`height`);
![image](https://user-images.githubusercontent.com/3586068/129583001-cd931c52-fd2b-4b76-a618-97278aa2bd41.png)

We do, I'll create another PR to remove the `DATABASE.md` file as it is now useless and confusing

2021-08-16 14:49 UTC, luislhl commented on src/api/txProposalCreate.ts
> +  const tx = hathorLib.helpersUtils.createTxFromHex(body.txHex, new hathorLib.Network(process.env.NETWORK));
Should we create a type for the transaction returned here?

For now TypeScript is typing this as `any`, since the wallet-lib doesn't have typing information.

2021-08-16 14:50 UTC, andreabadesso commented on db/migrations/20210718180425-remove_tx_proposal_outputs.js
> +    await queryInterface.dropTable('tx_proposal_outputs');
You are right, I'll create an issue to discuss the best approach for those kind of migrations

2021-08-16 14:56 UTC, andreabadesso commented on src/api/utxos.ts
> +    if (!Number.isInteger(value.index)) {
I agree! I didn't find this requirement on the docs

Fixed in 9859d9477dae545229b9dbca7028291eb2e665bf

2021-08-16 14:58 UTC, andreabadesso commented on src/api/utxos.ts
> +export const validateAddresses = async (walletAddresses: AddressInfo[], addresses: string[]): Promise<string[]> => {
You are right, fixed in 7ba421a85a3b3a29a9fb900e49bbb868cd5978cf

2021-08-16 15:01 UTC, andreabadesso commented on src/api/utxos.ts
> +  if (value.txId !== undefined) {
I agree! Fixed in aca353a8f0d61e39b2d37837404e2aa7b1646275

2021-08-16 15:11 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +  const tx = hathorLib.helpersUtils.createTxFromHex(body.txHex, new hathorLib.Network(process.env.NETWORK));
I've just tested it and TypeScript was getting the type from the wallet-lib method, but I added the type on the wallet-service as well to make it more explicit

Done in 0246942695655b474ac7a6f4c457bf38c3409de0

2021-08-16 15:14 UTC, andreabadesso commented on src/api/utxos.ts
> +      return closeDbAndGetError(mysql, ApiError.FORBIDDEN);
I agree

Done in 67ae4d6921d5ff438d25de00f78703e5f6d2ec22

2021-08-16 15:18 UTC, andreabadesso commented on db/migrations/20210718180425-remove_tx_proposal_outputs.js
> +    await queryInterface.dropTable('tx_proposal_outputs');
Issue created: https://github.com/HathorNetwork/hathor-wallet-service/issues/120

2021-08-16 15:20 UTC, luislhl commented on src/api/txProposalCreate.ts
> +  const tx = hathorLib.helpersUtils.createTxFromHex(body.txHex, new hathorLib.Network(process.env.NETWORK));
Ok, maybe the problem is my VScode, then.

2021-08-16 15:29 UTC, luislhl commented on src/api/txProposalCreate.ts
> +    return closeDbAndGetError(mysql, ApiError.INPUTS_ALREADY_USED);
What happens in case 2 txProposals using the same inputs are created concurrently, and both pass this check? This is a possible scenario, right?

In which future step we detect the duplicity?

I'm asking this more out of curiosity than anything

2021-08-16 15:33 UTC, luislhl commented on serverless.yml
> -    role: arn:aws:iam::769498303037:role/WalletServiceLoadWalletLambda
This isn't needed anymore?
Can we also remove the role from AWS IAM?

2021-08-16 15:42 UTC, luislhl commented on src/db.ts
>    await mysql.query(
Should we use timeout on mysql queries? This could avoid the Lambda timeout being hit in some situations, which is a scenario we know gives us no information about what exactly occurred.

2021-08-16 15:44 UTC, luislhl approved these changes

2021-08-16 16:10 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    return closeDbAndGetError(mysql, ApiError.INPUTS_ALREADY_USED);
I think you are right, we won't detect the duplicity, `markUtxosWithProposalId` will overwrite the last `txProposalIndex` on the `tx_output` table and the txProposal that loses the race will be in an invalid state

I will create an issue to properly handle this scenario

2021-08-16 16:11 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +    return closeDbAndGetError(mysql, ApiError.INPUTS_ALREADY_USED);
Issue created: https://github.com/HathorNetwork/hathor-wallet-service/issues/122

2021-08-16 16:14 UTC, andreabadesso commented on serverless.yml
> -    role: arn:aws:iam::769498303037:role/WalletServiceLoadWalletLambda
This should not have been removed, it is still needed

Fixed in 6a5cd149a3b70def6f81d3bf6b5bcc20eafa4b94

2021-08-16 16:15 UTC, andreabadesso commented on src/db.ts
>    await mysql.query(
Yes we should, we've talked about this before

I created the issue at https://github.com/HathorNetwork/hathor-wallet-service/issues/123

2021-08-16 17:05 UTC, merged