feat: websocket wallet auth
HathorNetwork/hathor-wallet-service-old pull request #87
Opened 2021-07-02 19:54 UTC by r4mmer

2021-07-08 20:33 UTC, r4mmer commented
Serverless offline does not support [yet](https://github.com/dherault/serverless-offline/pull/1222) the websocket authorizer, as described [here](https://github.com/dherault/serverless-offline/issues/951).

So we should test if this works as intended on staging environment.
If this doesn't work, we could move the jwt verification process to `common.js` and import from there.

2021-07-15 15:49 UTC, luislhl commented
@r4mmer , could you add a description of what we are trying to achieve in this PR and the main alterations?

2021-07-15 16:16 UTC, luislhl commented on package.json
>      "serverless-dotenv-plugin": "^2.4.2",
We can uninstall this plugin. It's not needed anymore.

2021-07-15 16:19 UTC, luislhl commented on serverless.yml
> +      name: bearerAuthorizer
What this name is used for?

I noticed it has the same name as the other authorizer.

2021-07-15 16:30 UTC, luislhl commented on src/api/auth.ts
> +      throw new Error('Expired Token');
What status code will be returned in the request in those cases, 401?

What defines the status code returned?

2021-07-15 16:35 UTC, luislhl commented on src/api/auth.ts
> +  CustomAuthorizerHandler,
Apparently this is deprecated. Shouldn't we use the one recommended by them?

```
/** @deprecated Use APIGatewayAuthorizerHandler or a subtype */
export type CustomAuthorizerHandler = Handler<CustomAuthorizerEvent, APIGatewayAuthorizerResult>;
```

2021-07-15 16:42 UTC, luislhl commented on src/api/auth.ts
> +  throw new Error('Unexpected Error.');
Is it possible that if the token is expired, we will throw this error?

I'm not sure becuase we apparently have two places that check the token expiration, the `jwt.verify` in line 192 and the if in line 220.

If the expired token can reach this if in line 220, we will be throwing this `Unexpected Error` for it, when we could be throwing a better error message.

If it can't reach this if in line 220, why do we need to check its expiration in the if?

2021-07-15 16:47 UTC, luislhl commented on src/ws/connection.ts
> +      walletId = process.env.DEV_WALLET_ID;
I feel we should have a configuration file (`settings.js`) where all environment variables are read, and any other part of the code imports them from the configuration file, instead of reading them directly.

This will make it easier to know all the env vars we need for the application to work.

2021-07-15 16:52 UTC, luislhl commented on src/ws/connection.ts
> +  ));
Isn't it possible that the `closeRedisClient` function below will be executed before `wsJoinWallet`? This shouldn't happen, right?

Why don't we also `await wsJoinWallet`?

```
 await initWsConnection(
    redisClient,
    connInfo,
  );
  
  await wsJoinWallet(
    redisClient,
    connInfo,
    walletId,
  );
```

2021-07-15 20:36 UTC, r4mmer commented on serverless.yml
> +      name: bearerAuthorizer
The name is the function of the authorizer.

2021-07-15 20:37 UTC, r4mmer commented on src/api/auth.ts
> +      throw new Error('Expired Token');
The API Gateway returns 401 for any `Error` thrown in the authorizer.

2021-07-15 20:47 UTC, r4mmer commented on src/ws/connection.ts
> +      walletId = process.env.DEV_WALLET_ID;
This would be nice, but I think we should implement this on another PR.

2021-07-15 20:50 UTC, r4mmer commented on src/ws/connection.ts
> +  ));
The await also await the `then` to resolve.

2021-07-15 21:01 UTC, r4mmer commented on src/api/auth.ts
> +  throw new Error('Unexpected Error.');
Changed to verify expiration only on the `jwt.verify` method and throw more descriptive error if our `verifySignature` fails.

2021-07-15 21:03 UTC, r4mmer commented on src/api/auth.ts
> +  CustomAuthorizerHandler,
Changed back to `APIGatewayTokenAuthorizerHandler` since the authorizers will be of type `token` they should have the `authorizationToken` which the `APIGatewayAuthorizerHandler` lacks.

2021-07-15 21:04 UTC, r4mmer commented on package.json
>      "serverless-dotenv-plugin": "^2.4.2",
Should i also remove the `useDotenv: true` from `serverless.yml`?

2021-07-16 18:45 UTC, luislhl commented on package.json
>      "serverless-dotenv-plugin": "^2.4.2",
No, this is the new built-in option from Serverless that replaces the plugin. 

There is a warning about this in the beginning of this page: https://www.serverless.com/plugins/serverless-dotenv-plugin

2021-07-16 19:05 UTC, luislhl approved these changes, later dismissed

2021-07-19 18:12 UTC, andreabadesso commented on src/ws/connection.ts
> +      walletId = process.env.DEV_WALLET_ID;
I agree with @luislhl that this would be nice. Maybe even throwing an exception if required environment variables are not loaded

@r4mmer can you open an issue describing that?

2021-07-19 18:39 UTC, andreabadesso requested changes

2021-07-19 18:39 UTC, andreabadesso commented on src/ws/connection.ts
> +      throw ex;
Shouldn't we also disconnect the client here?

2021-07-19 18:39 UTC, andreabadesso commented on src/ws/connection.ts
>  };
**Unrelated to line number**

Can you add some basic tests on `ws/redis.ts`? I know that serverless-offline does not allow offline websocket auth but there are methods that we can mock and test here

Also, coverage is quite low on those files and this may break the CI after the latest merge from Luis PR-validation branch

2021-07-19 19:01 UTC, r4mmer commented on src/ws/connection.ts
>  };
The websocket cannot be tested on the unit tests, if we could disable the CI coverage for the `ws` folder it would be better, but the `redis.ts` should be well tested.

2021-07-19 19:01 UTC, r4mmer commented on src/ws/connection.ts
>  };
The websocket cannot be tested on the unit tests, if we could disable the CI coverage for the ws folder it would be better, but the redis.ts should be well tested.

2021-07-20 18:30 UTC, r4mmer commented on src/ws/connection.ts
> +      throw ex;
Done.

2021-07-20 19:17 UTC, andreabadesso approved these changes

2021-10-07 22:02 UTC, closed without merging