Chore: Deployment preparation
HathorNetwork/hathor-wallet-service-old pull request #88
Opened 2021-07-05 13:27 UTC by luislhl

This PR contains some changes we are identifying while deploying and testing the service.

2021-07-06 20:00 UTC, andreabadesso requested changes

2021-07-06 20:00 UTC, andreabadesso commented on serverless.yml
> +    NETWORK: ${env:NETWORK}
We also need to add the `AUTH_SECRET` environment variable

This can be a random string of any length

I am generating it locally using:
`openssl rand -base64 32`

2021-07-06 20:00 UTC, andreabadesso commented on serverless.yml
> +# package:
Remove instead of commenting it out?

2021-07-06 20:00 UTC, andreabadesso commented on serverless.yml
> +            WalletServiceNewTxQueue_${opt:stage, 'dev'}
What is `opt:stage`?

2021-07-06 20:00 UTC, andreabadesso commented on serverless.yml
> +    memorySize: 256
I think we can set this for all methods, the 1GB default seems to be too much

2021-07-08 14:52 UTC, luislhl commented on serverless.yml
> +            WalletServiceNewTxQueue_${opt:stage, 'dev'}
It's the value of the `--stage` option passed to serverless cli.

If we run `serverless deploy --stage prod`, for instance, its value is `prod`.

2021-07-08 15:06 UTC, pedroferreira1 approved these changes

2021-07-08 15:06 UTC, pedroferreira1 commented on serverless.yml
> -  individually: true
What's this configuration for?

2021-07-08 15:06 UTC, pedroferreira1 commented on serverless.yml
> +    timeout: 600
Decrease?

2021-07-08 17:57 UTC, luislhl commented on serverless.yml
> -  individually: true
It makes Serverless build one individual package (.zip) for each function.

In conjuction with the webpack plugin, it does more: https://github.com/serverless-heaven/serverless-webpack#optimization--individual-packaging-per-function

However, this was causing our build to be extremely painful. It took a long time and used all memory in the dev's machine.
Apparently it was running Webpack build one time for each function.

After removing this, this build complete in something like 10s.

And the generated package is not so big. So it seems we have no reason to use this.

2021-07-08 17:57 UTC, luislhl commented on serverless.yml
> +    memorySize: 256
Done

2021-07-08 17:57 UTC, luislhl commented on serverless.yml
> +# package:
Done

2021-07-08 17:58 UTC, luislhl commented on serverless.yml
> +    NETWORK: ${env:NETWORK}
Done. I can pass you those secrets later.

2021-07-09 08:43 UTC, msbrogli approved these changes

2021-07-09 08:43 UTC, msbrogli commented on serverless.yml
> +  memorySize: 256
What's this parameter? RAM? MB? GB? Minimum value?

2021-07-09 08:43 UTC, msbrogli commented on serverless.yml
>      handler: src/api/auth.tokenHandler
Shouldn't we add a timeout here as well? Can we set a default value that is used in case one is not provided?

2021-07-09 16:58 UTC, luislhl commented on serverless.yml
> +  memorySize: 256
RAM, MB.

It's the memory allocated for the Lambda. So, Maximum memory it can use.

I will add a comment explaining it.

2021-07-09 17:00 UTC, luislhl commented on serverless.yml
>      handler: src/api/auth.tokenHandler
We can set the default value. The default default value is 6s, so every Lambda that is not defining it should be using 6s as timeout.

I think @andreabadesso and @r4mmer are better positioned to specify which timeout each Lambda should have, or if 6s is enough.

2021-07-09 17:05 UTC, luislhl commented on serverless.yml
>      handler: src/api/auth.tokenHandler
I've also set the timeout explicitly for Lambdas that have not set it just for clarity, but I've put 6s, which was already the default.

2021-07-09 17:06 UTC, r4mmer commented on serverless.yml
>      handler: src/api/auth.tokenHandler
The `authTokenApi` should be our fastest lambda since it does not access the db or redis. Having a short timeout in this one wouldn't hurt.

2021-07-09 17:12 UTC, andreabadesso approved these changes

2021-07-09 17:15 UTC, luislhl commented on serverless.yml
>      handler: src/api/auth.tokenHandler
Done

2021-07-09 17:16 UTC, merged