feat: tx proposal
HathorNetwork/hathor-wallet-service-old pull request #9
Opened 2020-09-02 17:35 UTC by obiyankenobi

I'm having some problems with `bitcore-lib` and `hathor-wallet-lib`. It'll be easier if I make some changes to the lib so I don't have to generate the addresses in this service and won't need to import `bitcore-lib` directly.

Since this code (address generation) was introduced on #4 , I'll go back to it and start making all the changes suggested. When that is done, I can come back to this PR to finish what's left. But in theory, most of the work is done and the tx is assembled and ready to be sent.

2020-09-04 14:33 UTC, obiyankenobi commented on src/api/txProposalCreate.ts
> +      inputs: inputUtxos.map((utxo) => ({ txId: utxo.txId, index: utxo.index })),
Also need to return the tokens array, as it's needed to assemble the tx for mining.

2021-01-27 10:01 UTC, msbrogli requested changes

2021-01-27 10:01 UTC, msbrogli commented on .env.production
> +MAX_ADDRESS_GAP=10
I feel the default value should be `20`. Any reason to change it?

2021-01-27 10:01 UTC, msbrogli commented on .gitignore
> +.env
You removed the `.env` file. Shouldn't it be `.env.*`?

2021-01-27 10:01 UTC, msbrogli commented on DATABASE.md
> +CREATE TABLE `version_data` (
Why don't we store it in memory? I feel we should get it from the fullnode when the service starts.

2021-01-27 10:01 UTC, msbrogli commented on DATABASE.md
> +CREATE TABLE `tx_proposal` (
Duplicate?

2021-01-27 10:01 UTC, msbrogli commented on DATABASE.md
> +  PRIMARY KEY (`id`)
Maybe we should index `wallet_id` for fast queries.

2021-01-27 10:01 UTC, msbrogli commented on DATABASE.md
> +  PRIMARY KEY (`tx_proposal_id`,`index`)
In previous version, MySQL supported `O(1)` search using `tx_proposal_id` even though it is a multi-key hash index. Is it true for the latest version? Maybe we should include a `tx_proposal_id` hash index.

2021-01-27 10:01 UTC, msbrogli commented on DATABASE.md
> +  `timelock` int unsigned DEFAULT NULL,
Why do we need a timelock here? I feel we should never create a tx_proposal with locked outputs.

2021-01-27 10:01 UTC, msbrogli commented on src/api/errors.ts
> +  INVALID_SELECTION_ALGO = 'invalid-selection-algo',
Why abbreviate?

2021-01-27 10:01 UTC, msbrogli commented on src/api/wallet.ts
> -/**
Removed the license header by mistake?

2021-01-27 10:01 UTC, msbrogli commented on src/commons.ts
> +import { ServerlessMysql } from 'serverless-mysql';
Missing license header.

2021-01-27 10:01 UTC, msbrogli commented on src/commons.ts
> +import {
Would you create a new PR for the refactor? It is way harder to review a mix of a big refactor with new features.

2021-01-27 10:03 UTC, msbrogli commented
@andreabadesso I haven't finished the review. I stopped when I reached a major refactor mixed with a new feature. I suggested you to split this PR in two parts: (i) a refactor, and (ii) the tx proposal feature.

2021-01-27 12:53 UTC, andreabadesso commented on DATABASE.md
> +CREATE TABLE `version_data` (
Because the service is runnning on lambda, they should be stateless.

2021-01-27 12:55 UTC, andreabadesso commented on DATABASE.md
> +  PRIMARY KEY (`id`)
I agree. There is a separate issue to use an ORM and optimize the database though

2021-02-25 17:20 UTC, merged

2021-03-04 22:02 UTC, andreabadesso commented on DATABASE.md
> +  `timelock` int unsigned DEFAULT NULL,
This commit was killed in the rebase, but I believe you were asking about `timelock` in `tx_proposal_outputs`

`tx_proposal_outputs` are the outputs that are being created, not the utxos that are being spent

2021-03-04 22:03 UTC, andreabadesso commented on DATABASE.md
> +  PRIMARY KEY (`tx_proposal_id`,`index`)
I agree, but there is already an issue to add indexes to tables

This will come with the ORM

2021-03-05 05:11 UTC, msbrogli commented on DATABASE.md
> +  `timelock` int unsigned DEFAULT NULL,
I got it. Thanks for the explanation.

2021-03-10 18:32 UTC, andreabadesso commented on src/api/txProposalCreate.ts
> +      inputs: inputUtxos.map((utxo) => ({ txId: utxo.txId, index: utxo.index })),
Done in https://github.com/HathorNetwork/hathor-wallet-service/pull/36