fix: treat exceptions from jsonwebtoken
HathorNetwork/hathor-wallet-service-old pull request #92
Opened 2021-07-06 23:37 UTC by r4mmer

2021-07-07 15:36 UTC, andreabadesso requested changes

2021-07-07 15:36 UTC, andreabadesso commented on src/api/auth.ts
> +    if (e.name === 'JsonWebTokenError') {
What is this error? An invalid JWT was sent from the user?

2021-07-07 15:36 UTC, andreabadesso commented on src/api/auth.ts
> +  } catch (e) {
I think we should log every unhandled error here

2021-07-07 15:36 UTC, andreabadesso commented on src/api/auth.ts
> +    // XXX: find a way to return specific error to frontend or make all errors Unauthorized?
I think it would be nice to inform the user the type of error, if possible

2021-07-07 15:41 UTC, r4mmer commented on src/api/auth.ts
> +    if (e.name === 'JsonWebTokenError') {
This is the most generic error, invalid jwt (like `"Bearer 123"`) or secret mismatch, any error that prevents the lib from verifying that this token is valid except for errors related to the headers `exp` and `nbf`.

2021-07-07 15:44 UTC, r4mmer commented on src/api/auth.ts
> +  } catch (e) {
Done.

2021-07-07 15:47 UTC, r4mmer commented on src/api/auth.ts
> +    // XXX: find a way to return specific error to frontend or make all errors Unauthorized?
I need to test this, but if the error thrown is an instance of `Error`, the API Gateway will return the message inside to the user along with a 401 (i think). I don't like exposing internal errors to the user but we could do it.

2021-07-08 01:26 UTC, pedroferreira1 approved these changes

2021-07-08 13:44 UTC, andreabadesso commented on src/api/auth.ts
> +    // XXX: find a way to return specific error to frontend or make all errors Unauthorized?
I agree with not exposing internal errors, but we are in control of the error that will get thrown here, right?

We could just throw an error with the nessage we want inside the catch block

2021-07-08 14:00 UTC, andreabadesso approved these changes

2021-07-08 16:55 UTC, merged