feat(db): migrations
HathorNetwork/hathor-wallet-service-old pull request #94
Opened 2021-07-07 19:43 UTC by r4mmer

2021-07-09 21:13 UTC, luislhl commented on db/models/address.js
> +    wallet_id: {
Why aren't we using Foreign Keys for references like this one?

2021-07-09 21:20 UTC, luislhl commented on db/models/addressbalance.js
> +} = require('sequelize');
Did you have a specific reason for using Javascript instead of Typescript?

2021-07-09 21:49 UTC, luislhl commented on db/config.js
> +  test: {
What exactly selects between those options? An EnvVar?

2021-07-12 16:09 UTC, r4mmer commented on db/models/address.js
> +    wallet_id: {
I translated the same database schema we are currently using, it does not have foreign keys. We can add them, but for this first PR I think we should aim to have the same db described in `DATABASE.md`

2021-07-12 16:13 UTC, r4mmer commented on db/models/addressbalance.js
> +} = require('sequelize');
Sequelize does not support typescript for migration scripts, and since we are not using the models (we won't change the queries or use the ORM part of sequelize in this PR) I made them for description and reference only (later we could easily translate to typescript using these as base).

2021-07-12 16:18 UTC, r4mmer commented on db/config.js
> +  test: {
There are 2 ways to select the environment, using the EnvVar `NODE_ENV` or by the `--env` parameter (default is `development`). Sequelize docs on the matter [here](https://sequelize.org/master/manual/migrations.html#configuration)

2021-07-12 16:40 UTC, luislhl commented on db/models/address.js
> +    wallet_id: {
Makes sense. But do we already have another issue to discuss the use of Foreign Keys?

2021-07-12 16:44 UTC, luislhl approved these changes

2021-07-12 18:59 UTC, andreabadesso requested changes

2021-07-12 18:59 UTC, andreabadesso commented on db/config.js
> +      // ssl: {
Remove this?

2021-07-12 18:59 UTC, andreabadesso commented on db/migrations/20210707174416-create-tx-proposal.js
> +      wallet_id: {
You could use camelCase here and define the field name as `wallet_id`

What do you think?

2021-07-12 18:59 UTC, andreabadesso commented on package.json
> +    "sqlite3": "^5.0.2",
What are we using it for?

I think we should remove it until we refactor the queries to be able to run on sqlite3

2021-07-12 18:59 UTC, andreabadesso commented on db/seeders/mainnet.js
> +        queryInterface.bulkInsert('metadata', [{
We are not using `metadata` anymore, we are currently fetching the latest block from the `transactions` table

We should also remove it from `DATABASE.md`

2021-07-12 18:59 UTC, andreabadesso commented on package.json
>      "typescript": "^3.9.5",
*Unrelated to line number:*

I think we should add the comments from `DATABASE.md` on the models, example:

on `tx_output` table, we should add a comment explaining that `tx_id` might be a block

2021-07-13 13:17 UTC, r4mmer commented on db/models/address.js
> +    wallet_id: {
No we don't

2021-07-13 13:32 UTC, r4mmer commented on db/migrations/20210707174416-create-tx-proposal.js
> +      wallet_id: {
For migrations I don't think it would make sense, and we could add this to the models, but since we will be using the models just for reference (for now) I think we should keep them as closely related to the migration schema as we can.

2021-07-13 13:32 UTC, r4mmer commented on db/config.js
> +      // ssl: {
Done.

2021-07-13 13:33 UTC, r4mmer commented on package.json
> +    "sqlite3": "^5.0.2",
Done.

2021-07-13 14:20 UTC, r4mmer commented on package.json
>      "typescript": "^3.9.5",
Done.

2021-07-13 14:20 UTC, r4mmer commented on db/seeders/mainnet.js
> +        queryInterface.bulkInsert('metadata', [{
Done.

2021-07-13 15:18 UTC, pedroferreira1 commented on db/migrations/20210706163010-create-address.js
> +'use strict'; // eslint-disable-line
No need to do it in this PR but in this table definition is possible to add db indexes already?

2021-07-13 15:18 UTC, pedroferreira1 commented on db/config.js
> +    username: process.env.CI_DB_USERNAME,
This is for testing or for CI?

2021-07-13 15:18 UTC, pedroferreira1 commented on db/migrations/20210706164553-create-address-balance.js
> +        primaryKey: true,
When you set 2 `primaryKey: true` it means they are unique together? Because `address` can be repeated, just like `token_uid`

2021-07-13 15:18 UTC, pedroferreira1 commented on db/migrations/20210707190612-create-transaction.js
> +    }).then(() => queryInterface.addIndex(
Nice, is it our only index for now?

2021-07-13 15:18 UTC, pedroferreira1 commented on db/models/address.js
> +    wallet_id: {
I think it's important to create. And I agree to keep this out of this PR context

2021-07-13 17:35 UTC, r4mmer commented on db/migrations/20210706163010-create-address.js
> +'use strict'; // eslint-disable-line
Yes, we are already adding an index for the `transaction` table.

2021-07-13 17:37 UTC, r4mmer commented on db/config.js
> +    username: process.env.CI_DB_USERNAME,
CI, but we could add another for testing only if we need it.

2021-07-13 17:39 UTC, r4mmer commented on db/migrations/20210706164553-create-address-balance.js
> +        primaryKey: true,
Yes, it translates to SQL as `PRIMARY KEY (address, token_id)`, both columns together are the primary key.

2021-07-13 17:40 UTC, r4mmer commented on db/migrations/20210707190612-create-transaction.js
> +    }).then(() => queryInterface.addIndex(
Yes.

2021-07-13 18:51 UTC, andreabadesso approved these changes

2021-07-13 18:56 UTC, merged